version: 2

project_name: arcentra

before:
  hooks:
    # Avoid generating uncommitted changes in CI
    - go mod download

builds:
  - id: arcentra
    main: ./cmd/arcentra
    binary: arcentra
    env:
      # NOTE: arcentra uses kafka (confluent-kafka-go) in the codebase; keep CGO enabled.
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags: &ldflags_common
      - -s -w
      - -X 'github.com/arcentrix/arcentra/pkg/version.Version={{ .Version }}'
      - -X 'github.com/arcentrix/arcentra/pkg/version.GitBranch={{ .Branch }}'
      - -X 'github.com/arcentrix/arcentra/pkg/version.GitCommit={{ .Commit }}'
      - -X 'github.com/arcentrix/arcentra/pkg/version.BuildTime={{ .Date }}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: arcentra-agent
    main: ./cmd/arcentra-agent
    binary: arcentra-agent
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags: *ldflags_common
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: arcentra
    builds: [arcentra]
    format: tar.gz
    wrap_in_directory: true
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}-{{ .Version }}
    files:
      - README.md
      - LICENSE
      - conf.d/*.toml
      - deploy/*

  - id: arcentra-agent
    builds: [arcentra-agent]
    format: tar.gz
    wrap_in_directory: true
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}-{{ .Version }}
    files:
      - README.md
      - LICENSE
      - conf.d/*.toml
      - deploy/*

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^refactor:"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  # Ensure release title uses version (without optional "v" prefix)
  name_template: "{{ .Version }}"
  prerelease: auto
