// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package dal

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const agentCount = `-- name: AgentCount :one
SELECT COUNT(*) FROM t_agent
`

// AgentCount Agent 总数
func (q *Queries) AgentCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, agentCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const agentCountByStatusOffline = `-- name: AgentCountByStatusOffline :one
SELECT COUNT(*) FROM t_agent WHERE status = 2
`

// AgentCountByStatusOffline 离线 Agent 数量（status=2）
func (q *Queries) AgentCountByStatusOffline(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, agentCountByStatusOffline)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const agentCountByStatusOnline = `-- name: AgentCountByStatusOnline :one
SELECT COUNT(*) FROM t_agent WHERE status = 1
`

// AgentCountByStatusOnline 在线 Agent 数量（status=1）
func (q *Queries) AgentCountByStatusOnline(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, agentCountByStatusOnline)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const agentCreate = `-- name: AgentCreate :exec

INSERT INTO t_agent (agent_id, agent_name, address, port, os, arch, version, status, labels, metrics, is_enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AgentCreateParams struct {
	AgentID   string          `json:"agent_id"`
	AgentName string          `json:"agent_name"`
	Address   sql.NullString  `json:"address"`
	Port      sql.NullString  `json:"port"`
	Os        sql.NullString  `json:"os"`
	Arch      sql.NullString  `json:"arch"`
	Version   sql.NullString  `json:"version"`
	Status    int8            `json:"status"`
	Labels    json.RawMessage `json:"labels"`
	Metrics   sql.NullString  `json:"metrics"`
	IsEnabled int8            `json:"is_enabled"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// AgentCreate 创建 Agent
func (q *Queries) AgentCreate(ctx context.Context, arg AgentCreateParams) error {
	_, err := q.db.ExecContext(ctx, agentCreate,
		arg.AgentID,
		arg.AgentName,
		arg.Address,
		arg.Port,
		arg.Os,
		arg.Arch,
		arg.Version,
		arg.Status,
		arg.Labels,
		arg.Metrics,
		arg.IsEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const agentDeleteByAgentId = `-- name: AgentDeleteByAgentId :exec
DELETE FROM t_agent WHERE agent_id = ?
`

type AgentDeleteByAgentIdParams struct {
	AgentID string `json:"agent_id"`
}

// AgentDeleteByAgentId 按 agent_id 删除 Agent
func (q *Queries) AgentDeleteByAgentId(ctx context.Context, arg AgentDeleteByAgentIdParams) error {
	_, err := q.db.ExecContext(ctx, agentDeleteByAgentId, arg.AgentID)
	return err
}

const agentGetByAgentId = `-- name: AgentGetByAgentId :one
SELECT id, agent_id, agent_name, address, port, os, arch, version, status, labels, metrics, is_enabled, created_at, updated_at
FROM t_agent WHERE agent_id = ? LIMIT 1
`

type AgentGetByAgentIdParams struct {
	AgentID string `json:"agent_id"`
}

// AgentGetByAgentId 按 agent_id 获取 Agent
func (q *Queries) AgentGetByAgentId(ctx context.Context, arg AgentGetByAgentIdParams) (TAgent, error) {
	row := q.db.QueryRowContext(ctx, agentGetByAgentId, arg.AgentID)
	var i TAgent
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AgentName,
		&i.Address,
		&i.Port,
		&i.Os,
		&i.Arch,
		&i.Version,
		&i.Status,
		&i.Labels,
		&i.Metrics,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const agentList = `-- name: AgentList :many
SELECT id, agent_id, agent_name, address, port, os, arch, version, status, labels, metrics, is_enabled
FROM t_agent ORDER BY id LIMIT ? OFFSET ?
`

type AgentListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AgentListRow struct {
	ID        uint64          `json:"id"`
	AgentID   string          `json:"agent_id"`
	AgentName string          `json:"agent_name"`
	Address   sql.NullString  `json:"address"`
	Port      sql.NullString  `json:"port"`
	Os        sql.NullString  `json:"os"`
	Arch      sql.NullString  `json:"arch"`
	Version   sql.NullString  `json:"version"`
	Status    int8            `json:"status"`
	Labels    json.RawMessage `json:"labels"`
	Metrics   sql.NullString  `json:"metrics"`
	IsEnabled int8            `json:"is_enabled"`
}

// AgentList Agent 列表分页
func (q *Queries) AgentList(ctx context.Context, arg AgentListParams) ([]AgentListRow, error) {
	rows, err := q.db.QueryContext(ctx, agentList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentListRow{}
	for rows.Next() {
		var i AgentListRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentName,
			&i.Address,
			&i.Port,
			&i.Os,
			&i.Arch,
			&i.Version,
			&i.Status,
			&i.Labels,
			&i.Metrics,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentPatchByAgentId = `-- name: AgentPatchByAgentId :exec
UPDATE t_agent SET status = COALESCE(?, status), updated_at = ? WHERE agent_id = ?
`

type AgentPatchByAgentIdParams struct {
	Status    int8      `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	AgentID   string    `json:"agent_id"`
}

// AgentPatchByAgentId 按 agent_id 部分更新（如 status, last_heartbeat）
func (q *Queries) AgentPatchByAgentId(ctx context.Context, arg AgentPatchByAgentIdParams) error {
	_, err := q.db.ExecContext(ctx, agentPatchByAgentId, arg.Status, arg.UpdatedAt, arg.AgentID)
	return err
}

const agentUpdateByAgentId = `-- name: AgentUpdateByAgentId :exec
UPDATE t_agent SET agent_name = ?, address = ?, port = ?, os = ?, arch = ?, version = ?, status = ?, labels = ?, metrics = ?, is_enabled = ?, updated_at = ? WHERE agent_id = ?
`

type AgentUpdateByAgentIdParams struct {
	AgentName string          `json:"agent_name"`
	Address   sql.NullString  `json:"address"`
	Port      sql.NullString  `json:"port"`
	Os        sql.NullString  `json:"os"`
	Arch      sql.NullString  `json:"arch"`
	Version   sql.NullString  `json:"version"`
	Status    int8            `json:"status"`
	Labels    json.RawMessage `json:"labels"`
	Metrics   sql.NullString  `json:"metrics"`
	IsEnabled int8            `json:"is_enabled"`
	UpdatedAt time.Time       `json:"updated_at"`
	AgentID   string          `json:"agent_id"`
}

// AgentUpdateByAgentId 按 agent_id 全量更新 Agent
func (q *Queries) AgentUpdateByAgentId(ctx context.Context, arg AgentUpdateByAgentIdParams) error {
	_, err := q.db.ExecContext(ctx, agentUpdateByAgentId,
		arg.AgentName,
		arg.Address,
		arg.Port,
		arg.Os,
		arg.Arch,
		arg.Version,
		arg.Status,
		arg.Labels,
		arg.Metrics,
		arg.IsEnabled,
		arg.UpdatedAt,
		arg.AgentID,
	)
	return err
}
