// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: general_settings.sql

package dal

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	datatypes "gorm.io/datatypes"
)

const generalSettingsGetByCategoryAndName = `-- name: GeneralSettingsGetByCategoryAndName :one
SELECT id, settings_id, category, name, display_name, data, ` + "`" + `schema` + "`" + `, description, created_at, updated_at FROM t_general_settings WHERE category = ? AND name = ? LIMIT 1
`

type GeneralSettingsGetByCategoryAndNameParams struct {
	Category string `json:"category"`
	Name     string `json:"name"`
}

// GeneralSettingsGetByCategoryAndName 按 category 与 name 获取完整配置
func (q *Queries) GeneralSettingsGetByCategoryAndName(ctx context.Context, arg GeneralSettingsGetByCategoryAndNameParams) (TGeneralSetting, error) {
	row := q.db.QueryRowContext(ctx, generalSettingsGetByCategoryAndName, arg.Category, arg.Name)
	var i TGeneralSetting
	err := row.Scan(
		&i.ID,
		&i.SettingsID,
		&i.Category,
		&i.Name,
		&i.DisplayName,
		&i.Data,
		&i.Schema,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const generalSettingsGetBySettingsId = `-- name: GeneralSettingsGetBySettingsId :one
SELECT name, category FROM t_general_settings WHERE settings_id = ? LIMIT 1
`

type GeneralSettingsGetBySettingsIdParams struct {
	SettingsID string `json:"settings_id"`
}

type GeneralSettingsGetBySettingsIdRow struct {
	Name     string `json:"name"`
	Category string `json:"category"`
}

// GeneralSettingsGetBySettingsId 按 settings_id 仅取 name, category（用于再查 GetByName）
func (q *Queries) GeneralSettingsGetBySettingsId(ctx context.Context, arg GeneralSettingsGetBySettingsIdParams) (GeneralSettingsGetBySettingsIdRow, error) {
	row := q.db.QueryRowContext(ctx, generalSettingsGetBySettingsId, arg.SettingsID)
	var i GeneralSettingsGetBySettingsIdRow
	err := row.Scan(&i.Name, &i.Category)
	return i, err
}

const generalSettingsGetCategories = `-- name: GeneralSettingsGetCategories :many
SELECT DISTINCT category FROM t_general_settings
`

// GeneralSettingsGetCategories 获取所有不重复的 category
func (q *Queries) GeneralSettingsGetCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, generalSettingsGetCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const generalSettingsList = `-- name: GeneralSettingsList :many
SELECT id, settings_id, category, name, display_name, data, ` + "`" + `schema` + "`" + `, description
FROM t_general_settings WHERE (? = '' OR category = ?) ORDER BY id DESC LIMIT ? OFFSET ?
`

type GeneralSettingsListParams struct {
	Column1  interface{} `json:"column_1"`
	Category string      `json:"category"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type GeneralSettingsListRow struct {
	ID          uint64          `json:"id"`
	SettingsID  string          `json:"settings_id"`
	Category    string          `json:"category"`
	Name        string          `json:"name"`
	DisplayName string          `json:"display_name"`
	Data        datatypes.JSON  `json:"data"`
	Schema      json.RawMessage `json:"schema"`
	Description sql.NullString  `json:"description"`
}

// GeneralSettingsList 配置列表分页
func (q *Queries) GeneralSettingsList(ctx context.Context, arg GeneralSettingsListParams) ([]GeneralSettingsListRow, error) {
	rows, err := q.db.QueryContext(ctx, generalSettingsList,
		arg.Column1,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeneralSettingsListRow{}
	for rows.Next() {
		var i GeneralSettingsListRow
		if err := rows.Scan(
			&i.ID,
			&i.SettingsID,
			&i.Category,
			&i.Name,
			&i.DisplayName,
			&i.Data,
			&i.Schema,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const generalSettingsListCount = `-- name: GeneralSettingsListCount :one
SELECT COUNT(*) FROM t_general_settings WHERE (? = '' OR category = ?)
`

type GeneralSettingsListCountParams struct {
	Column1  interface{} `json:"column_1"`
	Category string      `json:"category"`
}

// GeneralSettingsListCount 配置列表总数（可选 category）
func (q *Queries) GeneralSettingsListCount(ctx context.Context, arg GeneralSettingsListCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, generalSettingsListCount, arg.Column1, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const generalSettingsUpdateBySettingsId = `-- name: GeneralSettingsUpdateBySettingsId :exec

UPDATE t_general_settings SET display_name = ?, data = ?, ` + "`" + `schema` + "`" + ` = ?, description = ?, updated_at = ? WHERE settings_id = ?
`

type GeneralSettingsUpdateBySettingsIdParams struct {
	DisplayName string          `json:"display_name"`
	Data        datatypes.JSON  `json:"data"`
	Schema      json.RawMessage `json:"schema"`
	Description sql.NullString  `json:"description"`
	UpdatedAt   time.Time       `json:"updated_at"`
	SettingsID  string          `json:"settings_id"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// GeneralSettingsUpdateBySettingsId 按 settings_id 更新（不含 id, settings_id, category, name）
func (q *Queries) GeneralSettingsUpdateBySettingsId(ctx context.Context, arg GeneralSettingsUpdateBySettingsIdParams) error {
	_, err := q.db.ExecContext(ctx, generalSettingsUpdateBySettingsId,
		arg.DisplayName,
		arg.Data,
		arg.Schema,
		arg.Description,
		arg.UpdatedAt,
		arg.SettingsID,
	)
	return err
}
