// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package dal

import (
	"context"
	"database/sql"
	"time"

	datatypes "gorm.io/datatypes"
)

const identityCreate = `-- name: IdentityCreate :exec
INSERT INTO t_identity (provider_id, provider_type, name, description, config, priority, is_enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type IdentityCreateParams struct {
	ProviderID   string         `json:"provider_id"`
	ProviderType string         `json:"provider_type"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Config       datatypes.JSON `json:"config"`
	Priority     int32          `json:"priority"`
	IsEnabled    int8           `json:"is_enabled"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// IdentityCreate 创建身份提供商
func (q *Queries) IdentityCreate(ctx context.Context, arg IdentityCreateParams) error {
	_, err := q.db.ExecContext(ctx, identityCreate,
		arg.ProviderID,
		arg.ProviderType,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Priority,
		arg.IsEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const identityDeleteByName = `-- name: IdentityDeleteByName :exec
DELETE FROM t_identity WHERE name = ?
`

type IdentityDeleteByNameParams struct {
	Name string `json:"name"`
}

// IdentityDeleteByName 按 name 删除
func (q *Queries) IdentityDeleteByName(ctx context.Context, arg IdentityDeleteByNameParams) error {
	_, err := q.db.ExecContext(ctx, identityDeleteByName, arg.Name)
	return err
}

const identityExistsByName = `-- name: IdentityExistsByName :one
SELECT COUNT(*) > 0 FROM t_identity WHERE name = ?
`

type IdentityExistsByNameParams struct {
	Name string `json:"name"`
}

// IdentityExistsByName 判断 name 是否存在
func (q *Queries) IdentityExistsByName(ctx context.Context, arg IdentityExistsByNameParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, identityExistsByName, arg.Name)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const identityGetByName = `-- name: IdentityGetByName :one

SELECT id, provider_id, provider_type, name, description, config, priority, is_enabled, created_at, updated_at FROM t_identity WHERE name = ? LIMIT 1
`

type IdentityGetByNameParams struct {
	Name string `json:"name"`
}

type IdentityGetByNameRow struct {
	ID           int32          `json:"id"`
	ProviderID   string         `json:"provider_id"`
	ProviderType string         `json:"provider_type"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Config       datatypes.JSON `json:"config"`
	Priority     int32          `json:"priority"`
	IsEnabled    int8           `json:"is_enabled"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// IdentityGetByName 按 name 获取身份提供商
func (q *Queries) IdentityGetByName(ctx context.Context, arg IdentityGetByNameParams) (IdentityGetByNameRow, error) {
	row := q.db.QueryRowContext(ctx, identityGetByName, arg.Name)
	var i IdentityGetByNameRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderType,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Priority,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityGetIsEnabledByName = `-- name: IdentityGetIsEnabledByName :one
SELECT is_enabled FROM t_identity WHERE name = ? LIMIT 1
`

type IdentityGetIsEnabledByNameParams struct {
	Name string `json:"name"`
}

// IdentityGetIsEnabledByName 获取当前 is_enabled 用于切换
func (q *Queries) IdentityGetIsEnabledByName(ctx context.Context, arg IdentityGetIsEnabledByNameParams) (int8, error) {
	row := q.db.QueryRowContext(ctx, identityGetIsEnabledByName, arg.Name)
	var is_enabled int8
	err := row.Scan(&is_enabled)
	return is_enabled, err
}

const identityGetProviderTypes = `-- name: IdentityGetProviderTypes :many
SELECT DISTINCT provider_type FROM t_identity
`

// IdentityGetProviderTypes 获取所有不重复的 provider_type
func (q *Queries) IdentityGetProviderTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, identityGetProviderTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var provider_type string
		if err := rows.Scan(&provider_type); err != nil {
			return nil, err
		}
		items = append(items, provider_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListAll = `-- name: IdentityListAll :many
SELECT id, provider_id, provider_type, name, description, config, priority, is_enabled, created_at, updated_at FROM t_identity ORDER BY priority ASC
`

type IdentityListAllRow struct {
	ID           int32          `json:"id"`
	ProviderID   string         `json:"provider_id"`
	ProviderType string         `json:"provider_type"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Config       datatypes.JSON `json:"config"`
	Priority     int32          `json:"priority"`
	IsEnabled    int8           `json:"is_enabled"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// IdentityListAll 列出所有身份提供商
func (q *Queries) IdentityListAll(ctx context.Context) ([]IdentityListAllRow, error) {
	rows, err := q.db.QueryContext(ctx, identityListAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityListAllRow{}
	for rows.Next() {
		var i IdentityListAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderType,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Priority,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListByProviderType = `-- name: IdentityListByProviderType :many
SELECT id, provider_id, provider_type, name, description, config, priority, is_enabled, created_at, updated_at FROM t_identity WHERE provider_type = ? ORDER BY priority ASC
`

type IdentityListByProviderTypeParams struct {
	ProviderType string `json:"provider_type"`
}

type IdentityListByProviderTypeRow struct {
	ID           int32          `json:"id"`
	ProviderID   string         `json:"provider_id"`
	ProviderType string         `json:"provider_type"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Config       datatypes.JSON `json:"config"`
	Priority     int32          `json:"priority"`
	IsEnabled    int8           `json:"is_enabled"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// IdentityListByProviderType 按 provider_type 列出
func (q *Queries) IdentityListByProviderType(ctx context.Context, arg IdentityListByProviderTypeParams) ([]IdentityListByProviderTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, identityListByProviderType, arg.ProviderType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityListByProviderTypeRow{}
	for rows.Next() {
		var i IdentityListByProviderTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ProviderType,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Priority,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityToggleByName = `-- name: IdentityToggleByName :exec
UPDATE t_identity SET is_enabled = ?, updated_at = ? WHERE name = ?
`

type IdentityToggleByNameParams struct {
	IsEnabled int8      `json:"is_enabled"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

// IdentityToggleByName 切换 is_enabled（0/1）
func (q *Queries) IdentityToggleByName(ctx context.Context, arg IdentityToggleByNameParams) error {
	_, err := q.db.ExecContext(ctx, identityToggleByName, arg.IsEnabled, arg.UpdatedAt, arg.Name)
	return err
}

const identityUpdateByName = `-- name: IdentityUpdateByName :exec
UPDATE t_identity SET description = ?, config = ?, priority = ?, is_enabled = ?, updated_at = ? WHERE name = ?
`

type IdentityUpdateByNameParams struct {
	Description sql.NullString `json:"description"`
	Config      datatypes.JSON `json:"config"`
	Priority    int32          `json:"priority"`
	IsEnabled   int8           `json:"is_enabled"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Name        string         `json:"name"`
}

// IdentityUpdateByName 按 name 更新（不含 name, provider_id, provider_type, created_at）
func (q *Queries) IdentityUpdateByName(ctx context.Context, arg IdentityUpdateByNameParams) error {
	_, err := q.db.ExecContext(ctx, identityUpdateByName,
		arg.Description,
		arg.Config,
		arg.Priority,
		arg.IsEnabled,
		arg.UpdatedAt,
		arg.Name,
	)
	return err
}
