// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package dal

import (
	"context"
	"database/sql"
)

const menuBatchGetByMenuIds = `-- name: MenuBatchGetByMenuIds :many
SELECT id, menu_id, parent_id, name, path, component, icon, ` + "`" + `order` + "`" + `, is_visible, is_enabled, description, meta, created_at, updated_at FROM t_menu WHERE menu_id IN (?) AND is_enabled = 1 ORDER BY ` + "`" + `order` + "`" + ` ASC
`

type MenuBatchGetByMenuIdsParams struct {
	MenuID string `json:"menu_id"`
}

// MenuBatchGetByMenuIds 按 menu_id 列表批量获取（仅启用）
func (q *Queries) MenuBatchGetByMenuIds(ctx context.Context, arg MenuBatchGetByMenuIdsParams) ([]TMenu, error) {
	rows, err := q.db.QueryContext(ctx, menuBatchGetByMenuIds, arg.MenuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMenu{}
	for rows.Next() {
		var i TMenu
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.Component,
			&i.Icon,
			&i.Order,
			&i.IsVisible,
			&i.IsEnabled,
			&i.Description,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuGetByMenuId = `-- name: MenuGetByMenuId :one

SELECT id, menu_id, parent_id, name, path, component, icon, ` + "`" + `order` + "`" + `, is_visible, is_enabled, description, meta, created_at, updated_at FROM t_menu WHERE menu_id = ? AND is_enabled = 1 LIMIT 1
`

type MenuGetByMenuIdParams struct {
	MenuID string `json:"menu_id"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// MenuGetByMenuId 按 menu_id 获取菜单（仅启用）
func (q *Queries) MenuGetByMenuId(ctx context.Context, arg MenuGetByMenuIdParams) (TMenu, error) {
	row := q.db.QueryRowContext(ctx, menuGetByMenuId, arg.MenuID)
	var i TMenu
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.ParentID,
		&i.Name,
		&i.Path,
		&i.Component,
		&i.Icon,
		&i.Order,
		&i.IsVisible,
		&i.IsEnabled,
		&i.Description,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const menuList = `-- name: MenuList :many
SELECT id, menu_id, parent_id, name, path, component, icon, ` + "`" + `order` + "`" + `, is_visible, is_enabled, description, meta, created_at, updated_at FROM t_menu WHERE is_enabled = 1 ORDER BY ` + "`" + `order` + "`" + ` ASC
`

// MenuList 列出所有启用菜单
func (q *Queries) MenuList(ctx context.Context) ([]TMenu, error) {
	rows, err := q.db.QueryContext(ctx, menuList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMenu{}
	for rows.Next() {
		var i TMenu
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.Component,
			&i.Icon,
			&i.Order,
			&i.IsVisible,
			&i.IsEnabled,
			&i.Description,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuListByParentId = `-- name: MenuListByParentId :many
SELECT id, menu_id, parent_id, name, path, component, icon, ` + "`" + `order` + "`" + `, is_visible, is_enabled, description, meta, created_at, updated_at FROM t_menu WHERE parent_id = ? AND is_enabled = 1 ORDER BY ` + "`" + `order` + "`" + ` ASC
`

type MenuListByParentIdParams struct {
	ParentID sql.NullString `json:"parent_id"`
}

// MenuListByParentId 按 parent_id 列出子菜单（仅启用）
func (q *Queries) MenuListByParentId(ctx context.Context, arg MenuListByParentIdParams) ([]TMenu, error) {
	rows, err := q.db.QueryContext(ctx, menuListByParentId, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TMenu{}
	for rows.Next() {
		var i TMenu
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Name,
			&i.Path,
			&i.Component,
			&i.Icon,
			&i.Order,
			&i.IsVisible,
			&i.IsEnabled,
			&i.Description,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
