// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dal

import (
	"database/sql"
	"encoding/json"
	"time"

	datatypes "gorm.io/datatypes"
)

// 步骤执行记录表
type LStepRunRecord struct {
	StepRunID     string          `json:"step_run_id"`
	StepRunType   string          `json:"step_run_type"`
	Status        string          `json:"status"`
	Queue         string          `json:"queue"`
	Priority      int32           `json:"priority"`
	PipelineID    sql.NullString  `json:"pipeline_id"`
	PipelineRunID sql.NullString  `json:"pipeline_run_id"`
	StageID       sql.NullString  `json:"stage_id"`
	JobID         sql.NullString  `json:"job_id"`
	JobRunID      sql.NullString  `json:"job_run_id"`
	AgentID       sql.NullString  `json:"agent_id"`
	Payload       json.RawMessage `json:"payload"`
	CreateTime    time.Time       `json:"create_time"`
	StartTime     sql.NullTime    `json:"start_time"`
	EndTime       sql.NullTime    `json:"end_time"`
	Duration      sql.NullInt64   `json:"duration"`
	RetryCount    int32           `json:"retry_count"`
	CurrentRetry  int32           `json:"current_retry"`
	ErrorMessage  sql.NullString  `json:"error_message"`
}

// 任务队列记录表
type LTaskRecord struct {
	TaskID      string          `json:"task_id"`
	TaskType    string          `json:"task_type"`
	TaskPayload datatypes.JSON  `json:"task_payload"`
	Status      string          `json:"status"`
	Queue       string          `json:"queue"`
	Priority    int32           `json:"priority"`
	CreatedAt   time.Time       `json:"created_at"`
	QueuedAt    sql.NullTime    `json:"queued_at"`
	ProcessAt   sql.NullTime    `json:"process_at"`
	StartedAt   sql.NullTime    `json:"started_at"`
	CompletedAt sql.NullTime    `json:"completed_at"`
	FailedAt    sql.NullTime    `json:"failed_at"`
	Error       sql.NullString  `json:"error"`
	RetryCount  int32           `json:"retry_count"`
	Metadata    json.RawMessage `json:"metadata"`
}

// 终端输出表
type LTerminalOutputRecord struct {
	SessionID        string          `json:"session_id"`
	SessionType      string          `json:"session_type"`
	Environment      string          `json:"environment"`
	StepRunID        sql.NullString  `json:"step_run_id"`
	PipelineID       sql.NullString  `json:"pipeline_id"`
	PipelineRunID    sql.NullString  `json:"pipeline_run_id"`
	UserID           string          `json:"user_id"`
	Hostname         string          `json:"hostname"`
	WorkingDirectory string          `json:"working_directory"`
	Command          string          `json:"command"`
	ExitCode         sql.NullInt32   `json:"exit_code"`
	Logs             json.RawMessage `json:"logs"`
	Metadata         json.RawMessage `json:"metadata"`
	Status           string          `json:"status"`
	StartTime        time.Time       `json:"start_time"`
	EndTime          sql.NullTime    `json:"end_time"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

// Agent表
type TAgent struct {
	// 主键ID
	ID uint64 `json:"id"`
	// Agent唯一标识
	AgentID string `json:"agent_id"`
	// Agent名称
	AgentName string `json:"agent_name"`
	// Agent地址
	Address sql.NullString `json:"address"`
	// Agent端口
	Port sql.NullString `json:"port"`
	// 操作系统
	Os sql.NullString `json:"os"`
	// 架构(amd64/arm64)
	Arch sql.NullString `json:"arch"`
	// Agent版本
	Version sql.NullString `json:"version"`
	// Agent状态: 0-未知,1-在线,2-离线,3-忙碌,4-空闲
	Status int8 `json:"status"`
	// Agent标签
	Labels json.RawMessage `json:"labels"`
	// Agent指标
	Metrics sql.NullString `json:"metrics"`
	// 0:禁用,1:启用
	IsEnabled int8 `json:"is_enabled"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// Agent 配置表
type TAgentExt struct {
	// 主键ID
	ID uint64 `json:"id"`
	// Agent唯一标识
	AgentID string `json:"agent_id"`
	// 心跳间隔(秒)
	HeartbeatInterval int32 `json:"heartbeat_interval"`
	// 最大并发任务数
	MaxConcurrentJobs int32 `json:"max_concurrent_jobs"`
	// 任务超时时间(秒)
	JobTimeout int32 `json:"job_timeout"`
	// 工作目录
	WorkspaceDir sql.NullString `json:"workspace_dir"`
	// 临时目录
	TempDir sql.NullString `json:"temp_dir"`
	// 日志级别
	LogLevel sql.NullString `json:"log_level"`
	// 是否启用Docker
	EnableDocker bool `json:"enable_docker"`
	// Docker网络模式
	DockerNetwork sql.NullString `json:"docker_network"`
	// 资源限制(JSON)
	ResourceLimits json.RawMessage `json:"resource_limits"`
	// 禁止执行的命令(JSON数组)
	DeniedCommands json.RawMessage `json:"denied_commands"`
	// 环境变量(JSON对象)
	EnvVars json.RawMessage `json:"env_vars"`
	// 代理地址
	ProxyUrl sql.NullString `json:"proxy_url"`
	// 缓存目录
	CacheDir sql.NullString `json:"cache_dir"`
	// 清理策略(JSON)
	CleanupPolicy json.RawMessage `json:"cleanup_policy"`
	// 配置描述
	Description sql.NullString `json:"description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 操作审计日志表
type TAuditLog struct {
	// 主键ID
	ID int64 `json:"id"`
	// 操作用户ID
	UserID string `json:"user_id"`
	// 操作用户名
	Username string `json:"username"`
	// 操作动作(create/update/delete/execute)
	Action string `json:"action"`
	// 资源类型(pipeline/job/agent/user)
	ResourceType string `json:"resource_type"`
	// 资源ID
	ResourceID sql.NullString `json:"resource_id"`
	// 资源名称
	ResourceName sql.NullString `json:"resource_name"`
	// IP地址
	IpAddress sql.NullString `json:"ip_address"`
	// User Agent
	UserAgent sql.NullString `json:"user_agent"`
	// 请求参数(JSON格式)
	RequestParams json.RawMessage `json:"request_params"`
	// 响应状态码
	ResponseStatus sql.NullInt32 `json:"response_status"`
	// 错误信息
	ErrorMessage sql.NullString `json:"error_message"`
	// 操作时间
	CreatedAt time.Time `json:"created_at"`
}

// 系统配置（结构化设置表）
type TGeneralSetting struct {
	// 主键ID
	ID uint64 `json:"id"`
	// 设置ID
	SettingsID string `json:"settings_id"`
	// 配置类别
	Category string `json:"category"`
	// 配置名称（业务语义字段）
	Name string `json:"name"`
	// 展示名，如 JWT 密钥
	DisplayName string `json:"display_name"`
	// 配置内容，结构化 JSON
	Data datatypes.JSON `json:"data"`
	// 配置的结构定义（JSON Schema 格式，用于前端渲染与校验）
	Schema json.RawMessage `json:"schema"`
	// 配置说明
	Description sql.NullString `json:"description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// SSO认证提供者表
type TIdentity struct {
	// 主键ID
	ID int32 `json:"id"`
	// 提供者唯一标识
	ProviderID string `json:"provider_id"`
	// 提供者名称
	Name string `json:"name"`
	// 提供者类型(oauth/ldap/oidc/saml)
	ProviderType string `json:"provider_type"`
	// 配置内容(根据type不同,内容结构不同)
	Config datatypes.JSON `json:"config"`
	// 描述
	Description sql.NullString `json:"description"`
	// 优先级(数字越小优先级越高)
	Priority int32 `json:"priority"`
	// 0: disabled, 1: enabled
	IsEnabled int8 `json:"is_enabled"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 任务表
type TJob struct {
	// 主键ID
	ID int32 `json:"id"`
	// 任务唯一标识
	JobID string `json:"job_id"`
	// 任务名称
	Name string `json:"name"`
	// 所属流水线ID
	PipelineID sql.NullString `json:"pipeline_id"`
	// 所属流水线执行ID
	PipelineRunID sql.NullString `json:"pipeline_run_id"`
	// 所属阶段ID
	StageID sql.NullString `json:"stage_id"`
	// 阶段序号
	Stage int32 `json:"stage"`
	// 执行的Agent ID
	AgentID sql.NullString `json:"agent_id"`
	// 任务状态: 0-未知, 1-等待, 2-入队, 3-运行中, 4-成功, 5-失败, 6-已取消, 7-超时, 8-已跳过
	Status int8 `json:"status"`
	// 优先级: 1-最高, 5-普通, 10-最低
	Priority int32 `json:"priority"`
	// Docker镜像
	Image sql.NullString `json:"image"`
	// 执行命令列表(JSON数组)
	Commands sql.NullString `json:"commands"`
	// 工作目录
	Workspace sql.NullString `json:"workspace"`
	// 环境变量(JSON格式)
	Env json.RawMessage `json:"env"`
	// 密钥信息(JSON格式)
	Secrets json.RawMessage `json:"secrets"`
	// 超时时间(秒)
	Timeout int32 `json:"timeout"`
	// 重试次数
	RetryCount int32 `json:"retry_count"`
	// 当前重试次数
	CurrentRetry int32 `json:"current_retry"`
	// 是否允许失败: 0-否, 1-是
	AllowFailure int8 `json:"allow_failure"`
	// 标签选择器(JSON格式)
	LabelSelector json.RawMessage `json:"label_selector"`
	// 任务标签(逗号分隔,已废弃)
	Tags sql.NullString `json:"tags"`
	// 依赖的任务ID列表(逗号分隔)
	DependsOn sql.NullString `json:"depends_on"`
	// 退出码
	ExitCode sql.NullInt32 `json:"exit_code"`
	// 错误信息
	ErrorMessage sql.NullString `json:"error_message"`
	// 开始时间
	StartTime sql.NullTime `json:"start_time"`
	// 结束时间
	EndTime sql.NullTime `json:"end_time"`
	// 执行时长(毫秒)
	Duration sql.NullInt64 `json:"duration"`
	// 创建者用户ID
	CreatedBy sql.NullString `json:"created_by"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 任务产物表
type TJobArtifact struct {
	// 主键ID
	ID int32 `json:"id"`
	// 产物唯一标识
	ArtifactID string `json:"artifact_id"`
	// 任务ID
	JobID string `json:"job_id"`
	// 流水线执行ID
	PipelineRunID sql.NullString `json:"pipeline_run_id"`
	// 产物名称
	Name string `json:"name"`
	// 产物路径(支持glob模式)
	Path string `json:"path"`
	// 目标存储路径
	Destination sql.NullString `json:"destination"`
	// 文件大小(字节)
	Size sql.NullInt64 `json:"size"`
	// 存储类型(minio/s3/oss/gcs/cos)
	StorageType sql.NullString `json:"storage_type"`
	// 实际存储路径
	StoragePath sql.NullString `json:"storage_path"`
	// 是否过期: 0-否, 1-是
	Expire int8 `json:"expire"`
	// 过期天数
	ExpireDays sql.NullInt32 `json:"expire_days"`
	// 过期时间
	ExpiredAt sql.NullTime `json:"expired_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 任务插件关联表
type TJobPlugin struct {
	// 主键ID
	ID int32 `json:"id"`
	// 任务ID
	JobID string `json:"job_id"`
	// 插件ID
	PluginID string `json:"plugin_id"`
	// 插件配置ID
	PluginConfigID sql.NullString `json:"plugin_config_id"`
	// 任务特定的插件参数
	Params json.RawMessage `json:"params"`
	// 执行顺序
	ExecutionOrder int32 `json:"execution_order"`
	// 执行阶段(before/after/on_success/on_failure)
	ExecutionStage string `json:"execution_stage"`
	// 执行状态: 0-未执行, 1-执行中, 2-成功, 3-失败
	Status sql.NullInt16 `json:"status"`
	// 执行结果
	Result sql.NullString `json:"result"`
	// 错误信息
	ErrorMessage sql.NullString `json:"error_message"`
	// 开始执行时间
	StartedAt sql.NullTime `json:"started_at"`
	// 完成时间
	CompletedAt sql.NullTime `json:"completed_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 菜单表
type TMenu struct {
	// 主键ID
	ID int32 `json:"id"`
	// 菜单唯一标识
	MenuID string `json:"menu_id"`
	// 父菜单ID（为空表示顶级菜单）
	ParentID sql.NullString `json:"parent_id"`
	// 菜单名称
	Name string `json:"name"`
	// 菜单路径（路由路径）
	Path sql.NullString `json:"path"`
	// 组件路径（前端组件）
	Component sql.NullString `json:"component"`
	// 图标（图标名称或URL）
	Icon sql.NullString `json:"icon"`
	// 排序（数值越小越靠前）
	Order int32 `json:"order"`
	// 是否可见：0-隐藏，1-显示
	IsVisible int8 `json:"is_visible"`
	// 是否启用：0-禁用，1-启用
	IsEnabled int8 `json:"is_enabled"`
	// 菜单描述
	Description sql.NullString `json:"description"`
	// 扩展元数据（JSON格式）
	Meta sql.NullString `json:"meta"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// Notification channel configurations
type TNotificationChannel struct {
	ID uint64 `json:"id"`
	// Unique channel identifier
	ChannelID string `json:"channel_id"`
	// Channel name
	Name string `json:"name"`
	// Channel type (feishu_app/dingtalk/slack/etc)
	Type string `json:"type"`
	// Channel configuration (JSON)
	Config string `json:"config"`
	// Authentication configuration (JSON, optional)
	AuthConfig sql.NullString `json:"auth_config"`
	// Channel description
	Description sql.NullString `json:"description"`
	// Active status
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// Notification sending logs
type TNotificationLog struct {
	ID uint64 `json:"id"`
	// Template ID used
	TemplateID sql.NullString `json:"template_id"`
	// Channel name
	Channel string `json:"channel"`
	// Recipient information
	Recipient sql.NullString `json:"recipient"`
	// Rendered content
	Content sql.NullString `json:"content"`
	// Status (success/failed)
	Status string `json:"status"`
	// Error message if failed
	ErrorMsg sql.NullString `json:"error_msg"`
	// Additional metadata (JSON)
	Metadata sql.NullString `json:"metadata"`
	// Sent timestamp
	SentAt    time.Time `json:"sent_at"`
	CreatedAt time.Time `json:"created_at"`
}

// Notification templates
type TNotificationTemplate struct {
	ID uint64 `json:"id"`
	// Unique template identifier
	TemplateID string `json:"template_id"`
	// Template name
	Name string `json:"name"`
	// Template type (build/approval)
	Type string `json:"type"`
	// Target channel (dingtalk/feishu/slack/etc)
	Channel string `json:"channel"`
	// Template title
	Title sql.NullString `json:"title"`
	// Template content with variables
	Content string `json:"content"`
	// Required variables (JSON array)
	Variables sql.NullString `json:"variables"`
	// Message format (text/markdown/html)
	Format sql.NullString `json:"format"`
	// Additional metadata (JSON)
	Metadata sql.NullString `json:"metadata"`
	// Template description
	Description sql.NullString `json:"description"`
	// Active status
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// 组织表
type TOrganization struct {
	// 主键ID
	ID int32 `json:"id"`
	// 组织唯一标识
	OrgID string `json:"org_id"`
	// 组织名称(英文标识)
	Name string `json:"name"`
	// 组织显示名称
	DisplayName string `json:"display_name"`
	// 组织描述
	Description sql.NullString `json:"description"`
	// 组织Logo URL
	Logo sql.NullString `json:"logo"`
	// 组织官网
	Website sql.NullString `json:"website"`
	// 组织联系邮箱
	Email sql.NullString `json:"email"`
	// 组织联系电话
	Phone sql.NullString `json:"phone"`
	// 组织地址
	Address sql.NullString `json:"address"`
	// 组织设置(JSON格式)
	Settings json.RawMessage `json:"settings"`
	// 订阅计划(free/pro/enterprise)
	Plan string `json:"plan"`
	// 状态: 0-未激活, 1-正常, 2-冻结, 3-已删除
	Status int8 `json:"status"`
	// 组织所有者用户ID
	OwnerUserID string `json:"owner_user_id"`
	// 0: disabled, 1: enabled
	IsEnabled int8 `json:"is_enabled"`
	// 成员总数
	TotalMembers int32 `json:"total_members"`
	// 团队总数
	TotalTeams int32 `json:"total_teams"`
	// 项目总数
	TotalProjects int32 `json:"total_projects"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 组织邀请表
type TOrganizationInvitation struct {
	// 主键ID
	ID int32 `json:"id"`
	// 邀请唯一标识
	InvitationID string `json:"invitation_id"`
	// 组织ID
	OrgID string `json:"org_id"`
	// 被邀请人邮箱
	Email string `json:"email"`
	// 角色(owner/admin/member)
	Role string `json:"role"`
	// 邀请令牌
	Token string `json:"token"`
	// 邀请人用户ID
	InvitedBy string `json:"invited_by"`
	// 状态: 0-待接受, 1-已接受, 2-已拒绝, 3-已过期
	Status int8 `json:"status"`
	// 过期时间
	ExpiresAt time.Time `json:"expires_at"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 组织成员表
type TOrganizationMember struct {
	// 主键ID
	ID int32 `json:"id"`
	// 组织ID
	OrgID string `json:"org_id"`
	// 用户ID
	UserID string `json:"user_id"`
	// 角色ID（引用 t_role）
	RoleID string `json:"role_id"`
	// 用户名(冗余)
	Username sql.NullString `json:"username"`
	// 邮箱(冗余)
	Email sql.NullString `json:"email"`
	// 邀请人用户ID
	InvitedBy sql.NullString `json:"invited_by"`
	// 状态: 0-待接受, 1-正常, 2-禁用
	Status int8 `json:"status"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 流水线定义表
type TPipeline struct {
	// 主键ID
	ID int32 `json:"id"`
	// 流水线唯一标识
	PipelineID string `json:"pipeline_id"`
	// 所属项目ID
	ProjectID sql.NullString `json:"project_id"`
	// 流水线名称
	Name string `json:"name"`
	// 流水线描述
	Description sql.NullString `json:"description"`
	// 代码仓库URL
	RepoUrl sql.NullString `json:"repo_url"`
	// 默认分支
	DefaultBranch sql.NullString `json:"default_branch"`
	// 流水线定义文件路径
	PipelineFilePath string `json:"pipeline_file_path"`
	// 流水线状态: 0-未知, 1-等待, 2-运行中, 3-成功, 4-失败, 5-已取消, 6-暂停
	Status int8 `json:"status"`
	// 保存模式: 1-直推, 2-PR/MR
	SaveMode int8 `json:"save_mode"`
	// PR/MR 目标分支
	PrTargetBranch sql.NullString `json:"pr_target_branch"`
	// 扩展元数据(JSON格式)
	Metadata json.RawMessage `json:"metadata"`
	// 最近同步状态: 0-未知, 1-成功, 2-失败
	LastSyncStatus int8 `json:"last_sync_status"`
	// 最近同步消息
	LastSyncMessage sql.NullString `json:"last_sync_message"`
	// 最近同步时间
	LastSyncedAt sql.NullTime `json:"last_synced_at"`
	// 最近编辑者
	LastEditor sql.NullString `json:"last_editor"`
	// 最近提交 SHA
	LastCommitSha sql.NullString `json:"last_commit_sha"`
	// 最近保存请求幂等 ID
	LastSaveRequestID sql.NullString `json:"last_save_request_id"`
	// 总执行次数
	TotalRuns int32 `json:"total_runs"`
	// 成功次数
	SuccessRuns int32 `json:"success_runs"`
	// 失败次数
	FailedRuns int32 `json:"failed_runs"`
	// 创建者用户ID
	CreatedBy string `json:"created_by"`
	// 是否启用: 0-禁用, 1-启用
	IsEnabled int8 `json:"is_enabled"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 流水线执行记录表
type TPipelineRun struct {
	// 主键ID
	ID int32 `json:"id"`
	// 流水线执行唯一标识
	RunID string `json:"run_id"`
	// 流水线ID
	PipelineID string `json:"pipeline_id"`
	// 触发请求幂等 ID
	RequestID sql.NullString `json:"request_id"`
	// 流水线名称(冗余)
	PipelineName string `json:"pipeline_name"`
	// 分支
	Branch sql.NullString `json:"branch"`
	// Commit SHA
	CommitSha sql.NullString `json:"commit_sha"`
	// 定义文件对应 Commit SHA
	DefinitionCommitSha sql.NullString `json:"definition_commit_sha"`
	// 定义文件路径
	DefinitionPath sql.NullString `json:"definition_path"`
	// 执行状态: 0-未知, 1-等待, 2-运行中, 3-成功, 4-失败, 5-已取消, 6-暂停
	Status int8 `json:"status"`
	// 触发类型: 0-未知, 1-手动, 2-Webhook, 3-定时, 4-API
	TriggerType int8 `json:"trigger_type"`
	// 触发者用户ID
	TriggeredBy sql.NullString `json:"triggered_by"`
	// 环境变量(JSON格式)
	Env json.RawMessage `json:"env"`
	// 总任务数
	TotalJobs int32 `json:"total_jobs"`
	// 已完成任务数
	CompletedJobs int32 `json:"completed_jobs"`
	// 失败任务数
	FailedJobs int32 `json:"failed_jobs"`
	// 运行中任务数
	RunningJobs int32 `json:"running_jobs"`
	// 当前阶段
	CurrentStage int32 `json:"current_stage"`
	// 总阶段数
	TotalStages int32 `json:"total_stages"`
	// 开始时间
	StartTime sql.NullTime `json:"start_time"`
	// 结束时间
	EndTime sql.NullTime `json:"end_time"`
	// 执行时长(毫秒)
	Duration sql.NullInt64 `json:"duration"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 流水线阶段表
type TPipelineStage struct {
	// 主键ID
	ID int32 `json:"id"`
	// 阶段唯一标识
	StageID string `json:"stage_id"`
	// 流水线ID
	PipelineID string `json:"pipeline_id"`
	// 阶段名称
	Name string `json:"name"`
	// 阶段顺序
	StageOrder int32 `json:"stage_order"`
	// 是否并行执行: 0-否, 1-是
	Parallel int8 `json:"parallel"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 项目表
type TProject struct {
	// 主键ID
	ID int32 `json:"id"`
	// 项目唯一标识
	ProjectID string `json:"project_id"`
	// 所属组织ID
	OrgID string `json:"org_id"`
	// 项目名称(英文标识)
	Name string `json:"name"`
	// 项目显示名称
	DisplayName string `json:"display_name"`
	// 项目命名空间(org_name/project_name)
	Namespace string `json:"namespace"`
	// 项目描述
	Description sql.NullString `json:"description"`
	// 代码仓库URL
	RepoUrl string `json:"repo_url"`
	// 仓库类型(git/github/gitlab/gitee/svn)
	RepoType string `json:"repo_type"`
	// 默认分支
	DefaultBranch string `json:"default_branch"`
	// 认证类型: 0-无, 1-用户名密码, 2-Token, 3-SSH密钥
	AuthType int8 `json:"auth_type"`
	// 认证凭证(加密存储)
	Credential sql.NullString `json:"credential"`
	// 触发模式(位掩码): 1-手动, 2-Webhook, 4-定时, 8-Push, 16-MR, 32-Tag
	TriggerMode int32 `json:"trigger_mode"`
	// Webhook密钥
	WebhookSecret sql.NullString `json:"webhook_secret"`
	// 定时任务Cron表达式
	CronExpr sql.NullString `json:"cron_expr"`
	// 构建配置(JSON格式)
	BuildConfig json.RawMessage `json:"build_config"`
	// 环境变量(JSON格式)
	EnvVars json.RawMessage `json:"env_vars"`
	// 项目设置(JSON格式)
	Settings json.RawMessage `json:"settings"`
	// 项目标签(逗号分隔)
	Tags sql.NullString `json:"tags"`
	// 主要编程语言(Go/Java/Python/Node.js等)
	Language sql.NullString `json:"language"`
	// 使用的框架
	Framework sql.NullString `json:"framework"`
	// 项目状态: 0-未激活, 1-正常, 2-归档, 3-禁用
	Status int8 `json:"status"`
	// 可见性: 0-私有, 1-内部, 2-公开
	Visibility int8 `json:"visibility"`
	// 默认访问级别(owner/team/org)
	AccessLevel string `json:"access_level"`
	// 创建者用户ID
	CreatedBy string `json:"created_by"`
	// 是否启用: 0-禁用, 1-启用
	IsEnabled int8 `json:"is_enabled"`
	// 项目图标URL
	Icon sql.NullString `json:"icon"`
	// 项目主页
	Homepage sql.NullString `json:"homepage"`
	// 流水线总数
	TotalPipelines int32 `json:"total_pipelines"`
	// 构建总次数
	TotalBuilds int32 `json:"total_builds"`
	// 成功构建次数
	SuccessBuilds int32 `json:"success_builds"`
	// 失败构建次数
	FailedBuilds int32 `json:"failed_builds"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 项目成员表
type TProjectMember struct {
	// 主键ID
	ID int32 `json:"id"`
	// 项目ID
	ProjectID string `json:"project_id"`
	// 用户ID
	UserID string `json:"user_id"`
	// 角色(owner/maintainer/developer/reporter/guest)
	Role string `json:"role"`
	// 用户名(冗余)
	Username sql.NullString `json:"username"`
	// 来源(direct/team/org)
	Source string `json:"source"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 项目团队访问权限表
type TProjectTeamAccess struct {
	// 主键ID
	ID int32 `json:"id"`
	// 项目ID
	ProjectID string `json:"project_id"`
	// 团队ID
	TeamID string `json:"team_id"`
	// 访问权限: read/write/admin
	AccessLevel string `json:"access_level"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 项目团队关联表
type TProjectTeamRelation struct {
	// 主键ID
	ID int32 `json:"id"`
	// 项目ID
	ProjectID string `json:"project_id"`
	// 团队ID
	TeamID string `json:"team_id"`
	// 访问权限(read/write/admin)
	Access string `json:"access"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 项目变量表
type TProjectVariable struct {
	// 主键ID
	ID int32 `json:"id"`
	// 变量唯一标识
	VariableID string `json:"variable_id"`
	// 项目ID
	ProjectID string `json:"project_id"`
	// 变量键
	Key string `json:"key"`
	// 变量值(敏感信息加密存储)
	Value string `json:"value"`
	// 类型(env/secret/file)
	Type string `json:"type"`
	// 是否保护(仅在保护分支可用): 0-否, 1-是
	Protected int8 `json:"protected"`
	// 是否掩码(日志中隐藏): 0-否, 1-是
	Masked int8 `json:"masked"`
	// 描述
	Description sql.NullString `json:"description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 项目Webhook表
type TProjectWebhook struct {
	// 主键ID
	ID int32 `json:"id"`
	// Webhook唯一标识
	WebhookID string `json:"webhook_id"`
	// 项目ID
	ProjectID string `json:"project_id"`
	// Webhook名称
	Name string `json:"name"`
	// Webhook URL
	Url string `json:"url"`
	// 密钥
	Secret sql.NullString `json:"secret"`
	// 触发事件列表(push/merge_request/tag等)
	Events datatypes.JSON `json:"events"`
	// 0: disabled, 1: enabled
	IsEnabled int8 `json:"is_enabled"`
	// 描述
	Description sql.NullString `json:"description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 角色表（支持自定义角色）
type TRole struct {
	// 主键ID
	ID int32 `json:"id"`
	// 角色唯一标识
	RoleID string `json:"role_id"`
	// 角色名称
	Name string `json:"name"`
	// 角色显示名称
	DisplayName sql.NullString `json:"display_name"`
	// 角色描述
	Description sql.NullString `json:"description"`
	// 0: disabled, 1: enabled
	IsEnabled int8 `json:"is_enabled"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 角色菜单关联表
type TRoleMenuBinding struct {
	// 主键ID
	ID int32 `json:"id"`
	// 关联唯一标识
	RoleMenuID string `json:"role_menu_id"`
	// 角色ID（引用 t_role 表）
	RoleID string `json:"role_id"`
	// 菜单ID（引用 t_menu 表）
	MenuID string `json:"menu_id"`
	// 资源ID（组织ID/团队ID/项目ID，平台级为空）
	ResourceID sql.NullString `json:"resource_id"`
	// 是否可见：0-隐藏，1-显示
	IsVisible int8 `json:"is_visible"`
	// 是否可访问：0-不可访问，1-可访问
	IsAccessible int8 `json:"is_accessible"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 密钥管理表
type TSecret struct {
	// 主键ID
	ID int32 `json:"id"`
	// 密钥唯一标识
	SecretID string `json:"secret_id"`
	// 密钥名称
	Name string `json:"name"`
	// 密钥类型(password/token/ssh_key/env)
	SecretType string `json:"secret_type"`
	// 密钥值(加密存储)
	SecretValue string `json:"secret_value"`
	// 密钥描述
	Description sql.NullString `json:"description"`
	// 作用域(global/pipeline/user)
	Scope string `json:"scope"`
	// 作用域ID
	ScopeID sql.NullString `json:"scope_id"`
	// 创建者用户ID
	CreatedBy string `json:"created_by"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 步骤执行表
type TStepRun struct {
	// 主键ID
	ID uint64 `json:"id"`
	// 步骤运行唯一标识
	StepRunID string `json:"step_run_id"`
	// 流水线ID
	PipelineID string `json:"pipeline_id"`
	// 流水线运行ID
	PipelineRunID sql.NullString `json:"pipeline_run_id"`
	// 任务ID
	JobID sql.NullString `json:"job_id"`
	// 步骤名称
	Name sql.NullString `json:"name"`
	// 执行 Agent ID
	AgentID sql.NullString `json:"agent_id"`
	// 状态: 1-等待 2-入队 3-运行中 4-成功 5-失败 6-已取消 7-超时 8-已跳过
	Status int8 `json:"status"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 步骤执行产物表
type TStepRunArtifact struct {
	// 主键ID
	ID uint64 `json:"id"`
	// 产物唯一标识
	ArtifactID string `json:"artifact_id"`
	// 步骤运行ID
	StepRunID string `json:"step_run_id"`
	// 任务运行ID
	JobRunID sql.NullString `json:"job_run_id"`
	// 流水线运行ID
	PipelineRunID sql.NullString `json:"pipeline_run_id"`
	// 产物名称
	Name string `json:"name"`
	// 产物路径
	Path string `json:"path"`
	// 目标路径
	Destination sql.NullString `json:"destination"`
	// 大小(字节)
	Size sql.NullInt64 `json:"size"`
	// 存储类型
	StorageType sql.NullString `json:"storage_type"`
	// 存储路径
	StoragePath sql.NullString `json:"storage_path"`
	// 是否过期
	Expire int8 `json:"expire"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 对象存储配置表
type TStorageConfig struct {
	// 主键ID
	ID int32 `json:"id"`
	// 存储唯一标识
	StorageID string `json:"storage_id"`
	// 存储名称
	Name string `json:"name"`
	// 存储类型(minio/s3/oss/gcs/cos)
	StorageType string `json:"storage_type"`
	// 存储配置(根据type不同,内容结构不同)
	Config datatypes.JSON `json:"config"`
	// 描述
	Description sql.NullString `json:"description"`
	// 0: not default, 1: default
	IsDefault int8 `json:"is_default"`
	// 0: disabled, 1: enabled
	IsEnabled int8 `json:"is_enabled"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 系统事件表
type TSystemEvent struct {
	// 主键ID
	ID int64 `json:"id"`
	// 事件唯一标识
	EventID string `json:"event_id"`
	// 事件类型: 1-任务创建, 2-任务开始, 3-任务完成, 4-任务失败, 5-Agent上线, 6-流水线开始, 7-流水线完成, 8-流水线失败
	EventType int8 `json:"event_type"`
	// 资源类型(job/pipeline/agent)
	ResourceType string `json:"resource_type"`
	// 资源ID
	ResourceID string `json:"resource_id"`
	// 资源名称
	ResourceName sql.NullString `json:"resource_name"`
	// 事件消息
	Message sql.NullString `json:"message"`
	// 事件元数据(JSON格式)
	Metadata json.RawMessage `json:"metadata"`
	// 关联用户ID
	UserID sql.NullString `json:"user_id"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
}

// 团队表
type TTeam struct {
	// 主键ID
	ID int32 `json:"id"`
	// 团队唯一标识
	TeamID string `json:"team_id"`
	// 所属组织ID
	OrgID string `json:"org_id"`
	// 团队名称(英文标识)
	Name string `json:"name"`
	// 团队显示名称
	DisplayName string `json:"display_name"`
	// 团队描述
	Description sql.NullString `json:"description"`
	// 团队头像
	Avatar sql.NullString `json:"avatar"`
	// 父团队ID(支持嵌套)
	ParentTeamID sql.NullString `json:"parent_team_id"`
	// 团队路径(用于层级关系,如:/parent/child)
	Path sql.NullString `json:"path"`
	// 团队层级(1为顶层)
	Level int32 `json:"level"`
	// 团队设置(JSON格式)
	Settings json.RawMessage `json:"settings"`
	// 可见性: 0-私有, 1-内部, 2-公开
	Visibility int8 `json:"visibility"`
	// 0: disabled, 1: enabled
	IsEnabled int8 `json:"is_enabled"`
	// 成员总数
	TotalMembers int32 `json:"total_members"`
	// 项目总数
	TotalProjects int32 `json:"total_projects"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 团队成员表
type TTeamMember struct {
	// 主键ID
	ID int32 `json:"id"`
	// 团队ID
	TeamID string `json:"team_id"`
	// 用户ID
	UserID string `json:"user_id"`
	// 团队角色(owner/maintainer/developer/reporter/guest)
	Role string `json:"role"`
	// 用户名(冗余)
	Username sql.NullString `json:"username"`
	// 邀请人用户ID
	InvitedBy sql.NullString `json:"invited_by"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 团队变量表
type TTeamVariable struct {
	// 主键ID
	ID int32 `json:"id"`
	// 变量唯一标识
	VariableID string `json:"variable_id"`
	// 团队ID
	TeamID string `json:"team_id"`
	// 变量键
	Key string `json:"key"`
	// 变量值(敏感信息加密存储)
	Value string `json:"value"`
	// 类型(env/secret/file)
	Type string `json:"type"`
	// 是否保护(仅在保护分支可用): 0-否, 1-是
	Protected int8 `json:"protected"`
	// 是否掩码(日志中隐藏): 0-否, 1-是
	Masked int8 `json:"masked"`
	// 描述
	Description sql.NullString `json:"description"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 用户表
type TUser struct {
	// 主键ID
	ID int32 `json:"id"`
	// 用户唯一标识
	UserID string `json:"user_id"`
	// 用户名
	Username string `json:"username"`
	// full name
	FullName sql.NullString `json:"full_name"`
	// 密码(加密)
	Password string `json:"password"`
	// 头像URL
	Avatar sql.NullString `json:"avatar"`
	// 邮箱
	Email sql.NullString `json:"email"`
	// 手机号
	Phone sql.NullString `json:"phone"`
	// 0: disabled, 1: enabled
	IsEnabled int8 `json:"is_enabled"`
	// 0: normal user, 1: super admin
	IsSuperAdmin int8 `json:"is_super_admin"`
	// 创建时间
	CreatedAt time.Time `json:"created_at"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at"`
}

// 用户扩展表
type TUserExt struct {
	// Auto-increment ID
	ID uint64 `json:"id"`
	// User ID (foreign key to t_user)
	UserID string `json:"user_id"`
	// User timezone (e.g., Asia/Shanghai, America/New_York)
	Timezone sql.NullString `json:"timezone"`
	// Last login timestamp
	LastLoginAt sql.NullTime `json:"last_login_at"`
	// Invitation status: pending, accepted, expired, revoked
	InvitationStatus sql.NullString `json:"invitation_status"`
	// Invited by user ID
	InvitedBy sql.NullString `json:"invited_by"`
	// Invitation timestamp
	InvitedAt sql.NullTime `json:"invited_at"`
	// Invitation accepted timestamp
	AcceptedAt sql.NullTime `json:"accepted_at"`
	// Created timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Updated timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
}

// 用户角色绑定表（支持多层级权限管理）
type TUserRoleBinding struct {
	// 主键ID
	ID int32 `json:"id"`
	// 绑定唯一标识
	BindingID string `json:"binding_id"`
	// 用户ID
	UserID string `json:"user_id"`
	// 角色ID
	RoleID string `json:"role_id"`
	// 授权人ID
	GrantedBy sql.NullString `json:"granted_by"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 更新时间
	UpdateTime time.Time `json:"update_time"`
}
