// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_template.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const notificationTemplateCreate = `-- name: NotificationTemplateCreate :exec

INSERT INTO t_notification_templates (template_id, name, type, channel, content, is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type NotificationTemplateCreateParams struct {
	TemplateID string       `json:"template_id"`
	Name       string       `json:"name"`
	Type       string       `json:"type"`
	Channel    string       `json:"channel"`
	Content    string       `json:"content"`
	IsActive   sql.NullBool `json:"is_active"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// NotificationTemplateCreate 创建通知模板
func (q *Queries) NotificationTemplateCreate(ctx context.Context, arg NotificationTemplateCreateParams) error {
	_, err := q.db.ExecContext(ctx, notificationTemplateCreate,
		arg.TemplateID,
		arg.Name,
		arg.Type,
		arg.Channel,
		arg.Content,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const notificationTemplateGetByNameAndType = `-- name: NotificationTemplateGetByNameAndType :one
SELECT id, template_id, name, type, channel, title, content, variables, format, metadata, description, is_active, created_at, updated_at FROM t_notification_templates WHERE name = ? AND type = ? AND is_active = 1 LIMIT 1
`

type NotificationTemplateGetByNameAndTypeParams struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// NotificationTemplateGetByNameAndType 按 name 与 type 获取（仅 is_active=1）
func (q *Queries) NotificationTemplateGetByNameAndType(ctx context.Context, arg NotificationTemplateGetByNameAndTypeParams) (TNotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, notificationTemplateGetByNameAndType, arg.Name, arg.Type)
	var i TNotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Type,
		&i.Channel,
		&i.Title,
		&i.Content,
		&i.Variables,
		&i.Format,
		&i.Metadata,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notificationTemplateGetByTemplateId = `-- name: NotificationTemplateGetByTemplateId :one
SELECT id, template_id, name, type, channel, title, content, variables, format, metadata, description, is_active, created_at, updated_at FROM t_notification_templates WHERE template_id = ? AND is_active = 1 LIMIT 1
`

type NotificationTemplateGetByTemplateIdParams struct {
	TemplateID string `json:"template_id"`
}

// NotificationTemplateGetByTemplateId 按 template_id 获取（仅 is_active=1）
func (q *Queries) NotificationTemplateGetByTemplateId(ctx context.Context, arg NotificationTemplateGetByTemplateIdParams) (TNotificationTemplate, error) {
	row := q.db.QueryRowContext(ctx, notificationTemplateGetByTemplateId, arg.TemplateID)
	var i TNotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Name,
		&i.Type,
		&i.Channel,
		&i.Title,
		&i.Content,
		&i.Variables,
		&i.Format,
		&i.Metadata,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notificationTemplateList = `-- name: NotificationTemplateList :many
SELECT id, template_id, name, type, channel, title, content, variables, format, metadata, description, is_active, created_at, updated_at FROM t_notification_templates
WHERE is_active = 1 AND (? = '' OR type = ?) AND (? = '' OR channel = ?) AND (? = '' OR name LIKE ?)
ORDER BY id LIMIT ? OFFSET ?
`

type NotificationTemplateListParams struct {
	Column1 interface{} `json:"column_1"`
	Type    string      `json:"type"`
	Column3 interface{} `json:"column_3"`
	Channel string      `json:"channel"`
	Column5 interface{} `json:"column_5"`
	Name    string      `json:"name"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// NotificationTemplateList 模板列表（可选 type, channel, name LIKE, limit, offset）
func (q *Queries) NotificationTemplateList(ctx context.Context, arg NotificationTemplateListParams) ([]TNotificationTemplate, error) {
	rows, err := q.db.QueryContext(ctx, notificationTemplateList,
		arg.Column1,
		arg.Type,
		arg.Column3,
		arg.Channel,
		arg.Column5,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TNotificationTemplate{}
	for rows.Next() {
		var i TNotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Name,
			&i.Type,
			&i.Channel,
			&i.Title,
			&i.Content,
			&i.Variables,
			&i.Format,
			&i.Metadata,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationTemplateSoftDeleteByTemplateId = `-- name: NotificationTemplateSoftDeleteByTemplateId :exec
UPDATE t_notification_templates SET is_active = 0, updated_at = ? WHERE template_id = ?
`

type NotificationTemplateSoftDeleteByTemplateIdParams struct {
	UpdatedAt  time.Time `json:"updated_at"`
	TemplateID string    `json:"template_id"`
}

// NotificationTemplateSoftDeleteByTemplateId 软删除模板（is_active=0）
func (q *Queries) NotificationTemplateSoftDeleteByTemplateId(ctx context.Context, arg NotificationTemplateSoftDeleteByTemplateIdParams) error {
	_, err := q.db.ExecContext(ctx, notificationTemplateSoftDeleteByTemplateId, arg.UpdatedAt, arg.TemplateID)
	return err
}

const notificationTemplateUpdateByTemplateId = `-- name: NotificationTemplateUpdateByTemplateId :exec
UPDATE t_notification_templates SET name = ?, type = ?, channel = ?, content = ?, is_active = ?, updated_at = ? WHERE template_id = ?
`

type NotificationTemplateUpdateByTemplateIdParams struct {
	Name       string       `json:"name"`
	Type       string       `json:"type"`
	Channel    string       `json:"channel"`
	Content    string       `json:"content"`
	IsActive   sql.NullBool `json:"is_active"`
	UpdatedAt  time.Time    `json:"updated_at"`
	TemplateID string       `json:"template_id"`
}

// NotificationTemplateUpdateByTemplateId 按 template_id 更新（不含 id, template_id, created_at）
func (q *Queries) NotificationTemplateUpdateByTemplateId(ctx context.Context, arg NotificationTemplateUpdateByTemplateIdParams) error {
	_, err := q.db.ExecContext(ctx, notificationTemplateUpdateByTemplateId,
		arg.Name,
		arg.Type,
		arg.Channel,
		arg.Content,
		arg.IsActive,
		arg.UpdatedAt,
		arg.TemplateID,
	)
	return err
}
