// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_channel.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const notificationChannelCreate = `-- name: NotificationChannelCreate :exec

INSERT INTO t_notification_channels (channel_id, name, type, config, is_active, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type NotificationChannelCreateParams struct {
	ChannelID string       `json:"channel_id"`
	Name      string       `json:"name"`
	Type      string       `json:"type"`
	Config    string       `json:"config"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// NotificationChannelCreate 创建通知渠道
func (q *Queries) NotificationChannelCreate(ctx context.Context, arg NotificationChannelCreateParams) error {
	_, err := q.db.ExecContext(ctx, notificationChannelCreate,
		arg.ChannelID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const notificationChannelGetByChannelId = `-- name: NotificationChannelGetByChannelId :one
SELECT id, channel_id, name, type, config, auth_config, description, is_active, created_at, updated_at FROM t_notification_channels WHERE channel_id = ? LIMIT 1
`

type NotificationChannelGetByChannelIdParams struct {
	ChannelID string `json:"channel_id"`
}

// NotificationChannelGetByChannelId 按 channel_id 获取
func (q *Queries) NotificationChannelGetByChannelId(ctx context.Context, arg NotificationChannelGetByChannelIdParams) (TNotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, notificationChannelGetByChannelId, arg.ChannelID)
	var i TNotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.AuthConfig,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notificationChannelGetByName = `-- name: NotificationChannelGetByName :one
SELECT id, channel_id, name, type, config, auth_config, description, is_active, created_at, updated_at FROM t_notification_channels WHERE name = ? LIMIT 1
`

type NotificationChannelGetByNameParams struct {
	Name string `json:"name"`
}

// NotificationChannelGetByName 按 name 获取
func (q *Queries) NotificationChannelGetByName(ctx context.Context, arg NotificationChannelGetByNameParams) (TNotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, notificationChannelGetByName, arg.Name)
	var i TNotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.AuthConfig,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notificationChannelList = `-- name: NotificationChannelList :many
SELECT id, channel_id, name, type, config, auth_config, description, is_active, created_at, updated_at FROM t_notification_channels
`

// NotificationChannelList 列出所有渠道
func (q *Queries) NotificationChannelList(ctx context.Context) ([]TNotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, notificationChannelList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TNotificationChannel{}
	for rows.Next() {
		var i TNotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.AuthConfig,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationChannelListActive = `-- name: NotificationChannelListActive :many
SELECT id, channel_id, name, type, config, auth_config, description, is_active, created_at, updated_at FROM t_notification_channels WHERE is_active = 1
`

// NotificationChannelListActive 列出启用渠道
func (q *Queries) NotificationChannelListActive(ctx context.Context) ([]TNotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, notificationChannelListActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TNotificationChannel{}
	for rows.Next() {
		var i TNotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.AuthConfig,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationChannelSoftDeleteByChannelId = `-- name: NotificationChannelSoftDeleteByChannelId :exec
UPDATE t_notification_channels SET is_active = 0, updated_at = ? WHERE channel_id = ?
`

type NotificationChannelSoftDeleteByChannelIdParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ChannelID string    `json:"channel_id"`
}

// NotificationChannelSoftDeleteByChannelId 软删除渠道（is_active=0）
func (q *Queries) NotificationChannelSoftDeleteByChannelId(ctx context.Context, arg NotificationChannelSoftDeleteByChannelIdParams) error {
	_, err := q.db.ExecContext(ctx, notificationChannelSoftDeleteByChannelId, arg.UpdatedAt, arg.ChannelID)
	return err
}

const notificationChannelUpdateByChannelId = `-- name: NotificationChannelUpdateByChannelId :exec
UPDATE t_notification_channels SET name = ?, type = ?, config = ?, is_active = ?, updated_at = ? WHERE channel_id = ?
`

type NotificationChannelUpdateByChannelIdParams struct {
	Name      string       `json:"name"`
	Type      string       `json:"type"`
	Config    string       `json:"config"`
	IsActive  sql.NullBool `json:"is_active"`
	UpdatedAt time.Time    `json:"updated_at"`
	ChannelID string       `json:"channel_id"`
}

// NotificationChannelUpdateByChannelId 按 channel_id 更新（不含 id, channel_id, created_at）
func (q *Queries) NotificationChannelUpdateByChannelId(ctx context.Context, arg NotificationChannelUpdateByChannelIdParams) error {
	_, err := q.db.ExecContext(ctx, notificationChannelUpdateByChannelId,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsActive,
		arg.UpdatedAt,
		arg.ChannelID,
	)
	return err
}
