// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline_run.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const pipelineRunCreate = `-- name: PipelineRunCreate :exec

INSERT INTO t_pipeline_run (run_id, pipeline_id, request_id, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type PipelineRunCreateParams struct {
	RunID      string         `json:"run_id"`
	PipelineID string         `json:"pipeline_id"`
	RequestID  sql.NullString `json:"request_id"`
	Status     int8           `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// PipelineRunCreate 创建流水线运行
func (q *Queries) PipelineRunCreate(ctx context.Context, arg PipelineRunCreateParams) error {
	_, err := q.db.ExecContext(ctx, pipelineRunCreate,
		arg.RunID,
		arg.PipelineID,
		arg.RequestID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const pipelineRunGetByPipelineIdAndRequestId = `-- name: PipelineRunGetByPipelineIdAndRequestId :one
SELECT id, run_id, pipeline_id, request_id, pipeline_name, branch, commit_sha, definition_commit_sha, definition_path, status, trigger_type, triggered_by, env, total_jobs, completed_jobs, failed_jobs, running_jobs, current_stage, total_stages, start_time, end_time, duration, created_at, updated_at FROM t_pipeline_run WHERE pipeline_id = ? AND request_id = ? LIMIT 1
`

type PipelineRunGetByPipelineIdAndRequestIdParams struct {
	PipelineID string         `json:"pipeline_id"`
	RequestID  sql.NullString `json:"request_id"`
}

// PipelineRunGetByPipelineIdAndRequestId 按 pipeline_id 与 request_id 获取运行
func (q *Queries) PipelineRunGetByPipelineIdAndRequestId(ctx context.Context, arg PipelineRunGetByPipelineIdAndRequestIdParams) (TPipelineRun, error) {
	row := q.db.QueryRowContext(ctx, pipelineRunGetByPipelineIdAndRequestId, arg.PipelineID, arg.RequestID)
	var i TPipelineRun
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.PipelineID,
		&i.RequestID,
		&i.PipelineName,
		&i.Branch,
		&i.CommitSha,
		&i.DefinitionCommitSha,
		&i.DefinitionPath,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.Env,
		&i.TotalJobs,
		&i.CompletedJobs,
		&i.FailedJobs,
		&i.RunningJobs,
		&i.CurrentStage,
		&i.TotalStages,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pipelineRunGetByRunId = `-- name: PipelineRunGetByRunId :one
SELECT id, run_id, pipeline_id, request_id, pipeline_name, branch, commit_sha, definition_commit_sha, definition_path, status, trigger_type, triggered_by, env, total_jobs, completed_jobs, failed_jobs, running_jobs, current_stage, total_stages, start_time, end_time, duration, created_at, updated_at FROM t_pipeline_run WHERE run_id = ? LIMIT 1
`

type PipelineRunGetByRunIdParams struct {
	RunID string `json:"run_id"`
}

// PipelineRunGetByRunId 按 run_id 获取流水线运行
func (q *Queries) PipelineRunGetByRunId(ctx context.Context, arg PipelineRunGetByRunIdParams) (TPipelineRun, error) {
	row := q.db.QueryRowContext(ctx, pipelineRunGetByRunId, arg.RunID)
	var i TPipelineRun
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.PipelineID,
		&i.RequestID,
		&i.PipelineName,
		&i.Branch,
		&i.CommitSha,
		&i.DefinitionCommitSha,
		&i.DefinitionPath,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.Env,
		&i.TotalJobs,
		&i.CompletedJobs,
		&i.FailedJobs,
		&i.RunningJobs,
		&i.CurrentStage,
		&i.TotalStages,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pipelineRunList = `-- name: PipelineRunList :many
SELECT id, run_id, pipeline_id, request_id, pipeline_name, branch, commit_sha, definition_commit_sha, definition_path, status, trigger_type, triggered_by, env, total_jobs, completed_jobs, failed_jobs, running_jobs, current_stage, total_stages, start_time, end_time, duration, created_at, updated_at FROM t_pipeline_run
WHERE (? = '' OR pipeline_id = ?) AND (? <= 0 OR status = ?)
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type PipelineRunListParams struct {
	Column1    interface{} `json:"column_1"`
	PipelineID string      `json:"pipeline_id"`
	Column3    interface{} `json:"column_3"`
	Status     int8        `json:"status"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

// PipelineRunList 流水线运行列表分页
func (q *Queries) PipelineRunList(ctx context.Context, arg PipelineRunListParams) ([]TPipelineRun, error) {
	rows, err := q.db.QueryContext(ctx, pipelineRunList,
		arg.Column1,
		arg.PipelineID,
		arg.Column3,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TPipelineRun{}
	for rows.Next() {
		var i TPipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.PipelineID,
			&i.RequestID,
			&i.PipelineName,
			&i.Branch,
			&i.CommitSha,
			&i.DefinitionCommitSha,
			&i.DefinitionPath,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.Env,
			&i.TotalJobs,
			&i.CompletedJobs,
			&i.FailedJobs,
			&i.RunningJobs,
			&i.CurrentStage,
			&i.TotalStages,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pipelineRunListCount = `-- name: PipelineRunListCount :one
SELECT COUNT(*) FROM t_pipeline_run WHERE (? = '' OR pipeline_id = ?) AND (? <= 0 OR status = ?)
`

type PipelineRunListCountParams struct {
	Column1    interface{} `json:"column_1"`
	PipelineID string      `json:"pipeline_id"`
	Column3    interface{} `json:"column_3"`
	Status     int8        `json:"status"`
}

// PipelineRunListCount 流水线运行列表总数（可选：pipeline_id, status）
func (q *Queries) PipelineRunListCount(ctx context.Context, arg PipelineRunListCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, pipelineRunListCount,
		arg.Column1,
		arg.PipelineID,
		arg.Column3,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pipelineRunUpdateByRunId = `-- name: PipelineRunUpdateByRunId :exec
UPDATE t_pipeline_run SET status = COALESCE(?, status), updated_at = ? WHERE run_id = ?
`

type PipelineRunUpdateByRunIdParams struct {
	Status    int8      `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	RunID     string    `json:"run_id"`
}

// PipelineRunUpdateByRunId 按 run_id 更新流水线运行（动态字段）
func (q *Queries) PipelineRunUpdateByRunId(ctx context.Context, arg PipelineRunUpdateByRunIdParams) error {
	_, err := q.db.ExecContext(ctx, pipelineRunUpdateByRunId, arg.Status, arg.UpdatedAt, arg.RunID)
	return err
}
