// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const pipelineCreate = `-- name: PipelineCreate :exec

INSERT INTO t_pipeline (pipeline_id, project_id, name, description, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type PipelineCreateParams struct {
	PipelineID  string         `json:"pipeline_id"`
	ProjectID   sql.NullString `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      int8           `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// PipelineCreate 创建流水线
func (q *Queries) PipelineCreate(ctx context.Context, arg PipelineCreateParams) error {
	_, err := q.db.ExecContext(ctx, pipelineCreate,
		arg.PipelineID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const pipelineGetByPipelineId = `-- name: PipelineGetByPipelineId :one
SELECT id, pipeline_id, project_id, name, description, repo_url, default_branch, pipeline_file_path, status, save_mode, pr_target_branch, metadata, last_sync_status, last_sync_message, last_synced_at, last_editor, last_commit_sha, last_save_request_id, total_runs, success_runs, failed_runs, created_by, is_enabled, created_at, updated_at FROM t_pipeline WHERE pipeline_id = ? LIMIT 1
`

type PipelineGetByPipelineIdParams struct {
	PipelineID string `json:"pipeline_id"`
}

// PipelineGetByPipelineId 按 pipeline_id 获取流水线
func (q *Queries) PipelineGetByPipelineId(ctx context.Context, arg PipelineGetByPipelineIdParams) (TPipeline, error) {
	row := q.db.QueryRowContext(ctx, pipelineGetByPipelineId, arg.PipelineID)
	var i TPipeline
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.PipelineFilePath,
		&i.Status,
		&i.SaveMode,
		&i.PrTargetBranch,
		&i.Metadata,
		&i.LastSyncStatus,
		&i.LastSyncMessage,
		&i.LastSyncedAt,
		&i.LastEditor,
		&i.LastCommitSha,
		&i.LastSaveRequestID,
		&i.TotalRuns,
		&i.SuccessRuns,
		&i.FailedRuns,
		&i.CreatedBy,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const pipelineList = `-- name: PipelineList :many
SELECT id, pipeline_id, project_id, name, description, repo_url, default_branch, pipeline_file_path, status, save_mode, pr_target_branch, metadata, last_sync_status, last_sync_message, last_synced_at, last_editor, last_commit_sha, last_save_request_id, total_runs, success_runs, failed_runs, created_by, is_enabled, created_at, updated_at FROM t_pipeline
WHERE (? = '' OR project_id = ?) AND (? = '' OR name LIKE ?) AND (? <= 0 OR status = ?)
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type PipelineListParams struct {
	Column1   interface{}    `json:"column_1"`
	ProjectID sql.NullString `json:"project_id"`
	Column3   interface{}    `json:"column_3"`
	Name      string         `json:"name"`
	Column5   interface{}    `json:"column_5"`
	Status    int8           `json:"status"`
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
}

// PipelineList 流水线列表分页
func (q *Queries) PipelineList(ctx context.Context, arg PipelineListParams) ([]TPipeline, error) {
	rows, err := q.db.QueryContext(ctx, pipelineList,
		arg.Column1,
		arg.ProjectID,
		arg.Column3,
		arg.Name,
		arg.Column5,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TPipeline{}
	for rows.Next() {
		var i TPipeline
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.RepoUrl,
			&i.DefaultBranch,
			&i.PipelineFilePath,
			&i.Status,
			&i.SaveMode,
			&i.PrTargetBranch,
			&i.Metadata,
			&i.LastSyncStatus,
			&i.LastSyncMessage,
			&i.LastSyncedAt,
			&i.LastEditor,
			&i.LastCommitSha,
			&i.LastSaveRequestID,
			&i.TotalRuns,
			&i.SuccessRuns,
			&i.FailedRuns,
			&i.CreatedBy,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pipelineListCount = `-- name: PipelineListCount :one
SELECT COUNT(*) FROM t_pipeline
WHERE (? = '' OR project_id = ?) AND (? = '' OR name LIKE ?) AND (? <= 0 OR status = ?)
`

type PipelineListCountParams struct {
	Column1   interface{}    `json:"column_1"`
	ProjectID sql.NullString `json:"project_id"`
	Column3   interface{}    `json:"column_3"`
	Name      string         `json:"name"`
	Column5   interface{}    `json:"column_5"`
	Status    int8           `json:"status"`
}

// PipelineListCount 流水线列表总数（可选：project_id, name LIKE, status）
func (q *Queries) PipelineListCount(ctx context.Context, arg PipelineListCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, pipelineListCount,
		arg.Column1,
		arg.ProjectID,
		arg.Column3,
		arg.Name,
		arg.Column5,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const pipelineUpdateByPipelineId = `-- name: PipelineUpdateByPipelineId :exec
UPDATE t_pipeline SET name = COALESCE(?, name), description = COALESCE(?, description), status = COALESCE(?, status), updated_at = ? WHERE pipeline_id = ?
`

type PipelineUpdateByPipelineIdParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      int8           `json:"status"`
	UpdatedAt   time.Time      `json:"updated_at"`
	PipelineID  string         `json:"pipeline_id"`
}

// PipelineUpdateByPipelineId 按 pipeline_id 更新流水线（动态字段）
func (q *Queries) PipelineUpdateByPipelineId(ctx context.Context, arg PipelineUpdateByPipelineIdParams) error {
	_, err := q.db.ExecContext(ctx, pipelineUpdateByPipelineId,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.UpdatedAt,
		arg.PipelineID,
	)
	return err
}
