// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const projectCreate = `-- name: ProjectCreate :exec

INSERT INTO t_project (project_id, org_id, name, description, language, status, visibility, tags, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type ProjectCreateParams struct {
	ProjectID   string         `json:"project_id"`
	OrgID       string         `json:"org_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Language    sql.NullString `json:"language"`
	Status      int8           `json:"status"`
	Visibility  int8           `json:"visibility"`
	Tags        sql.NullString `json:"tags"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ProjectCreate 创建项目
func (q *Queries) ProjectCreate(ctx context.Context, arg ProjectCreateParams) error {
	_, err := q.db.ExecContext(ctx, projectCreate,
		arg.ProjectID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Language,
		arg.Status,
		arg.Visibility,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const projectExistsByProjectId = `-- name: ProjectExistsByProjectId :one
SELECT 1 FROM t_project WHERE project_id = ? LIMIT 1
`

type ProjectExistsByProjectIdParams struct {
	ProjectID string `json:"project_id"`
}

// ProjectExistsByProjectId 判断项目是否存在
func (q *Queries) ProjectExistsByProjectId(ctx context.Context, arg ProjectExistsByProjectIdParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, projectExistsByProjectId, arg.ProjectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const projectGetByOrgIdAndName = `-- name: ProjectGetByOrgIdAndName :one
SELECT id, project_id, org_id, name, display_name, namespace, description, repo_url, repo_type, default_branch, auth_type, credential, trigger_mode, webhook_secret, cron_expr, build_config, env_vars, settings, tags, language, framework, status, visibility, access_level, created_by, is_enabled, icon, homepage, total_pipelines, total_builds, success_builds, failed_builds, created_at, updated_at FROM t_project WHERE org_id = ? AND name = ? LIMIT 1
`

type ProjectGetByOrgIdAndNameParams struct {
	OrgID string `json:"org_id"`
	Name  string `json:"name"`
}

// ProjectGetByOrgIdAndName 按 org_id 与 name 获取项目
func (q *Queries) ProjectGetByOrgIdAndName(ctx context.Context, arg ProjectGetByOrgIdAndNameParams) (TProject, error) {
	row := q.db.QueryRowContext(ctx, projectGetByOrgIdAndName, arg.OrgID, arg.Name)
	var i TProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Namespace,
		&i.Description,
		&i.RepoUrl,
		&i.RepoType,
		&i.DefaultBranch,
		&i.AuthType,
		&i.Credential,
		&i.TriggerMode,
		&i.WebhookSecret,
		&i.CronExpr,
		&i.BuildConfig,
		&i.EnvVars,
		&i.Settings,
		&i.Tags,
		&i.Language,
		&i.Framework,
		&i.Status,
		&i.Visibility,
		&i.AccessLevel,
		&i.CreatedBy,
		&i.IsEnabled,
		&i.Icon,
		&i.Homepage,
		&i.TotalPipelines,
		&i.TotalBuilds,
		&i.SuccessBuilds,
		&i.FailedBuilds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectGetByProjectId = `-- name: ProjectGetByProjectId :one
SELECT id, project_id, org_id, name, display_name, namespace, description, repo_url, repo_type, default_branch, auth_type, credential, trigger_mode, webhook_secret, cron_expr, build_config, env_vars, settings, tags, language, framework, status, visibility, access_level, created_by, is_enabled, icon, homepage, total_pipelines, total_builds, success_builds, failed_builds, created_at, updated_at FROM t_project WHERE project_id = ? LIMIT 1
`

type ProjectGetByProjectIdParams struct {
	ProjectID string `json:"project_id"`
}

// ProjectGetByProjectId 按 project_id 获取项目
func (q *Queries) ProjectGetByProjectId(ctx context.Context, arg ProjectGetByProjectIdParams) (TProject, error) {
	row := q.db.QueryRowContext(ctx, projectGetByProjectId, arg.ProjectID)
	var i TProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Namespace,
		&i.Description,
		&i.RepoUrl,
		&i.RepoType,
		&i.DefaultBranch,
		&i.AuthType,
		&i.Credential,
		&i.TriggerMode,
		&i.WebhookSecret,
		&i.CronExpr,
		&i.BuildConfig,
		&i.EnvVars,
		&i.Settings,
		&i.Tags,
		&i.Language,
		&i.Framework,
		&i.Status,
		&i.Visibility,
		&i.AccessLevel,
		&i.CreatedBy,
		&i.IsEnabled,
		&i.Icon,
		&i.Homepage,
		&i.TotalPipelines,
		&i.TotalBuilds,
		&i.SuccessBuilds,
		&i.FailedBuilds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectList = `-- name: ProjectList :many
SELECT id, project_id, org_id, name, display_name, namespace, description, repo_url, repo_type, default_branch, auth_type, credential, trigger_mode, webhook_secret, cron_expr, build_config, env_vars, settings, tags, language, framework, status, visibility, access_level, created_by, is_enabled, icon, homepage, total_pipelines, total_builds, success_builds, failed_builds, created_at, updated_at FROM t_project
WHERE (? = '' OR org_id = ?) AND (? = '' OR name LIKE ?) AND (? = '' OR language = ?) AND (? IS NULL OR status = ?) AND (? IS NULL OR visibility = ?)
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ProjectListParams struct {
	Column1    interface{}    `json:"column_1"`
	OrgID      string         `json:"org_id"`
	Column3    interface{}    `json:"column_3"`
	Name       string         `json:"name"`
	Column5    interface{}    `json:"column_5"`
	Language   sql.NullString `json:"language"`
	Column7    interface{}    `json:"column_7"`
	Status     int8           `json:"status"`
	Column9    interface{}    `json:"column_9"`
	Visibility int8           `json:"visibility"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
}

// ProjectList 项目列表分页
func (q *Queries) ProjectList(ctx context.Context, arg ProjectListParams) ([]TProject, error) {
	rows, err := q.db.QueryContext(ctx, projectList,
		arg.Column1,
		arg.OrgID,
		arg.Column3,
		arg.Name,
		arg.Column5,
		arg.Language,
		arg.Column7,
		arg.Status,
		arg.Column9,
		arg.Visibility,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TProject{}
	for rows.Next() {
		var i TProject
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Namespace,
			&i.Description,
			&i.RepoUrl,
			&i.RepoType,
			&i.DefaultBranch,
			&i.AuthType,
			&i.Credential,
			&i.TriggerMode,
			&i.WebhookSecret,
			&i.CronExpr,
			&i.BuildConfig,
			&i.EnvVars,
			&i.Settings,
			&i.Tags,
			&i.Language,
			&i.Framework,
			&i.Status,
			&i.Visibility,
			&i.AccessLevel,
			&i.CreatedBy,
			&i.IsEnabled,
			&i.Icon,
			&i.Homepage,
			&i.TotalPipelines,
			&i.TotalBuilds,
			&i.SuccessBuilds,
			&i.FailedBuilds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectListByOrg = `-- name: ProjectListByOrg :many
SELECT id, project_id, org_id, name, display_name, namespace, description, repo_url, repo_type, default_branch, auth_type, credential, trigger_mode, webhook_secret, cron_expr, build_config, env_vars, settings, tags, language, framework, status, visibility, access_level, created_by, is_enabled, icon, homepage, total_pipelines, total_builds, success_builds, failed_builds, created_at, updated_at FROM t_project WHERE org_id = ? AND (? IS NULL OR status = ?) ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ProjectListByOrgParams struct {
	OrgID   string      `json:"org_id"`
	Column2 interface{} `json:"column_2"`
	Status  int8        `json:"status"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// ProjectListByOrg 按组织分页列表
func (q *Queries) ProjectListByOrg(ctx context.Context, arg ProjectListByOrgParams) ([]TProject, error) {
	rows, err := q.db.QueryContext(ctx, projectListByOrg,
		arg.OrgID,
		arg.Column2,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TProject{}
	for rows.Next() {
		var i TProject
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Namespace,
			&i.Description,
			&i.RepoUrl,
			&i.RepoType,
			&i.DefaultBranch,
			&i.AuthType,
			&i.Credential,
			&i.TriggerMode,
			&i.WebhookSecret,
			&i.CronExpr,
			&i.BuildConfig,
			&i.EnvVars,
			&i.Settings,
			&i.Tags,
			&i.Language,
			&i.Framework,
			&i.Status,
			&i.Visibility,
			&i.AccessLevel,
			&i.CreatedBy,
			&i.IsEnabled,
			&i.Icon,
			&i.Homepage,
			&i.TotalPipelines,
			&i.TotalBuilds,
			&i.SuccessBuilds,
			&i.FailedBuilds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectListByOrgCount = `-- name: ProjectListByOrgCount :one
SELECT COUNT(*) FROM t_project WHERE org_id = ? AND (? IS NULL OR status = ?)
`

type ProjectListByOrgCountParams struct {
	OrgID   string      `json:"org_id"`
	Column2 interface{} `json:"column_2"`
	Status  int8        `json:"status"`
}

// ProjectListByOrgCount 按组织分页总数（可选 status）
func (q *Queries) ProjectListByOrgCount(ctx context.Context, arg ProjectListByOrgCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectListByOrgCount, arg.OrgID, arg.Column2, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const projectListByUser = `-- name: ProjectListByUser :many
SELECT p.id, p.project_id, p.org_id, p.name, p.display_name, p.namespace, p.description, p.repo_url, p.repo_type, p.default_branch, p.auth_type, p.credential, p.trigger_mode, p.webhook_secret, p.cron_expr, p.build_config, p.env_vars, p.settings, p.tags, p.language, p.framework, p.status, p.visibility, p.access_level, p.created_by, p.is_enabled, p.icon, p.homepage, p.total_pipelines, p.total_builds, p.success_builds, p.failed_builds, p.created_at, p.updated_at FROM t_project p
INNER JOIN t_project_member pm ON p.project_id = pm.project_id
WHERE pm.user_id = ? AND (? = '' OR p.org_id = ?) AND (? = '' OR pm.role = ?)
ORDER BY p.created_at DESC LIMIT ? OFFSET ?
`

type ProjectListByUserParams struct {
	UserID  string      `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	OrgID   string      `json:"org_id"`
	Column4 interface{} `json:"column_4"`
	Role    string      `json:"role"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// ProjectListByUser 按用户获取项目列表（JOIN t_project_member）
func (q *Queries) ProjectListByUser(ctx context.Context, arg ProjectListByUserParams) ([]TProject, error) {
	rows, err := q.db.QueryContext(ctx, projectListByUser,
		arg.UserID,
		arg.Column2,
		arg.OrgID,
		arg.Column4,
		arg.Role,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TProject{}
	for rows.Next() {
		var i TProject
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Namespace,
			&i.Description,
			&i.RepoUrl,
			&i.RepoType,
			&i.DefaultBranch,
			&i.AuthType,
			&i.Credential,
			&i.TriggerMode,
			&i.WebhookSecret,
			&i.CronExpr,
			&i.BuildConfig,
			&i.EnvVars,
			&i.Settings,
			&i.Tags,
			&i.Language,
			&i.Framework,
			&i.Status,
			&i.Visibility,
			&i.AccessLevel,
			&i.CreatedBy,
			&i.IsEnabled,
			&i.Icon,
			&i.Homepage,
			&i.TotalPipelines,
			&i.TotalBuilds,
			&i.SuccessBuilds,
			&i.FailedBuilds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectListByUserCount = `-- name: ProjectListByUserCount :one
SELECT COUNT(*) FROM t_project p
INNER JOIN t_project_member pm ON p.project_id = pm.project_id
WHERE pm.user_id = ? AND (? = '' OR p.org_id = ?) AND (? = '' OR pm.role = ?)
`

type ProjectListByUserCountParams struct {
	UserID  string      `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	OrgID   string      `json:"org_id"`
	Column4 interface{} `json:"column_4"`
	Role    string      `json:"role"`
}

// ProjectListByUserCount 按用户与可选 org_id/role_id 统计项目数
func (q *Queries) ProjectListByUserCount(ctx context.Context, arg ProjectListByUserCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectListByUserCount,
		arg.UserID,
		arg.Column2,
		arg.OrgID,
		arg.Column4,
		arg.Role,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const projectListCount = `-- name: ProjectListCount :one
SELECT COUNT(*) FROM t_project
WHERE (? = '' OR org_id = ?) AND (? = '' OR name LIKE ?) AND (? = '' OR language = ?)
  AND (? IS NULL OR status = ?) AND (? IS NULL OR visibility = ?)
`

type ProjectListCountParams struct {
	Column1    interface{}    `json:"column_1"`
	OrgID      string         `json:"org_id"`
	Column3    interface{}    `json:"column_3"`
	Name       string         `json:"name"`
	Column5    interface{}    `json:"column_5"`
	Language   sql.NullString `json:"language"`
	Column7    interface{}    `json:"column_7"`
	Status     int8           `json:"status"`
	Column9    interface{}    `json:"column_9"`
	Visibility int8           `json:"visibility"`
}

// ProjectListCount 项目列表总数（可选：org_id, name LIKE, language, status, visibility, tags）
func (q *Queries) ProjectListCount(ctx context.Context, arg ProjectListCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, projectListCount,
		arg.Column1,
		arg.OrgID,
		arg.Column3,
		arg.Name,
		arg.Column5,
		arg.Language,
		arg.Column7,
		arg.Status,
		arg.Column9,
		arg.Visibility,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const projectNameExists = `-- name: ProjectNameExists :one
SELECT COUNT(*) > 0 FROM t_project WHERE org_id = ? AND name = ? AND (? = '' OR project_id != ?)
`

type ProjectNameExistsParams struct {
	OrgID     string      `json:"org_id"`
	Name      string      `json:"name"`
	Column3   interface{} `json:"column_3"`
	ProjectID string      `json:"project_id"`
}

// ProjectNameExists 判断组织下项目名称是否存在（可排除指定 project_id）
func (q *Queries) ProjectNameExists(ctx context.Context, arg ProjectNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectNameExists,
		arg.OrgID,
		arg.Name,
		arg.Column3,
		arg.ProjectID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const projectSetStatus = `-- name: ProjectSetStatus :exec
UPDATE t_project SET status = ?, updated_at = ? WHERE project_id = ?
`

type ProjectSetStatusParams struct {
	Status    int8      `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ProjectID string    `json:"project_id"`
}

// ProjectSetStatus 设置项目状态（启用/禁用）
func (q *Queries) ProjectSetStatus(ctx context.Context, arg ProjectSetStatusParams) error {
	_, err := q.db.ExecContext(ctx, projectSetStatus, arg.Status, arg.UpdatedAt, arg.ProjectID)
	return err
}

const projectSoftDeleteByProjectId = `-- name: ProjectSoftDeleteByProjectId :exec
UPDATE t_project SET status = ?, updated_at = ? WHERE project_id = ?
`

type ProjectSoftDeleteByProjectIdParams struct {
	Status    int8      `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ProjectID string    `json:"project_id"`
}

// ProjectSoftDeleteByProjectId 软删除项目（置为禁用状态）
func (q *Queries) ProjectSoftDeleteByProjectId(ctx context.Context, arg ProjectSoftDeleteByProjectIdParams) error {
	_, err := q.db.ExecContext(ctx, projectSoftDeleteByProjectId, arg.Status, arg.UpdatedAt, arg.ProjectID)
	return err
}

const projectUpdateByProjectId = `-- name: ProjectUpdateByProjectId :exec
UPDATE t_project SET name = COALESCE(?, name), description = COALESCE(?, description), status = COALESCE(?, status), updated_at = ? WHERE project_id = ?
`

type ProjectUpdateByProjectIdParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      int8           `json:"status"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ProjectID   string         `json:"project_id"`
}

// ProjectUpdateByProjectId 按 project_id 更新项目（动态字段）
func (q *Queries) ProjectUpdateByProjectId(ctx context.Context, arg ProjectUpdateByProjectIdParams) error {
	_, err := q.db.ExecContext(ctx, projectUpdateByProjectId,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.UpdatedAt,
		arg.ProjectID,
	)
	return err
}

const projectUpdateStatistics = `-- name: ProjectUpdateStatistics :exec
UPDATE t_project SET total_pipelines = COALESCE(?, total_pipelines), total_builds = COALESCE(?, total_builds), success_builds = COALESCE(?, success_builds), updated_at = ? WHERE project_id = ?
`

type ProjectUpdateStatisticsParams struct {
	TotalPipelines int32     `json:"total_pipelines"`
	TotalBuilds    int32     `json:"total_builds"`
	SuccessBuilds  int32     `json:"success_builds"`
	UpdatedAt      time.Time `json:"updated_at"`
	ProjectID      string    `json:"project_id"`
}

// ProjectUpdateStatistics 更新项目统计字段
func (q *Queries) ProjectUpdateStatistics(ctx context.Context, arg ProjectUpdateStatisticsParams) error {
	_, err := q.db.ExecContext(ctx, projectUpdateStatistics,
		arg.TotalPipelines,
		arg.TotalBuilds,
		arg.SuccessBuilds,
		arg.UpdatedAt,
		arg.ProjectID,
	)
	return err
}
