// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_member.sql

package dal

import (
	"context"
	"time"
)

const projectMemberCreate = `-- name: ProjectMemberCreate :exec
INSERT INTO t_project_member (project_id, user_id, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type ProjectMemberCreateParams struct {
	ProjectID string    `json:"project_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ProjectMemberCreate 添加项目成员
func (q *Queries) ProjectMemberCreate(ctx context.Context, arg ProjectMemberCreateParams) error {
	_, err := q.db.ExecContext(ctx, projectMemberCreate,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const projectMemberGet = `-- name: ProjectMemberGet :one

SELECT id, project_id, user_id, role, created_at, updated_at FROM t_project_member WHERE project_id = ? AND user_id = ? LIMIT 1
`

type ProjectMemberGetParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

type ProjectMemberGetRow struct {
	ID        int32     `json:"id"`
	ProjectID string    `json:"project_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ProjectMemberGet 按 project_id 与 user_id 获取项目成员
func (q *Queries) ProjectMemberGet(ctx context.Context, arg ProjectMemberGetParams) (ProjectMemberGetRow, error) {
	row := q.db.QueryRowContext(ctx, projectMemberGet, arg.ProjectID, arg.UserID)
	var i ProjectMemberGetRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectMemberListByProjectId = `-- name: ProjectMemberListByProjectId :many
SELECT id, project_id, user_id, role, created_at, updated_at FROM t_project_member WHERE project_id = ?
`

type ProjectMemberListByProjectIdParams struct {
	ProjectID string `json:"project_id"`
}

type ProjectMemberListByProjectIdRow struct {
	ID        int32     `json:"id"`
	ProjectID string    `json:"project_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ProjectMemberListByProjectId 按 project_id 列出成员
func (q *Queries) ProjectMemberListByProjectId(ctx context.Context, arg ProjectMemberListByProjectIdParams) ([]ProjectMemberListByProjectIdRow, error) {
	rows, err := q.db.QueryContext(ctx, projectMemberListByProjectId, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMemberListByProjectIdRow{}
	for rows.Next() {
		var i ProjectMemberListByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMemberListByUserId = `-- name: ProjectMemberListByUserId :many
SELECT id, project_id, user_id, role, created_at, updated_at FROM t_project_member WHERE user_id = ?
`

type ProjectMemberListByUserIdParams struct {
	UserID string `json:"user_id"`
}

type ProjectMemberListByUserIdRow struct {
	ID        int32     `json:"id"`
	ProjectID string    `json:"project_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ProjectMemberListByUserId 按 user_id 列出其项目成员关系
func (q *Queries) ProjectMemberListByUserId(ctx context.Context, arg ProjectMemberListByUserIdParams) ([]ProjectMemberListByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, projectMemberListByUserId, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMemberListByUserIdRow{}
	for rows.Next() {
		var i ProjectMemberListByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMemberRemove = `-- name: ProjectMemberRemove :exec
DELETE FROM t_project_member WHERE project_id = ? AND user_id = ?
`

type ProjectMemberRemoveParams struct {
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

// ProjectMemberRemove 移除项目成员
func (q *Queries) ProjectMemberRemove(ctx context.Context, arg ProjectMemberRemoveParams) error {
	_, err := q.db.ExecContext(ctx, projectMemberRemove, arg.ProjectID, arg.UserID)
	return err
}

const projectMemberUpdateRole = `-- name: ProjectMemberUpdateRole :exec
UPDATE t_project_member SET role = ?, updated_at = ? WHERE project_id = ? AND user_id = ?
`

type ProjectMemberUpdateRoleParams struct {
	Role      string    `json:"role"`
	UpdatedAt time.Time `json:"updated_at"`
	ProjectID string    `json:"project_id"`
	UserID    string    `json:"user_id"`
}

// ProjectMemberUpdateRole 更新项目成员角色
func (q *Queries) ProjectMemberUpdateRole(ctx context.Context, arg ProjectMemberUpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, projectMemberUpdateRole,
		arg.Role,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.UserID,
	)
	return err
}
