// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_team_access.sql

package dal

import (
	"context"
	"time"
)

const projectTeamAccessCreate = `-- name: ProjectTeamAccessCreate :exec
INSERT INTO t_project_team_access (project_id, team_id, access_level, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type ProjectTeamAccessCreateParams struct {
	ProjectID   string    `json:"project_id"`
	TeamID      string    `json:"team_id"`
	AccessLevel string    `json:"access_level"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ProjectTeamAccessCreate 创建项目-团队访问
func (q *Queries) ProjectTeamAccessCreate(ctx context.Context, arg ProjectTeamAccessCreateParams) error {
	_, err := q.db.ExecContext(ctx, projectTeamAccessCreate,
		arg.ProjectID,
		arg.TeamID,
		arg.AccessLevel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const projectTeamAccessGet = `-- name: ProjectTeamAccessGet :one

SELECT id, project_id, team_id, access_level, created_at, updated_at FROM t_project_team_access WHERE project_id = ? AND team_id = ? LIMIT 1
`

type ProjectTeamAccessGetParams struct {
	ProjectID string `json:"project_id"`
	TeamID    string `json:"team_id"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ProjectTeamAccessGet 按 project_id 与 team_id 获取访问配置
func (q *Queries) ProjectTeamAccessGet(ctx context.Context, arg ProjectTeamAccessGetParams) (TProjectTeamAccess, error) {
	row := q.db.QueryRowContext(ctx, projectTeamAccessGet, arg.ProjectID, arg.TeamID)
	var i TProjectTeamAccess
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TeamID,
		&i.AccessLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectTeamAccessListByProjectId = `-- name: ProjectTeamAccessListByProjectId :many
SELECT id, project_id, team_id, access_level, created_at, updated_at FROM t_project_team_access WHERE project_id = ?
`

type ProjectTeamAccessListByProjectIdParams struct {
	ProjectID string `json:"project_id"`
}

// ProjectTeamAccessListByProjectId 按 project_id 列出
func (q *Queries) ProjectTeamAccessListByProjectId(ctx context.Context, arg ProjectTeamAccessListByProjectIdParams) ([]TProjectTeamAccess, error) {
	rows, err := q.db.QueryContext(ctx, projectTeamAccessListByProjectId, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TProjectTeamAccess{}
	for rows.Next() {
		var i TProjectTeamAccess
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TeamID,
			&i.AccessLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectTeamAccessListByTeamId = `-- name: ProjectTeamAccessListByTeamId :many
SELECT id, project_id, team_id, access_level, created_at, updated_at FROM t_project_team_access WHERE team_id = ?
`

type ProjectTeamAccessListByTeamIdParams struct {
	TeamID string `json:"team_id"`
}

// ProjectTeamAccessListByTeamId 按 team_id 列出
func (q *Queries) ProjectTeamAccessListByTeamId(ctx context.Context, arg ProjectTeamAccessListByTeamIdParams) ([]TProjectTeamAccess, error) {
	rows, err := q.db.QueryContext(ctx, projectTeamAccessListByTeamId, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TProjectTeamAccess{}
	for rows.Next() {
		var i TProjectTeamAccess
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TeamID,
			&i.AccessLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
