// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dal

import (
	"context"
)

type Querier interface {
	// AgentCount Agent 总数
	AgentCount(ctx context.Context) (int64, error)
	// AgentCountByStatusOffline 离线 Agent 数量（status=2）
	AgentCountByStatusOffline(ctx context.Context) (int64, error)
	// AgentCountByStatusOnline 在线 Agent 数量（status=1）
	AgentCountByStatusOnline(ctx context.Context) (int64, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// AgentCreate 创建 Agent
	AgentCreate(ctx context.Context, arg AgentCreateParams) error
	// AgentDeleteByAgentId 按 agent_id 删除 Agent
	AgentDeleteByAgentId(ctx context.Context, arg AgentDeleteByAgentIdParams) error
	// AgentGetByAgentId 按 agent_id 获取 Agent
	AgentGetByAgentId(ctx context.Context, arg AgentGetByAgentIdParams) (TAgent, error)
	// AgentList Agent 列表分页
	AgentList(ctx context.Context, arg AgentListParams) ([]AgentListRow, error)
	// AgentPatchByAgentId 按 agent_id 部分更新（如 status, last_heartbeat）
	AgentPatchByAgentId(ctx context.Context, arg AgentPatchByAgentIdParams) error
	// AgentUpdateByAgentId 按 agent_id 全量更新 Agent
	AgentUpdateByAgentId(ctx context.Context, arg AgentUpdateByAgentIdParams) error
	// SettingGet 按 workspace 与 name 获取配置
	SettingGet(ctx context.Context, arg SettingGetParams) (TSetting, error)
	// SettingUpsert 创建或更新配置 (ON CONFLICT DO UPDATE)
	SettingUpsert(ctx context.Context, arg SettingUpsertParams) error
	// SettingList 按 workspace 列出所有配置
	SettingList(ctx context.Context, workspace string) ([]TSetting, error)
	// SettingDelete 按 workspace 与 name 删除配置
	SettingDelete(ctx context.Context, arg SettingDeleteParams) error
	// IdentityCreate 创建身份提供商
	IdentityCreate(ctx context.Context, arg IdentityCreateParams) error
	// IdentityDeleteByName 按 name 删除
	IdentityDeleteByName(ctx context.Context, arg IdentityDeleteByNameParams) error
	// IdentityExistsByName 判断 name 是否存在
	IdentityExistsByName(ctx context.Context, arg IdentityExistsByNameParams) (bool, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// IdentityGetByName 按 name 获取身份提供商
	IdentityGetByName(ctx context.Context, arg IdentityGetByNameParams) (IdentityGetByNameRow, error)
	// IdentityGetIsEnabledByName 获取当前 is_enabled 用于切换
	IdentityGetIsEnabledByName(ctx context.Context, arg IdentityGetIsEnabledByNameParams) (int8, error)
	// IdentityGetProviderTypes 获取所有不重复的 provider_type
	IdentityGetProviderTypes(ctx context.Context) ([]string, error)
	// IdentityListAll 列出所有身份提供商
	IdentityListAll(ctx context.Context) ([]IdentityListAllRow, error)
	// IdentityListByProviderType 按 provider_type 列出
	IdentityListByProviderType(ctx context.Context, arg IdentityListByProviderTypeParams) ([]IdentityListByProviderTypeRow, error)
	// IdentityToggleByName 切换 is_enabled（0/1）
	IdentityToggleByName(ctx context.Context, arg IdentityToggleByNameParams) error
	// IdentityUpdateByName 按 name 更新（不含 name, provider_id, provider_type, created_at）
	IdentityUpdateByName(ctx context.Context, arg IdentityUpdateByNameParams) error
	// MenuBatchGetByMenuIds 按 menu_id 列表批量获取（仅启用）
	MenuBatchGetByMenuIds(ctx context.Context, arg MenuBatchGetByMenuIdsParams) ([]TMenu, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// MenuGetByMenuId 按 menu_id 获取菜单（仅启用）
	MenuGetByMenuId(ctx context.Context, arg MenuGetByMenuIdParams) (TMenu, error)
	// MenuList 列出所有启用菜单
	MenuList(ctx context.Context) ([]TMenu, error)
	// MenuListByParentId 按 parent_id 列出子菜单（仅启用）
	MenuListByParentId(ctx context.Context, arg MenuListByParentIdParams) ([]TMenu, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// NotificationChannelCreate 创建通知渠道
	NotificationChannelCreate(ctx context.Context, arg NotificationChannelCreateParams) error
	// NotificationChannelGetByChannelId 按 channel_id 获取
	NotificationChannelGetByChannelId(ctx context.Context, arg NotificationChannelGetByChannelIdParams) (TNotificationChannel, error)
	// NotificationChannelGetByName 按 name 获取
	NotificationChannelGetByName(ctx context.Context, arg NotificationChannelGetByNameParams) (TNotificationChannel, error)
	// NotificationChannelList 列出所有渠道
	NotificationChannelList(ctx context.Context) ([]TNotificationChannel, error)
	// NotificationChannelListActive 列出启用渠道
	NotificationChannelListActive(ctx context.Context) ([]TNotificationChannel, error)
	// NotificationChannelSoftDeleteByChannelId 软删除渠道（is_active=0）
	NotificationChannelSoftDeleteByChannelId(ctx context.Context, arg NotificationChannelSoftDeleteByChannelIdParams) error
	// NotificationChannelUpdateByChannelId 按 channel_id 更新（不含 id, channel_id, created_at）
	NotificationChannelUpdateByChannelId(ctx context.Context, arg NotificationChannelUpdateByChannelIdParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// NotificationTemplateCreate 创建通知模板
	NotificationTemplateCreate(ctx context.Context, arg NotificationTemplateCreateParams) error
	// NotificationTemplateGetByNameAndType 按 name 与 type 获取（仅 is_active=1）
	NotificationTemplateGetByNameAndType(ctx context.Context, arg NotificationTemplateGetByNameAndTypeParams) (TNotificationTemplate, error)
	// NotificationTemplateGetByTemplateId 按 template_id 获取（仅 is_active=1）
	NotificationTemplateGetByTemplateId(ctx context.Context, arg NotificationTemplateGetByTemplateIdParams) (TNotificationTemplate, error)
	// NotificationTemplateList 模板列表（可选 type, channel, name LIKE, limit, offset）
	NotificationTemplateList(ctx context.Context, arg NotificationTemplateListParams) ([]TNotificationTemplate, error)
	// NotificationTemplateSoftDeleteByTemplateId 软删除模板（is_active=0）
	NotificationTemplateSoftDeleteByTemplateId(ctx context.Context, arg NotificationTemplateSoftDeleteByTemplateIdParams) error
	// NotificationTemplateUpdateByTemplateId 按 template_id 更新（不含 id, template_id, created_at）
	NotificationTemplateUpdateByTemplateId(ctx context.Context, arg NotificationTemplateUpdateByTemplateIdParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// PipelineCreate 创建流水线
	PipelineCreate(ctx context.Context, arg PipelineCreateParams) error
	// PipelineGetByPipelineId 按 pipeline_id 获取流水线
	PipelineGetByPipelineId(ctx context.Context, arg PipelineGetByPipelineIdParams) (TPipeline, error)
	// PipelineList 流水线列表分页
	PipelineList(ctx context.Context, arg PipelineListParams) ([]TPipeline, error)
	// PipelineListCount 流水线列表总数（可选：project_id, name LIKE, status）
	PipelineListCount(ctx context.Context, arg PipelineListCountParams) (int64, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// PipelineRunCreate 创建流水线运行
	PipelineRunCreate(ctx context.Context, arg PipelineRunCreateParams) error
	// PipelineRunGetByPipelineIdAndRequestId 按 pipeline_id 与 request_id 获取运行
	PipelineRunGetByPipelineIdAndRequestId(ctx context.Context, arg PipelineRunGetByPipelineIdAndRequestIdParams) (TPipelineRun, error)
	// PipelineRunGetByRunId 按 run_id 获取流水线运行
	PipelineRunGetByRunId(ctx context.Context, arg PipelineRunGetByRunIdParams) (TPipelineRun, error)
	// PipelineRunList 流水线运行列表分页
	PipelineRunList(ctx context.Context, arg PipelineRunListParams) ([]TPipelineRun, error)
	// PipelineRunListCount 流水线运行列表总数（可选：pipeline_id, status）
	PipelineRunListCount(ctx context.Context, arg PipelineRunListCountParams) (int64, error)
	// PipelineRunUpdateByRunId 按 run_id 更新流水线运行（动态字段）
	PipelineRunUpdateByRunId(ctx context.Context, arg PipelineRunUpdateByRunIdParams) error
	// PipelineUpdateByPipelineId 按 pipeline_id 更新流水线（动态字段）
	PipelineUpdateByPipelineId(ctx context.Context, arg PipelineUpdateByPipelineIdParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// ProjectCreate 创建项目
	ProjectCreate(ctx context.Context, arg ProjectCreateParams) error
	// ProjectExistsByProjectId 判断项目是否存在
	ProjectExistsByProjectId(ctx context.Context, arg ProjectExistsByProjectIdParams) (int32, error)
	// ProjectGetByOrgIdAndName 按 org_id 与 name 获取项目
	ProjectGetByOrgIdAndName(ctx context.Context, arg ProjectGetByOrgIdAndNameParams) (TProject, error)
	// ProjectGetByProjectId 按 project_id 获取项目
	ProjectGetByProjectId(ctx context.Context, arg ProjectGetByProjectIdParams) (TProject, error)
	// ProjectList 项目列表分页
	ProjectList(ctx context.Context, arg ProjectListParams) ([]TProject, error)
	// ProjectListByOrg 按组织分页列表
	ProjectListByOrg(ctx context.Context, arg ProjectListByOrgParams) ([]TProject, error)
	// ProjectListByOrgCount 按组织分页总数（可选 status）
	ProjectListByOrgCount(ctx context.Context, arg ProjectListByOrgCountParams) (int64, error)
	// ProjectListByUser 按用户获取项目列表（JOIN t_project_member）
	ProjectListByUser(ctx context.Context, arg ProjectListByUserParams) ([]TProject, error)
	// ProjectListByUserCount 按用户与可选 org_id/role_id 统计项目数
	ProjectListByUserCount(ctx context.Context, arg ProjectListByUserCountParams) (int64, error)
	// ProjectListCount 项目列表总数（可选：org_id, name LIKE, language, status, visibility, tags）
	ProjectListCount(ctx context.Context, arg ProjectListCountParams) (int64, error)
	// ProjectMemberCreate 添加项目成员
	ProjectMemberCreate(ctx context.Context, arg ProjectMemberCreateParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// ProjectMemberGet 按 project_id 与 user_id 获取项目成员
	ProjectMemberGet(ctx context.Context, arg ProjectMemberGetParams) (ProjectMemberGetRow, error)
	// ProjectMemberListByProjectId 按 project_id 列出成员
	ProjectMemberListByProjectId(ctx context.Context, arg ProjectMemberListByProjectIdParams) ([]ProjectMemberListByProjectIdRow, error)
	// ProjectMemberListByUserId 按 user_id 列出其项目成员关系
	ProjectMemberListByUserId(ctx context.Context, arg ProjectMemberListByUserIdParams) ([]ProjectMemberListByUserIdRow, error)
	// ProjectMemberRemove 移除项目成员
	ProjectMemberRemove(ctx context.Context, arg ProjectMemberRemoveParams) error
	// ProjectMemberUpdateRole 更新项目成员角色
	ProjectMemberUpdateRole(ctx context.Context, arg ProjectMemberUpdateRoleParams) error
	// ProjectNameExists 判断组织下项目名称是否存在（可排除指定 project_id）
	ProjectNameExists(ctx context.Context, arg ProjectNameExistsParams) (bool, error)
	// ProjectSetStatus 设置项目状态（启用/禁用）
	ProjectSetStatus(ctx context.Context, arg ProjectSetStatusParams) error
	// ProjectSoftDeleteByProjectId 软删除项目（置为禁用状态）
	ProjectSoftDeleteByProjectId(ctx context.Context, arg ProjectSoftDeleteByProjectIdParams) error
	// ProjectTeamAccessCreate 创建项目-团队访问
	ProjectTeamAccessCreate(ctx context.Context, arg ProjectTeamAccessCreateParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// ProjectTeamAccessGet 按 project_id 与 team_id 获取访问配置
	ProjectTeamAccessGet(ctx context.Context, arg ProjectTeamAccessGetParams) (TProjectTeamAccess, error)
	// ProjectTeamAccessListByProjectId 按 project_id 列出
	ProjectTeamAccessListByProjectId(ctx context.Context, arg ProjectTeamAccessListByProjectIdParams) ([]TProjectTeamAccess, error)
	// ProjectTeamAccessListByTeamId 按 team_id 列出
	ProjectTeamAccessListByTeamId(ctx context.Context, arg ProjectTeamAccessListByTeamIdParams) ([]TProjectTeamAccess, error)
	// ProjectUpdateByProjectId 按 project_id 更新项目（动态字段）
	ProjectUpdateByProjectId(ctx context.Context, arg ProjectUpdateByProjectIdParams) error
	// ProjectUpdateStatistics 更新项目统计字段
	ProjectUpdateStatistics(ctx context.Context, arg ProjectUpdateStatisticsParams) error
	// RoleBatchGetByRoleIds 按 role_id 列表批量获取
	RoleBatchGetByRoleIds(ctx context.Context, arg RoleBatchGetByRoleIdsParams) ([]TRole, error)
	// RoleCount 角色总数
	RoleCount(ctx context.Context) (int64, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// RoleCreate 创建角色
	RoleCreate(ctx context.Context, arg RoleCreateParams) error
	// RoleDeleteByRoleId 按 role_id 硬删除角色
	RoleDeleteByRoleId(ctx context.Context, arg RoleDeleteByRoleIdParams) error
	// RoleGetByRoleId 按 role_id 获取角色
	RoleGetByRoleId(ctx context.Context, arg RoleGetByRoleIdParams) (TRole, error)
	// RoleList 角色列表分页
	RoleList(ctx context.Context, arg RoleListParams) ([]TRole, error)
	// RoleMenuBindingCreate 创建角色菜单绑定
	RoleMenuBindingCreate(ctx context.Context, arg RoleMenuBindingCreateParams) error
	// RoleMenuBindingDeleteByRoleMenuId 按 role_menu_id 删除
	RoleMenuBindingDeleteByRoleMenuId(ctx context.Context, arg RoleMenuBindingDeleteByRoleMenuIdParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// RoleMenuBindingListByRoleId 按 role_id 列出角色菜单绑定（is_accessible=1）
	RoleMenuBindingListByRoleId(ctx context.Context, arg RoleMenuBindingListByRoleIdParams) ([]TRoleMenuBinding, error)
	// RoleMenuBindingListByRoleIdAndResourceId 按 role_id 与 resource_id 列出（resource_id 空则 IS NULL OR = ''）
	RoleMenuBindingListByRoleIdAndResourceId(ctx context.Context, arg RoleMenuBindingListByRoleIdAndResourceIdParams) ([]TRoleMenuBinding, error)
	// RoleMenuBindingListByRoleIdsAndResourceId 按 role_id 列表与 resource_id 列出
	RoleMenuBindingListByRoleIdsAndResourceId(ctx context.Context, arg RoleMenuBindingListByRoleIdsAndResourceIdParams) ([]TRoleMenuBinding, error)
	// RoleSoftDeleteByRoleId 软删除角色（is_enabled=0）
	RoleSoftDeleteByRoleId(ctx context.Context, arg RoleSoftDeleteByRoleIdParams) error
	// RoleUpdateByRoleId 按 role_id 更新（动态字段）
	RoleUpdateByRoleId(ctx context.Context, arg RoleUpdateByRoleIdParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// SecretCreate 创建密钥
	SecretCreate(ctx context.Context, arg SecretCreateParams) error
	// SecretDeleteBySecretId 按 secret_id 删除密钥
	SecretDeleteBySecretId(ctx context.Context, arg SecretDeleteBySecretIdParams) error
	// SecretGetBySecretId 按 secret_id 获取密钥（含 secret_value）
	SecretGetBySecretId(ctx context.Context, arg SecretGetBySecretIdParams) (TSecret, error)
	// SecretGetValueBySecretId 仅获取密钥值
	SecretGetValueBySecretId(ctx context.Context, arg SecretGetValueBySecretIdParams) (string, error)
	// SecretList 密钥列表分页（不含 secret_value）
	SecretList(ctx context.Context, arg SecretListParams) ([]SecretListRow, error)
	// SecretListByScope 按 scope 与 scope_id 列出密钥（不含 value）
	SecretListByScope(ctx context.Context, arg SecretListByScopeParams) ([]SecretListByScopeRow, error)
	// SecretListCount 密钥列表总数（可选：secret_type, scope, scope_id, created_by）
	SecretListCount(ctx context.Context, arg SecretListCountParams) (int64, error)
	// SecretUpdateBySecretId 按 secret_id 更新密钥（不含 id, secret_id, created_at）
	SecretUpdateBySecretId(ctx context.Context, arg SecretUpdateBySecretIdParams) error
	// StepRunArtifactListByStepRunId 按 step_run_id 获取产物列表
	StepRunArtifactListByStepRunId(ctx context.Context, arg StepRunArtifactListByStepRunIdParams) ([]TStepRunArtifact, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// StepRunCreate 创建步骤运行
	StepRunCreate(ctx context.Context, arg StepRunCreateParams) error
	// StepRunDeleteByStepRunId 按 step_run_id 删除步骤运行
	StepRunDeleteByStepRunId(ctx context.Context, arg StepRunDeleteByStepRunIdParams) error
	// StepRunGetByPipelineJobStep 按 pipeline_id + job_id + step_run_id 获取
	StepRunGetByPipelineJobStep(ctx context.Context, arg StepRunGetByPipelineJobStepParams) (TStepRun, error)
	// StepRunGetByStepRunId 按 step_run_id 获取步骤运行
	StepRunGetByStepRunId(ctx context.Context, arg StepRunGetByStepRunIdParams) (TStepRun, error)
	// StepRunList 步骤运行列表分页
	StepRunList(ctx context.Context, arg StepRunListParams) ([]TStepRun, error)
	// StepRunListCount 步骤运行列表总数（动态条件见应用层）
	StepRunListCount(ctx context.Context, arg StepRunListCountParams) (int64, error)
	// StepRunPatchByStepRunId 按 step_run_id 部分更新（含 updated_at）
	StepRunPatchByStepRunId(ctx context.Context, arg StepRunPatchByStepRunIdParams) error
	// StorageConfigClearDefault 清除当前默认（将所有 is_default=1 置为 0）
	StorageConfigClearDefault(ctx context.Context, arg StorageConfigClearDefaultParams) error
	// StorageConfigCreate 创建存储配置
	StorageConfigCreate(ctx context.Context, arg StorageConfigCreateParams) error
	// StorageConfigDeleteByStorageId 按 storage_id 删除
	StorageConfigDeleteByStorageId(ctx context.Context, arg StorageConfigDeleteByStorageIdParams) error
	// StorageConfigGetByStorageId 按 storage_id 获取（仅启用）
	StorageConfigGetByStorageId(ctx context.Context, arg StorageConfigGetByStorageIdParams) (TStorageConfig, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// StorageConfigGetDefault 获取默认存储配置（is_default=1 且 is_enabled=1）
	StorageConfigGetDefault(ctx context.Context) (TStorageConfig, error)
	// StorageConfigListByType 按 storage_type 列出启用配置
	StorageConfigListByType(ctx context.Context, arg StorageConfigListByTypeParams) ([]StorageConfigListByTypeRow, error)
	// StorageConfigListEnabled 列出所有启用配置
	StorageConfigListEnabled(ctx context.Context) ([]StorageConfigListEnabledRow, error)
	// StorageConfigSetDefault 将指定 storage_id 设为默认
	StorageConfigSetDefault(ctx context.Context, arg StorageConfigSetDefaultParams) error
	// StorageConfigUpdateByStorageId 按 storage_id 更新
	StorageConfigUpdateByStorageId(ctx context.Context, arg StorageConfigUpdateByStorageIdParams) error
	// TaskRecordDeleteByTaskId 按 task_id 删除任务记录
	TaskRecordDeleteByTaskId(ctx context.Context, arg TaskRecordDeleteByTaskIdParams) error
	// TaskRecordGetByTaskId 按 task_id 获取任务记录
	TaskRecordGetByTaskId(ctx context.Context, arg TaskRecordGetByTaskIdParams) (LTaskRecord, error)
	// TaskRecordList 任务记录列表（可选 status IN, queue, priority, created_at 范围，分页）
	TaskRecordList(ctx context.Context, arg TaskRecordListParams) ([]LTaskRecord, error)
	// TaskRecordUpdateStatus 更新任务状态及时间戳（按 status 写 started_at/completed_at/failed_at/error）
	TaskRecordUpdateStatus(ctx context.Context, arg TaskRecordUpdateStatusParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// TaskRecordUpsert 插入或更新任务记录（MySQL: ON DUPLICATE KEY UPDATE）
	TaskRecordUpsert(ctx context.Context, arg TaskRecordUpsertParams) error
	// TeamBatchGetByTeamIds 按 team_id 列表批量获取团队
	TeamBatchGetByTeamIds(ctx context.Context, arg TeamBatchGetByTeamIdsParams) ([]TTeam, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// TeamCreate 创建团队
	TeamCreate(ctx context.Context, arg TeamCreateParams) error
	// TeamDeleteByTeamId 按 team_id 删除团队
	TeamDeleteByTeamId(ctx context.Context, arg TeamDeleteByTeamIdParams) error
	// TeamExistsByTeamId 判断团队是否存在
	TeamExistsByTeamId(ctx context.Context, arg TeamExistsByTeamIdParams) (int32, error)
	// TeamGetByOrgIdAndName 按 org_id 与 name 获取团队
	TeamGetByOrgIdAndName(ctx context.Context, arg TeamGetByOrgIdAndNameParams) (TTeam, error)
	// TeamGetByTeamId 按 team_id 获取团队
	TeamGetByTeamId(ctx context.Context, arg TeamGetByTeamIdParams) (TTeam, error)
	// TeamIncrementMembers 团队成员数 +delta
	TeamIncrementMembers(ctx context.Context, arg TeamIncrementMembersParams) error
	// TeamIncrementProjects 团队项目数 +delta
	TeamIncrementProjects(ctx context.Context, arg TeamIncrementProjectsParams) error
	// TeamList 团队列表分页
	TeamList(ctx context.Context, arg TeamListParams) ([]TeamListRow, error)
	// TeamListByOrg 按组织获取团队列表
	TeamListByOrg(ctx context.Context, arg TeamListByOrgParams) ([]TeamListByOrgRow, error)
	// TeamListByUser 按用户获取其所属团队列表（JOIN t_team_member）
	TeamListByUser(ctx context.Context, arg TeamListByUserParams) ([]TeamListByUserRow, error)
	// TeamListCount 团队列表总数（可选条件：org_id, name LIKE, parent_team_id, visibility, is_enabled）
	TeamListCount(ctx context.Context, arg TeamListCountParams) (int64, error)
	// TeamListSubTeams 获取子团队列表
	TeamListSubTeams(ctx context.Context, arg TeamListSubTeamsParams) ([]TeamListSubTeamsRow, error)
	// TeamMemberAdd 添加团队成员
	TeamMemberAdd(ctx context.Context, arg TeamMemberAddParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// TeamMemberGet 按 team_id 与 user_id 获取团队成员
	TeamMemberGet(ctx context.Context, arg TeamMemberGetParams) (TeamMemberGetRow, error)
	// TeamMemberListByTeamId 按 team_id 列出成员
	TeamMemberListByTeamId(ctx context.Context, arg TeamMemberListByTeamIdParams) ([]TeamMemberListByTeamIdRow, error)
	// TeamMemberListByUserId 按 user_id 列出其团队成员关系
	TeamMemberListByUserId(ctx context.Context, arg TeamMemberListByUserIdParams) ([]TeamMemberListByUserIdRow, error)
	// TeamMemberRemove 移除团队成员
	TeamMemberRemove(ctx context.Context, arg TeamMemberRemoveParams) error
	// TeamMemberUpdateRole 更新团队成员角色
	TeamMemberUpdateRole(ctx context.Context, arg TeamMemberUpdateRoleParams) error
	// TeamNameExists 判断组织下团队名称是否存在（可排除指定 team_id）
	TeamNameExists(ctx context.Context, arg TeamNameExistsParams) (bool, error)
	// TeamUpdateByTeamId 按 team_id 更新团队（动态字段由调用方传入）
	TeamUpdateByTeamId(ctx context.Context, arg TeamUpdateByTeamIdParams) error
	// TeamUpdatePath 更新团队 path 与 level
	TeamUpdatePath(ctx context.Context, arg TeamUpdatePathParams) error
	// TeamUpdateStatistics 更新团队统计（total_members, total_projects）
	TeamUpdateStatistics(ctx context.Context, arg TeamUpdateStatisticsParams) error
	// UserCount 用户总数
	UserCount(ctx context.Context) (int64, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// UserCreate 创建用户（AddUserReq -> t_user）
	UserCreate(ctx context.Context, arg UserCreateParams) error
	// UserDeleteByUserId 按 user_id 删除用户
	UserDeleteByUserId(ctx context.Context, arg UserDeleteByUserIdParams) error
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// UserExtCreate 创建用户扩展
	UserExtCreate(ctx context.Context, arg UserExtCreateParams) error
	// UserExtDeleteByUserId 按 user_id 删除用户扩展
	UserExtDeleteByUserId(ctx context.Context, arg UserExtDeleteByUserIdParams) error
	// UserExtExistsByUserId 判断用户扩展是否存在
	UserExtExistsByUserId(ctx context.Context, arg UserExtExistsByUserIdParams) (bool, error)
	// UserExtGetByUserId 按 user_id 获取用户扩展
	UserExtGetByUserId(ctx context.Context, arg UserExtGetByUserIdParams) (TUserExt, error)
	// UserExtUpdateByUserId 按 user_id 更新用户扩展
	UserExtUpdateByUserId(ctx context.Context, arg UserExtUpdateByUserIdParams) error
	// UserExtUpdateInvitationStatus 更新邀请状态（accepted 时写 accepted_at）
	UserExtUpdateInvitationStatus(ctx context.Context, arg UserExtUpdateInvitationStatusParams) error
	// UserExtUpdateLastLogin 更新最后登录时间
	UserExtUpdateLastLogin(ctx context.Context, arg UserExtUpdateLastLoginParams) error
	// UserExtUpdateTimezone 更新时区
	UserExtUpdateTimezone(ctx context.Context, arg UserExtUpdateTimezoneParams) error
	// UserFetchInfoByUserId 获取用户基本信息（不含 password）
	UserFetchInfoByUserId(ctx context.Context, arg UserFetchInfoByUserIdParams) (UserFetchInfoByUserIdRow, error)
	// UserGetByEmail 按 email 获取用户（不含 password）
	UserGetByEmail(ctx context.Context, arg UserGetByEmailParams) (UserGetByEmailRow, error)
	// UserGetByUserId 按 user_id 获取用户
	UserGetByUserId(ctx context.Context, arg UserGetByUserIdParams) (TUser, error)
	// UserGetByUsername 按 username 获取用户（不含 password）
	UserGetByUsername(ctx context.Context, arg UserGetByUsernameParams) (UserGetByUsernameRow, error)
	// UserGetPasswordByUserId 获取用户密码哈希
	UserGetPasswordByUserId(ctx context.Context, arg UserGetPasswordByUserIdParams) (string, error)
	// UserGetUserIdByUsername 按 username 获取 user_id
	UserGetUserIdByUsername(ctx context.Context, arg UserGetUserIdByUsernameParams) (string, error)
	// UserListSimple 简单用户列表（不含 password，按 id DESC 分页）
	UserListSimple(ctx context.Context, arg UserListSimpleParams) ([]UserListSimpleRow, error)
	// UserListWithExtAndRole 用户列表（含扩展表与角色名，分页）
	UserListWithExtAndRole(ctx context.Context, arg UserListWithExtAndRoleParams) ([]UserListWithExtAndRoleRow, error)
	// UserListWithExtAndRoleByRoleId 按 role_id 过滤的用户列表（含扩展与角色名）
	UserListWithExtAndRoleByRoleId(ctx context.Context, arg UserListWithExtAndRoleByRoleIdParams) ([]UserListWithExtAndRoleByRoleIdRow, error)
	// UserListWithExtAndRoleByRoleIdCount 按 role_id 过滤的用户总数
	UserListWithExtAndRoleByRoleIdCount(ctx context.Context, arg UserListWithExtAndRoleByRoleIdCountParams) (int64, error)
	// UserListWithExtAndRoleByRoleName 按角色名过滤的用户列表（含扩展与角色名）
	UserListWithExtAndRoleByRoleName(ctx context.Context, arg UserListWithExtAndRoleByRoleNameParams) ([]UserListWithExtAndRoleByRoleNameRow, error)
	// UserListWithExtAndRoleByRoleNameCount 按角色名过滤的用户总数
	UserListWithExtAndRoleByRoleNameCount(ctx context.Context, arg UserListWithExtAndRoleByRoleNameCountParams) (int64, error)
	// UserListWithExtAndRoleCount 用户列表总数（无角色过滤，与 UserListWithExtAndRole 对应）
	UserListWithExtAndRoleCount(ctx context.Context) (int64, error)
	// UserLogin 登录（username 或 email + is_enabled=1）
	UserLogin(ctx context.Context, arg UserLoginParams) (UserLoginRow, error)
	// UserResetPasswordByUserId 重置密码
	UserResetPasswordByUserId(ctx context.Context, arg UserResetPasswordByUserIdParams) error
	// UserRoleBindingCreate 创建用户角色绑定
	UserRoleBindingCreate(ctx context.Context, arg UserRoleBindingCreateParams) error
	// UserRoleBindingDeleteByBindingId 按 binding_id 删除
	UserRoleBindingDeleteByBindingId(ctx context.Context, arg UserRoleBindingDeleteByBindingIdParams) error
	// UserRoleBindingDeleteByUserId 按 user_id 删除该用户全部绑定
	UserRoleBindingDeleteByUserId(ctx context.Context, arg UserRoleBindingDeleteByUserIdParams) error
	// UserRoleBindingGetByUserIdAndRoleId 按 user_id 与 role_id 获取绑定
	UserRoleBindingGetByUserIdAndRoleId(ctx context.Context, arg UserRoleBindingGetByUserIdAndRoleIdParams) (UserRoleBindingGetByUserIdAndRoleIdRow, error)
	// Copyright 2026 Arcentra Authors.
	//
	// Licensed under the Apache License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License.
	// You may obtain a copy of the License at
	//
	//      http://www.apache.org/licenses/LICENSE-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	// See the License for the specific language governing permissions and
	// limitations under the License.
	// UserRoleBindingListByUserId 按 user_id 列出用户角色绑定
	UserRoleBindingListByUserId(ctx context.Context, arg UserRoleBindingListByUserIdParams) ([]UserRoleBindingListByUserIdRow, error)
	// UserUpdateByUserId 按 user_id 更新（动态字段，不含 user_id/username/created_at）
	UserUpdateByUserId(ctx context.Context, arg UserUpdateByUserIdParams) error
}

var _ Querier = (*Queries)(nil)
