// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const roleBatchGetByRoleIds = `-- name: RoleBatchGetByRoleIds :many
SELECT id, role_id, name, display_name, description, is_enabled, created_at, updated_at FROM t_role WHERE role_id IN (?)
`

type RoleBatchGetByRoleIdsParams struct {
	RoleID string `json:"role_id"`
}

// RoleBatchGetByRoleIds 按 role_id 列表批量获取
func (q *Queries) RoleBatchGetByRoleIds(ctx context.Context, arg RoleBatchGetByRoleIdsParams) ([]TRole, error) {
	rows, err := q.db.QueryContext(ctx, roleBatchGetByRoleIds, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TRole{}
	for rows.Next() {
		var i TRole
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleCount = `-- name: RoleCount :one
SELECT COUNT(*) FROM t_role
`

// RoleCount 角色总数
func (q *Queries) RoleCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, roleCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const roleCreate = `-- name: RoleCreate :exec

INSERT INTO t_role (role_id, name, display_name, description, is_enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type RoleCreateParams struct {
	RoleID      string         `json:"role_id"`
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	Description sql.NullString `json:"description"`
	IsEnabled   int8           `json:"is_enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// RoleCreate 创建角色
func (q *Queries) RoleCreate(ctx context.Context, arg RoleCreateParams) error {
	_, err := q.db.ExecContext(ctx, roleCreate,
		arg.RoleID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.IsEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const roleDeleteByRoleId = `-- name: RoleDeleteByRoleId :exec
DELETE FROM t_role WHERE role_id = ?
`

type RoleDeleteByRoleIdParams struct {
	RoleID string `json:"role_id"`
}

// RoleDeleteByRoleId 按 role_id 硬删除角色
func (q *Queries) RoleDeleteByRoleId(ctx context.Context, arg RoleDeleteByRoleIdParams) error {
	_, err := q.db.ExecContext(ctx, roleDeleteByRoleId, arg.RoleID)
	return err
}

const roleGetByRoleId = `-- name: RoleGetByRoleId :one
SELECT id, role_id, name, display_name, description, is_enabled, created_at, updated_at FROM t_role WHERE role_id = ? LIMIT 1
`

type RoleGetByRoleIdParams struct {
	RoleID string `json:"role_id"`
}

// RoleGetByRoleId 按 role_id 获取角色
func (q *Queries) RoleGetByRoleId(ctx context.Context, arg RoleGetByRoleIdParams) (TRole, error) {
	row := q.db.QueryRowContext(ctx, roleGetByRoleId, arg.RoleID)
	var i TRole
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const roleList = `-- name: RoleList :many
SELECT id, role_id, name, display_name, description, is_enabled, created_at, updated_at FROM t_role ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type RoleListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// RoleList 角色列表分页
func (q *Queries) RoleList(ctx context.Context, arg RoleListParams) ([]TRole, error) {
	rows, err := q.db.QueryContext(ctx, roleList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TRole{}
	for rows.Next() {
		var i TRole
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleSoftDeleteByRoleId = `-- name: RoleSoftDeleteByRoleId :exec
UPDATE t_role SET is_enabled = 0, updated_at = ? WHERE role_id = ?
`

type RoleSoftDeleteByRoleIdParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	RoleID    string    `json:"role_id"`
}

// RoleSoftDeleteByRoleId 软删除角色（is_enabled=0）
func (q *Queries) RoleSoftDeleteByRoleId(ctx context.Context, arg RoleSoftDeleteByRoleIdParams) error {
	_, err := q.db.ExecContext(ctx, roleSoftDeleteByRoleId, arg.UpdatedAt, arg.RoleID)
	return err
}

const roleUpdateByRoleId = `-- name: RoleUpdateByRoleId :exec
UPDATE t_role SET name = COALESCE(?, name), display_name = COALESCE(?, display_name), description = COALESCE(?, description), is_enabled = COALESCE(?, is_enabled), updated_at = ? WHERE role_id = ?
`

type RoleUpdateByRoleIdParams struct {
	Name        string         `json:"name"`
	DisplayName sql.NullString `json:"display_name"`
	Description sql.NullString `json:"description"`
	IsEnabled   int8           `json:"is_enabled"`
	UpdatedAt   time.Time      `json:"updated_at"`
	RoleID      string         `json:"role_id"`
}

// RoleUpdateByRoleId 按 role_id 更新（动态字段）
func (q *Queries) RoleUpdateByRoleId(ctx context.Context, arg RoleUpdateByRoleIdParams) error {
	_, err := q.db.ExecContext(ctx, roleUpdateByRoleId,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.IsEnabled,
		arg.UpdatedAt,
		arg.RoleID,
	)
	return err
}
