// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_menu_binding.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const roleMenuBindingCreate = `-- name: RoleMenuBindingCreate :exec
INSERT INTO t_role_menu_binding (role_menu_id, role_id, menu_id, resource_id, is_visible, is_accessible, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type RoleMenuBindingCreateParams struct {
	RoleMenuID   string         `json:"role_menu_id"`
	RoleID       string         `json:"role_id"`
	MenuID       string         `json:"menu_id"`
	ResourceID   sql.NullString `json:"resource_id"`
	IsVisible    int8           `json:"is_visible"`
	IsAccessible int8           `json:"is_accessible"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// RoleMenuBindingCreate 创建角色菜单绑定
func (q *Queries) RoleMenuBindingCreate(ctx context.Context, arg RoleMenuBindingCreateParams) error {
	_, err := q.db.ExecContext(ctx, roleMenuBindingCreate,
		arg.RoleMenuID,
		arg.RoleID,
		arg.MenuID,
		arg.ResourceID,
		arg.IsVisible,
		arg.IsAccessible,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const roleMenuBindingDeleteByRoleMenuId = `-- name: RoleMenuBindingDeleteByRoleMenuId :exec
DELETE FROM t_role_menu_binding WHERE role_menu_id = ?
`

type RoleMenuBindingDeleteByRoleMenuIdParams struct {
	RoleMenuID string `json:"role_menu_id"`
}

// RoleMenuBindingDeleteByRoleMenuId 按 role_menu_id 删除
func (q *Queries) RoleMenuBindingDeleteByRoleMenuId(ctx context.Context, arg RoleMenuBindingDeleteByRoleMenuIdParams) error {
	_, err := q.db.ExecContext(ctx, roleMenuBindingDeleteByRoleMenuId, arg.RoleMenuID)
	return err
}

const roleMenuBindingListByRoleId = `-- name: RoleMenuBindingListByRoleId :many

SELECT id, role_menu_id, role_id, menu_id, resource_id, is_visible, is_accessible, created_at, updated_at FROM t_role_menu_binding WHERE role_id = ? AND is_accessible = 1
`

type RoleMenuBindingListByRoleIdParams struct {
	RoleID string `json:"role_id"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// RoleMenuBindingListByRoleId 按 role_id 列出角色菜单绑定（is_accessible=1）
func (q *Queries) RoleMenuBindingListByRoleId(ctx context.Context, arg RoleMenuBindingListByRoleIdParams) ([]TRoleMenuBinding, error) {
	rows, err := q.db.QueryContext(ctx, roleMenuBindingListByRoleId, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TRoleMenuBinding{}
	for rows.Next() {
		var i TRoleMenuBinding
		if err := rows.Scan(
			&i.ID,
			&i.RoleMenuID,
			&i.RoleID,
			&i.MenuID,
			&i.ResourceID,
			&i.IsVisible,
			&i.IsAccessible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleMenuBindingListByRoleIdAndResourceId = `-- name: RoleMenuBindingListByRoleIdAndResourceId :many
SELECT id, role_menu_id, role_id, menu_id, resource_id, is_visible, is_accessible, created_at, updated_at FROM t_role_menu_binding
WHERE role_id = ? AND is_accessible = 1 AND ((? = '') AND (resource_id IS NULL OR resource_id = '') OR resource_id = ?)
`

type RoleMenuBindingListByRoleIdAndResourceIdParams struct {
	RoleID     string         `json:"role_id"`
	Column2    interface{}    `json:"column_2"`
	ResourceID sql.NullString `json:"resource_id"`
}

// RoleMenuBindingListByRoleIdAndResourceId 按 role_id 与 resource_id 列出（resource_id 空则 IS NULL OR = ”）
func (q *Queries) RoleMenuBindingListByRoleIdAndResourceId(ctx context.Context, arg RoleMenuBindingListByRoleIdAndResourceIdParams) ([]TRoleMenuBinding, error) {
	rows, err := q.db.QueryContext(ctx, roleMenuBindingListByRoleIdAndResourceId, arg.RoleID, arg.Column2, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TRoleMenuBinding{}
	for rows.Next() {
		var i TRoleMenuBinding
		if err := rows.Scan(
			&i.ID,
			&i.RoleMenuID,
			&i.RoleID,
			&i.MenuID,
			&i.ResourceID,
			&i.IsVisible,
			&i.IsAccessible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleMenuBindingListByRoleIdsAndResourceId = `-- name: RoleMenuBindingListByRoleIdsAndResourceId :many
SELECT id, role_menu_id, role_id, menu_id, resource_id, is_visible, is_accessible, created_at, updated_at FROM t_role_menu_binding
WHERE role_id IN (?) AND is_accessible = 1 AND ((? = '') AND (resource_id IS NULL OR resource_id = '') OR resource_id = ?)
`

type RoleMenuBindingListByRoleIdsAndResourceIdParams struct {
	RoleID     string         `json:"role_id"`
	Column2    interface{}    `json:"column_2"`
	ResourceID sql.NullString `json:"resource_id"`
}

// RoleMenuBindingListByRoleIdsAndResourceId 按 role_id 列表与 resource_id 列出
func (q *Queries) RoleMenuBindingListByRoleIdsAndResourceId(ctx context.Context, arg RoleMenuBindingListByRoleIdsAndResourceIdParams) ([]TRoleMenuBinding, error) {
	rows, err := q.db.QueryContext(ctx, roleMenuBindingListByRoleIdsAndResourceId, arg.RoleID, arg.Column2, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TRoleMenuBinding{}
	for rows.Next() {
		var i TRoleMenuBinding
		if err := rows.Scan(
			&i.ID,
			&i.RoleMenuID,
			&i.RoleID,
			&i.MenuID,
			&i.ResourceID,
			&i.IsVisible,
			&i.IsAccessible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
