// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secret.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const secretCreate = `-- name: SecretCreate :exec

INSERT INTO t_secret (secret_id, name, secret_type, secret_value, description, scope, scope_id, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type SecretCreateParams struct {
	SecretID    string         `json:"secret_id"`
	Name        string         `json:"name"`
	SecretType  string         `json:"secret_type"`
	SecretValue string         `json:"secret_value"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	ScopeID     sql.NullString `json:"scope_id"`
	CreatedBy   string         `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// SecretCreate 创建密钥
func (q *Queries) SecretCreate(ctx context.Context, arg SecretCreateParams) error {
	_, err := q.db.ExecContext(ctx, secretCreate,
		arg.SecretID,
		arg.Name,
		arg.SecretType,
		arg.SecretValue,
		arg.Description,
		arg.Scope,
		arg.ScopeID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const secretDeleteBySecretId = `-- name: SecretDeleteBySecretId :exec
DELETE FROM t_secret WHERE secret_id = ?
`

type SecretDeleteBySecretIdParams struct {
	SecretID string `json:"secret_id"`
}

// SecretDeleteBySecretId 按 secret_id 删除密钥
func (q *Queries) SecretDeleteBySecretId(ctx context.Context, arg SecretDeleteBySecretIdParams) error {
	_, err := q.db.ExecContext(ctx, secretDeleteBySecretId, arg.SecretID)
	return err
}

const secretGetBySecretId = `-- name: SecretGetBySecretId :one
SELECT id, secret_id, name, secret_type, secret_value, description, scope, scope_id, created_by, created_at, updated_at FROM t_secret WHERE secret_id = ? LIMIT 1
`

type SecretGetBySecretIdParams struct {
	SecretID string `json:"secret_id"`
}

// SecretGetBySecretId 按 secret_id 获取密钥（含 secret_value）
func (q *Queries) SecretGetBySecretId(ctx context.Context, arg SecretGetBySecretIdParams) (TSecret, error) {
	row := q.db.QueryRowContext(ctx, secretGetBySecretId, arg.SecretID)
	var i TSecret
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.Name,
		&i.SecretType,
		&i.SecretValue,
		&i.Description,
		&i.Scope,
		&i.ScopeID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const secretGetValueBySecretId = `-- name: SecretGetValueBySecretId :one
SELECT secret_value FROM t_secret WHERE secret_id = ? LIMIT 1
`

type SecretGetValueBySecretIdParams struct {
	SecretID string `json:"secret_id"`
}

// SecretGetValueBySecretId 仅获取密钥值
func (q *Queries) SecretGetValueBySecretId(ctx context.Context, arg SecretGetValueBySecretIdParams) (string, error) {
	row := q.db.QueryRowContext(ctx, secretGetValueBySecretId, arg.SecretID)
	var secret_value string
	err := row.Scan(&secret_value)
	return secret_value, err
}

const secretList = `-- name: SecretList :many
SELECT id, secret_id, name, secret_type, description, scope, scope_id, created_by
FROM t_secret
WHERE (? = '' OR secret_type = ?) AND (? = '' OR scope = ?) AND (? = '' OR scope_id = ?) AND (? = '' OR created_by = ?)
ORDER BY id DESC LIMIT ? OFFSET ?
`

type SecretListParams struct {
	Column1    interface{}    `json:"column_1"`
	SecretType string         `json:"secret_type"`
	Column3    interface{}    `json:"column_3"`
	Scope      string         `json:"scope"`
	Column5    interface{}    `json:"column_5"`
	ScopeID    sql.NullString `json:"scope_id"`
	Column7    interface{}    `json:"column_7"`
	CreatedBy  string         `json:"created_by"`
	Limit      int32          `json:"limit"`
	Offset     int32          `json:"offset"`
}

type SecretListRow struct {
	ID          int32          `json:"id"`
	SecretID    string         `json:"secret_id"`
	Name        string         `json:"name"`
	SecretType  string         `json:"secret_type"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	ScopeID     sql.NullString `json:"scope_id"`
	CreatedBy   string         `json:"created_by"`
}

// SecretList 密钥列表分页（不含 secret_value）
func (q *Queries) SecretList(ctx context.Context, arg SecretListParams) ([]SecretListRow, error) {
	rows, err := q.db.QueryContext(ctx, secretList,
		arg.Column1,
		arg.SecretType,
		arg.Column3,
		arg.Scope,
		arg.Column5,
		arg.ScopeID,
		arg.Column7,
		arg.CreatedBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretListRow{}
	for rows.Next() {
		var i SecretListRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.Name,
			&i.SecretType,
			&i.Description,
			&i.Scope,
			&i.ScopeID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretListByScope = `-- name: SecretListByScope :many
SELECT id, secret_id, name, secret_type, description, scope, scope_id, created_by FROM t_secret WHERE scope = ? AND scope_id = ?
`

type SecretListByScopeParams struct {
	Scope   string         `json:"scope"`
	ScopeID sql.NullString `json:"scope_id"`
}

type SecretListByScopeRow struct {
	ID          int32          `json:"id"`
	SecretID    string         `json:"secret_id"`
	Name        string         `json:"name"`
	SecretType  string         `json:"secret_type"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	ScopeID     sql.NullString `json:"scope_id"`
	CreatedBy   string         `json:"created_by"`
}

// SecretListByScope 按 scope 与 scope_id 列出密钥（不含 value）
func (q *Queries) SecretListByScope(ctx context.Context, arg SecretListByScopeParams) ([]SecretListByScopeRow, error) {
	rows, err := q.db.QueryContext(ctx, secretListByScope, arg.Scope, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretListByScopeRow{}
	for rows.Next() {
		var i SecretListByScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.Name,
			&i.SecretType,
			&i.Description,
			&i.Scope,
			&i.ScopeID,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretListCount = `-- name: SecretListCount :one
SELECT COUNT(*) FROM t_secret
WHERE (? = '' OR secret_type = ?) AND (? = '' OR scope = ?) AND (? = '' OR scope_id = ?) AND (? = '' OR created_by = ?)
`

type SecretListCountParams struct {
	Column1    interface{}    `json:"column_1"`
	SecretType string         `json:"secret_type"`
	Column3    interface{}    `json:"column_3"`
	Scope      string         `json:"scope"`
	Column5    interface{}    `json:"column_5"`
	ScopeID    sql.NullString `json:"scope_id"`
	Column7    interface{}    `json:"column_7"`
	CreatedBy  string         `json:"created_by"`
}

// SecretListCount 密钥列表总数（可选：secret_type, scope, scope_id, created_by）
func (q *Queries) SecretListCount(ctx context.Context, arg SecretListCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, secretListCount,
		arg.Column1,
		arg.SecretType,
		arg.Column3,
		arg.Scope,
		arg.Column5,
		arg.ScopeID,
		arg.Column7,
		arg.CreatedBy,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const secretUpdateBySecretId = `-- name: SecretUpdateBySecretId :exec
UPDATE t_secret SET name = ?, secret_type = ?, secret_value = ?, description = ?, scope = ?, scope_id = ?, created_by = ?, updated_at = ? WHERE secret_id = ?
`

type SecretUpdateBySecretIdParams struct {
	Name        string         `json:"name"`
	SecretType  string         `json:"secret_type"`
	SecretValue string         `json:"secret_value"`
	Description sql.NullString `json:"description"`
	Scope       string         `json:"scope"`
	ScopeID     sql.NullString `json:"scope_id"`
	CreatedBy   string         `json:"created_by"`
	UpdatedAt   time.Time      `json:"updated_at"`
	SecretID    string         `json:"secret_id"`
}

// SecretUpdateBySecretId 按 secret_id 更新密钥（不含 id, secret_id, created_at）
func (q *Queries) SecretUpdateBySecretId(ctx context.Context, arg SecretUpdateBySecretIdParams) error {
	_, err := q.db.ExecContext(ctx, secretUpdateBySecretId,
		arg.Name,
		arg.SecretType,
		arg.SecretValue,
		arg.Description,
		arg.Scope,
		arg.ScopeID,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.SecretID,
	)
	return err
}
