// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package dal

import (
	"context"

	datatypes "gorm.io/datatypes"
)

const settingGet = `-- name: SettingGet :one
SELECT id, name, workspace, value, created_at, updated_at FROM t_setting WHERE workspace = ? AND name = ? LIMIT 1
`

type SettingGetParams struct {
	Workspace string `json:"workspace"`
	Name      string `json:"name"`
}

// SettingGet 按 workspace 与 name 获取配置
func (q *Queries) SettingGet(ctx context.Context, arg SettingGetParams) (TSetting, error) {
	row := q.db.QueryRowContext(ctx, settingGet, arg.Workspace, arg.Name)
	var i TSetting
	err := row.Scan(&i.ID, &i.Name, &i.Workspace, &i.Value, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const settingUpsert = `-- name: SettingUpsert :exec
INSERT INTO t_setting (name, workspace, value)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE value = VALUES(value), updated_at = CURRENT_TIMESTAMP
`

type SettingUpsertParams struct {
	Name      string         `json:"name"`
	Workspace string         `json:"workspace"`
	Value     datatypes.JSON `json:"value"`
}

// SettingUpsert 创建或更新配置
func (q *Queries) SettingUpsert(ctx context.Context, arg SettingUpsertParams) error {
	_, err := q.db.ExecContext(ctx, settingUpsert, arg.Name, arg.Workspace, arg.Value)
	return err
}

const settingList = `-- name: SettingList :many
SELECT id, name, workspace, value, created_at, updated_at FROM t_setting WHERE workspace = ? ORDER BY name ASC
`

// SettingList 按 workspace 列出所有配置
func (q *Queries) SettingList(ctx context.Context, workspace string) ([]TSetting, error) {
	rows, err := q.db.QueryContext(ctx, settingList, workspace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TSetting{}
	for rows.Next() {
		var i TSetting
		if err := rows.Scan(&i.ID, &i.Name, &i.Workspace, &i.Value, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settingDelete = `-- name: SettingDelete :exec
DELETE FROM t_setting WHERE workspace = ? AND name = ?
`

type SettingDeleteParams struct {
	Workspace string `json:"workspace"`
	Name      string `json:"name"`
}

// SettingDelete 按 workspace 与 name 删除配置
func (q *Queries) SettingDelete(ctx context.Context, arg SettingDeleteParams) error {
	_, err := q.db.ExecContext(ctx, settingDelete, arg.Workspace, arg.Name)
	return err
}
