// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step_run.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const stepRunArtifactListByStepRunId = `-- name: StepRunArtifactListByStepRunId :many
SELECT id, artifact_id, step_run_id, job_run_id, pipeline_run_id, name, path, destination, size, storage_type, storage_path, expire, created_at, updated_at FROM t_step_run_artifact WHERE step_run_id = ? ORDER BY created_at DESC
`

type StepRunArtifactListByStepRunIdParams struct {
	StepRunID string `json:"step_run_id"`
}

// StepRunArtifactListByStepRunId 按 step_run_id 获取产物列表
func (q *Queries) StepRunArtifactListByStepRunId(ctx context.Context, arg StepRunArtifactListByStepRunIdParams) ([]TStepRunArtifact, error) {
	rows, err := q.db.QueryContext(ctx, stepRunArtifactListByStepRunId, arg.StepRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TStepRunArtifact{}
	for rows.Next() {
		var i TStepRunArtifact
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.StepRunID,
			&i.JobRunID,
			&i.PipelineRunID,
			&i.Name,
			&i.Path,
			&i.Destination,
			&i.Size,
			&i.StorageType,
			&i.StoragePath,
			&i.Expire,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stepRunCreate = `-- name: StepRunCreate :exec

INSERT INTO t_step_run (step_run_id, pipeline_id, pipeline_run_id, job_id, name, agent_id, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type StepRunCreateParams struct {
	StepRunID     string         `json:"step_run_id"`
	PipelineID    string         `json:"pipeline_id"`
	PipelineRunID sql.NullString `json:"pipeline_run_id"`
	JobID         sql.NullString `json:"job_id"`
	Name          sql.NullString `json:"name"`
	AgentID       sql.NullString `json:"agent_id"`
	Status        int8           `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// StepRunCreate 创建步骤运行
func (q *Queries) StepRunCreate(ctx context.Context, arg StepRunCreateParams) error {
	_, err := q.db.ExecContext(ctx, stepRunCreate,
		arg.StepRunID,
		arg.PipelineID,
		arg.PipelineRunID,
		arg.JobID,
		arg.Name,
		arg.AgentID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const stepRunDeleteByStepRunId = `-- name: StepRunDeleteByStepRunId :exec
DELETE FROM t_step_run WHERE step_run_id = ?
`

type StepRunDeleteByStepRunIdParams struct {
	StepRunID string `json:"step_run_id"`
}

// StepRunDeleteByStepRunId 按 step_run_id 删除步骤运行
func (q *Queries) StepRunDeleteByStepRunId(ctx context.Context, arg StepRunDeleteByStepRunIdParams) error {
	_, err := q.db.ExecContext(ctx, stepRunDeleteByStepRunId, arg.StepRunID)
	return err
}

const stepRunGetByPipelineJobStep = `-- name: StepRunGetByPipelineJobStep :one
SELECT id, step_run_id, pipeline_id, pipeline_run_id, job_id, name, agent_id, status, created_at, updated_at FROM t_step_run WHERE pipeline_id = ? AND job_id = ? AND step_run_id = ? LIMIT 1
`

type StepRunGetByPipelineJobStepParams struct {
	PipelineID string         `json:"pipeline_id"`
	JobID      sql.NullString `json:"job_id"`
	StepRunID  string         `json:"step_run_id"`
}

// StepRunGetByPipelineJobStep 按 pipeline_id + job_id + step_run_id 获取
func (q *Queries) StepRunGetByPipelineJobStep(ctx context.Context, arg StepRunGetByPipelineJobStepParams) (TStepRun, error) {
	row := q.db.QueryRowContext(ctx, stepRunGetByPipelineJobStep, arg.PipelineID, arg.JobID, arg.StepRunID)
	var i TStepRun
	err := row.Scan(
		&i.ID,
		&i.StepRunID,
		&i.PipelineID,
		&i.PipelineRunID,
		&i.JobID,
		&i.Name,
		&i.AgentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stepRunGetByStepRunId = `-- name: StepRunGetByStepRunId :one
SELECT id, step_run_id, pipeline_id, pipeline_run_id, job_id, name, agent_id, status, created_at, updated_at FROM t_step_run WHERE step_run_id = ? LIMIT 1
`

type StepRunGetByStepRunIdParams struct {
	StepRunID string `json:"step_run_id"`
}

// StepRunGetByStepRunId 按 step_run_id 获取步骤运行
func (q *Queries) StepRunGetByStepRunId(ctx context.Context, arg StepRunGetByStepRunIdParams) (TStepRun, error) {
	row := q.db.QueryRowContext(ctx, stepRunGetByStepRunId, arg.StepRunID)
	var i TStepRun
	err := row.Scan(
		&i.ID,
		&i.StepRunID,
		&i.PipelineID,
		&i.PipelineRunID,
		&i.JobID,
		&i.Name,
		&i.AgentID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const stepRunList = `-- name: StepRunList :many
SELECT id, step_run_id, pipeline_id, pipeline_run_id, job_id, name, agent_id, status, created_at, updated_at FROM t_step_run
WHERE (? = '' OR pipeline_id = ?) AND (? = '' OR pipeline_run_id = ?) AND (? = '' OR job_id = ?) AND (? = '' OR name = ?) AND (? = '' OR agent_id = ?) AND (? <= 0 OR status = ?)
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type StepRunListParams struct {
	Column1       interface{}    `json:"column_1"`
	PipelineID    string         `json:"pipeline_id"`
	Column3       interface{}    `json:"column_3"`
	PipelineRunID sql.NullString `json:"pipeline_run_id"`
	Column5       interface{}    `json:"column_5"`
	JobID         sql.NullString `json:"job_id"`
	Column7       interface{}    `json:"column_7"`
	Name          sql.NullString `json:"name"`
	Column9       interface{}    `json:"column_9"`
	AgentID       sql.NullString `json:"agent_id"`
	Column11      interface{}    `json:"column_11"`
	Status        int8           `json:"status"`
	Limit         int32          `json:"limit"`
	Offset        int32          `json:"offset"`
}

// StepRunList 步骤运行列表分页
func (q *Queries) StepRunList(ctx context.Context, arg StepRunListParams) ([]TStepRun, error) {
	rows, err := q.db.QueryContext(ctx, stepRunList,
		arg.Column1,
		arg.PipelineID,
		arg.Column3,
		arg.PipelineRunID,
		arg.Column5,
		arg.JobID,
		arg.Column7,
		arg.Name,
		arg.Column9,
		arg.AgentID,
		arg.Column11,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TStepRun{}
	for rows.Next() {
		var i TStepRun
		if err := rows.Scan(
			&i.ID,
			&i.StepRunID,
			&i.PipelineID,
			&i.PipelineRunID,
			&i.JobID,
			&i.Name,
			&i.AgentID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stepRunListCount = `-- name: StepRunListCount :one
SELECT COUNT(*) FROM t_step_run
WHERE (? = '' OR pipeline_id = ?) AND (? = '' OR pipeline_run_id = ?) AND (? = '' OR job_id = ?) AND (? = '' OR name = ?) AND (? = '' OR agent_id = ?) AND (? <= 0 OR status = ?)
`

type StepRunListCountParams struct {
	Column1       interface{}    `json:"column_1"`
	PipelineID    string         `json:"pipeline_id"`
	Column3       interface{}    `json:"column_3"`
	PipelineRunID sql.NullString `json:"pipeline_run_id"`
	Column5       interface{}    `json:"column_5"`
	JobID         sql.NullString `json:"job_id"`
	Column7       interface{}    `json:"column_7"`
	Name          sql.NullString `json:"name"`
	Column9       interface{}    `json:"column_9"`
	AgentID       sql.NullString `json:"agent_id"`
	Column11      interface{}    `json:"column_11"`
	Status        int8           `json:"status"`
}

// StepRunListCount 步骤运行列表总数（动态条件见应用层）
func (q *Queries) StepRunListCount(ctx context.Context, arg StepRunListCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, stepRunListCount,
		arg.Column1,
		arg.PipelineID,
		arg.Column3,
		arg.PipelineRunID,
		arg.Column5,
		arg.JobID,
		arg.Column7,
		arg.Name,
		arg.Column9,
		arg.AgentID,
		arg.Column11,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const stepRunPatchByStepRunId = `-- name: StepRunPatchByStepRunId :exec
UPDATE t_step_run SET status = COALESCE(?, status), updated_at = ? WHERE step_run_id = ?
`

type StepRunPatchByStepRunIdParams struct {
	Status    int8      `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	StepRunID string    `json:"step_run_id"`
}

// StepRunPatchByStepRunId 按 step_run_id 部分更新（含 updated_at）
func (q *Queries) StepRunPatchByStepRunId(ctx context.Context, arg StepRunPatchByStepRunIdParams) error {
	_, err := q.db.ExecContext(ctx, stepRunPatchByStepRunId, arg.Status, arg.UpdatedAt, arg.StepRunID)
	return err
}
