// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage_config.sql

package dal

import (
	"context"
	"database/sql"
	"time"

	datatypes "gorm.io/datatypes"
)

const storageConfigClearDefault = `-- name: StorageConfigClearDefault :exec
UPDATE t_storage_config SET is_default = 0, updated_at = ? WHERE is_default = 1
`

type StorageConfigClearDefaultParams struct {
	UpdatedAt time.Time `json:"updated_at"`
}

// StorageConfigClearDefault 清除当前默认（将所有 is_default=1 置为 0）
func (q *Queries) StorageConfigClearDefault(ctx context.Context, arg StorageConfigClearDefaultParams) error {
	_, err := q.db.ExecContext(ctx, storageConfigClearDefault, arg.UpdatedAt)
	return err
}

const storageConfigCreate = `-- name: StorageConfigCreate :exec
INSERT INTO t_storage_config (storage_id, name, storage_type, config, description, is_default, is_enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type StorageConfigCreateParams struct {
	StorageID   string         `json:"storage_id"`
	Name        string         `json:"name"`
	StorageType string         `json:"storage_type"`
	Config      datatypes.JSON `json:"config"`
	Description sql.NullString `json:"description"`
	IsDefault   int8           `json:"is_default"`
	IsEnabled   int8           `json:"is_enabled"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// StorageConfigCreate 创建存储配置
func (q *Queries) StorageConfigCreate(ctx context.Context, arg StorageConfigCreateParams) error {
	_, err := q.db.ExecContext(ctx, storageConfigCreate,
		arg.StorageID,
		arg.Name,
		arg.StorageType,
		arg.Config,
		arg.Description,
		arg.IsDefault,
		arg.IsEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const storageConfigDeleteByStorageId = `-- name: StorageConfigDeleteByStorageId :exec
DELETE FROM t_storage_config WHERE storage_id = ?
`

type StorageConfigDeleteByStorageIdParams struct {
	StorageID string `json:"storage_id"`
}

// StorageConfigDeleteByStorageId 按 storage_id 删除
func (q *Queries) StorageConfigDeleteByStorageId(ctx context.Context, arg StorageConfigDeleteByStorageIdParams) error {
	_, err := q.db.ExecContext(ctx, storageConfigDeleteByStorageId, arg.StorageID)
	return err
}

const storageConfigGetByStorageId = `-- name: StorageConfigGetByStorageId :one
SELECT id, storage_id, name, storage_type, config, description, is_default, is_enabled, created_at, updated_at FROM t_storage_config WHERE storage_id = ? AND is_enabled = 1 LIMIT 1
`

type StorageConfigGetByStorageIdParams struct {
	StorageID string `json:"storage_id"`
}

// StorageConfigGetByStorageId 按 storage_id 获取（仅启用）
func (q *Queries) StorageConfigGetByStorageId(ctx context.Context, arg StorageConfigGetByStorageIdParams) (TStorageConfig, error) {
	row := q.db.QueryRowContext(ctx, storageConfigGetByStorageId, arg.StorageID)
	var i TStorageConfig
	err := row.Scan(
		&i.ID,
		&i.StorageID,
		&i.Name,
		&i.StorageType,
		&i.Config,
		&i.Description,
		&i.IsDefault,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const storageConfigGetDefault = `-- name: StorageConfigGetDefault :one

SELECT id, storage_id, name, storage_type, config, description, is_default, is_enabled, created_at, updated_at FROM t_storage_config WHERE is_default = 1 AND is_enabled = 1 LIMIT 1
`

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// StorageConfigGetDefault 获取默认存储配置（is_default=1 且 is_enabled=1）
func (q *Queries) StorageConfigGetDefault(ctx context.Context) (TStorageConfig, error) {
	row := q.db.QueryRowContext(ctx, storageConfigGetDefault)
	var i TStorageConfig
	err := row.Scan(
		&i.ID,
		&i.StorageID,
		&i.Name,
		&i.StorageType,
		&i.Config,
		&i.Description,
		&i.IsDefault,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const storageConfigListByType = `-- name: StorageConfigListByType :many
SELECT storage_id, name, storage_type, config, description, is_default, is_enabled FROM t_storage_config WHERE storage_type = ? AND is_enabled = 1 ORDER BY is_default DESC, storage_id ASC
`

type StorageConfigListByTypeParams struct {
	StorageType string `json:"storage_type"`
}

type StorageConfigListByTypeRow struct {
	StorageID   string         `json:"storage_id"`
	Name        string         `json:"name"`
	StorageType string         `json:"storage_type"`
	Config      datatypes.JSON `json:"config"`
	Description sql.NullString `json:"description"`
	IsDefault   int8           `json:"is_default"`
	IsEnabled   int8           `json:"is_enabled"`
}

// StorageConfigListByType 按 storage_type 列出启用配置
func (q *Queries) StorageConfigListByType(ctx context.Context, arg StorageConfigListByTypeParams) ([]StorageConfigListByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, storageConfigListByType, arg.StorageType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageConfigListByTypeRow{}
	for rows.Next() {
		var i StorageConfigListByTypeRow
		if err := rows.Scan(
			&i.StorageID,
			&i.Name,
			&i.StorageType,
			&i.Config,
			&i.Description,
			&i.IsDefault,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageConfigListEnabled = `-- name: StorageConfigListEnabled :many
SELECT storage_id, name, storage_type, config, description, is_default, is_enabled FROM t_storage_config WHERE is_enabled = 1 ORDER BY is_default DESC, storage_id ASC
`

type StorageConfigListEnabledRow struct {
	StorageID   string         `json:"storage_id"`
	Name        string         `json:"name"`
	StorageType string         `json:"storage_type"`
	Config      datatypes.JSON `json:"config"`
	Description sql.NullString `json:"description"`
	IsDefault   int8           `json:"is_default"`
	IsEnabled   int8           `json:"is_enabled"`
}

// StorageConfigListEnabled 列出所有启用配置
func (q *Queries) StorageConfigListEnabled(ctx context.Context) ([]StorageConfigListEnabledRow, error) {
	rows, err := q.db.QueryContext(ctx, storageConfigListEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageConfigListEnabledRow{}
	for rows.Next() {
		var i StorageConfigListEnabledRow
		if err := rows.Scan(
			&i.StorageID,
			&i.Name,
			&i.StorageType,
			&i.Config,
			&i.Description,
			&i.IsDefault,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storageConfigSetDefault = `-- name: StorageConfigSetDefault :exec
UPDATE t_storage_config SET is_default = 1, updated_at = ? WHERE storage_id = ?
`

type StorageConfigSetDefaultParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	StorageID string    `json:"storage_id"`
}

// StorageConfigSetDefault 将指定 storage_id 设为默认
func (q *Queries) StorageConfigSetDefault(ctx context.Context, arg StorageConfigSetDefaultParams) error {
	_, err := q.db.ExecContext(ctx, storageConfigSetDefault, arg.UpdatedAt, arg.StorageID)
	return err
}

const storageConfigUpdateByStorageId = `-- name: StorageConfigUpdateByStorageId :exec
UPDATE t_storage_config SET name = ?, storage_type = ?, config = ?, description = ?, is_default = ?, is_enabled = ?, updated_at = ? WHERE storage_id = ?
`

type StorageConfigUpdateByStorageIdParams struct {
	Name        string         `json:"name"`
	StorageType string         `json:"storage_type"`
	Config      datatypes.JSON `json:"config"`
	Description sql.NullString `json:"description"`
	IsDefault   int8           `json:"is_default"`
	IsEnabled   int8           `json:"is_enabled"`
	UpdatedAt   time.Time      `json:"updated_at"`
	StorageID   string         `json:"storage_id"`
}

// StorageConfigUpdateByStorageId 按 storage_id 更新
func (q *Queries) StorageConfigUpdateByStorageId(ctx context.Context, arg StorageConfigUpdateByStorageIdParams) error {
	_, err := q.db.ExecContext(ctx, storageConfigUpdateByStorageId,
		arg.Name,
		arg.StorageType,
		arg.Config,
		arg.Description,
		arg.IsDefault,
		arg.IsEnabled,
		arg.UpdatedAt,
		arg.StorageID,
	)
	return err
}
