// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_record.sql

package dal

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	datatypes "gorm.io/datatypes"
)

const taskRecordDeleteByTaskId = `-- name: TaskRecordDeleteByTaskId :exec
DELETE FROM l_task_records WHERE task_id = ?
`

type TaskRecordDeleteByTaskIdParams struct {
	TaskID string `json:"task_id"`
}

// TaskRecordDeleteByTaskId 按 task_id 删除任务记录
func (q *Queries) TaskRecordDeleteByTaskId(ctx context.Context, arg TaskRecordDeleteByTaskIdParams) error {
	_, err := q.db.ExecContext(ctx, taskRecordDeleteByTaskId, arg.TaskID)
	return err
}

const taskRecordGetByTaskId = `-- name: TaskRecordGetByTaskId :one
SELECT task_id, task_type, task_payload, status, queue, priority, created_at, queued_at, process_at, started_at, completed_at, failed_at, error, retry_count, metadata FROM l_task_records WHERE task_id = ? LIMIT 1
`

type TaskRecordGetByTaskIdParams struct {
	TaskID string `json:"task_id"`
}

// TaskRecordGetByTaskId 按 task_id 获取任务记录
func (q *Queries) TaskRecordGetByTaskId(ctx context.Context, arg TaskRecordGetByTaskIdParams) (LTaskRecord, error) {
	row := q.db.QueryRowContext(ctx, taskRecordGetByTaskId, arg.TaskID)
	var i LTaskRecord
	err := row.Scan(
		&i.TaskID,
		&i.TaskType,
		&i.TaskPayload,
		&i.Status,
		&i.Queue,
		&i.Priority,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.ProcessAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.Error,
		&i.RetryCount,
		&i.Metadata,
	)
	return i, err
}

const taskRecordList = `-- name: TaskRecordList :many
SELECT task_id, task_type, task_payload, status, queue, priority, created_at, queued_at, process_at, started_at, completed_at, failed_at, error, retry_count, metadata FROM l_task_records
WHERE (? = 0 OR status IN (?)) AND (? = '' OR queue = ?) AND (? IS NULL OR priority = ?)
  AND (? IS NULL OR created_at >= ?) AND (? IS NULL OR created_at <= ?)
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type TaskRecordListParams struct {
	Column1     interface{} `json:"column_1"`
	Status      string      `json:"status"`
	Column3     interface{} `json:"column_3"`
	Queue       string      `json:"queue"`
	Column5     interface{} `json:"column_5"`
	Priority    int32       `json:"priority"`
	Column7     interface{} `json:"column_7"`
	CreatedAt   time.Time   `json:"created_at"`
	Column9     interface{} `json:"column_9"`
	CreatedAt_2 time.Time   `json:"created_at_2"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

// TaskRecordList 任务记录列表（可选 status IN, queue, priority, created_at 范围，分页）
func (q *Queries) TaskRecordList(ctx context.Context, arg TaskRecordListParams) ([]LTaskRecord, error) {
	rows, err := q.db.QueryContext(ctx, taskRecordList,
		arg.Column1,
		arg.Status,
		arg.Column3,
		arg.Queue,
		arg.Column5,
		arg.Priority,
		arg.Column7,
		arg.CreatedAt,
		arg.Column9,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LTaskRecord{}
	for rows.Next() {
		var i LTaskRecord
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskType,
			&i.TaskPayload,
			&i.Status,
			&i.Queue,
			&i.Priority,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.ProcessAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.Error,
			&i.RetryCount,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskRecordUpdateStatus = `-- name: TaskRecordUpdateStatus :exec
UPDATE l_task_records SET status = ?, started_at = COALESCE(?, started_at), completed_at = COALESCE(?, completed_at), failed_at = COALESCE(?, failed_at), error = COALESCE(?, error) WHERE task_id = ?
`

type TaskRecordUpdateStatusParams struct {
	Status      string         `json:"status"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	FailedAt    sql.NullTime   `json:"failed_at"`
	Error       sql.NullString `json:"error"`
	TaskID      string         `json:"task_id"`
}

// TaskRecordUpdateStatus 更新任务状态及时间戳（按 status 写 started_at/completed_at/failed_at/error）
func (q *Queries) TaskRecordUpdateStatus(ctx context.Context, arg TaskRecordUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, taskRecordUpdateStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
		arg.Error,
		arg.TaskID,
	)
	return err
}

const taskRecordUpsert = `-- name: TaskRecordUpsert :exec

INSERT INTO l_task_records (task_id, task_type, task_payload, status, queue, priority, created_at, queued_at, process_at, started_at, completed_at, failed_at, error, retry_count, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE task_type = VALUES(task_type), task_payload = VALUES(task_payload), status = VALUES(status), queue = VALUES(queue), priority = VALUES(priority), queued_at = VALUES(queued_at), process_at = VALUES(process_at), started_at = VALUES(started_at), completed_at = VALUES(completed_at), failed_at = VALUES(failed_at), error = VALUES(error), retry_count = VALUES(retry_count), metadata = VALUES(metadata)
`

type TaskRecordUpsertParams struct {
	TaskID      string          `json:"task_id"`
	TaskType    string          `json:"task_type"`
	TaskPayload datatypes.JSON  `json:"task_payload"`
	Status      string          `json:"status"`
	Queue       string          `json:"queue"`
	Priority    int32           `json:"priority"`
	CreatedAt   time.Time       `json:"created_at"`
	QueuedAt    sql.NullTime    `json:"queued_at"`
	ProcessAt   sql.NullTime    `json:"process_at"`
	StartedAt   sql.NullTime    `json:"started_at"`
	CompletedAt sql.NullTime    `json:"completed_at"`
	FailedAt    sql.NullTime    `json:"failed_at"`
	Error       sql.NullString  `json:"error"`
	RetryCount  int32           `json:"retry_count"`
	Metadata    json.RawMessage `json:"metadata"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// TaskRecordUpsert 插入或更新任务记录（MySQL: ON DUPLICATE KEY UPDATE）
func (q *Queries) TaskRecordUpsert(ctx context.Context, arg TaskRecordUpsertParams) error {
	_, err := q.db.ExecContext(ctx, taskRecordUpsert,
		arg.TaskID,
		arg.TaskType,
		arg.TaskPayload,
		arg.Status,
		arg.Queue,
		arg.Priority,
		arg.CreatedAt,
		arg.QueuedAt,
		arg.ProcessAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailedAt,
		arg.Error,
		arg.RetryCount,
		arg.Metadata,
	)
	return err
}
