// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package dal

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const teamBatchGetByTeamIds = `-- name: TeamBatchGetByTeamIds :many
SELECT id, team_id, org_id, name, display_name, description, avatar, parent_team_id, path, level, settings, visibility, is_enabled, total_members, total_projects, created_at, updated_at
FROM t_team WHERE team_id IN (?)
`

type TeamBatchGetByTeamIdsParams struct {
	TeamID string `json:"team_id"`
}

// TeamBatchGetByTeamIds 按 team_id 列表批量获取团队
func (q *Queries) TeamBatchGetByTeamIds(ctx context.Context, arg TeamBatchGetByTeamIdsParams) ([]TTeam, error) {
	rows, err := q.db.QueryContext(ctx, teamBatchGetByTeamIds, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TTeam{}
	for rows.Next() {
		var i TTeam
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.ParentTeamID,
			&i.Path,
			&i.Level,
			&i.Settings,
			&i.Visibility,
			&i.IsEnabled,
			&i.TotalMembers,
			&i.TotalProjects,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamCreate = `-- name: TeamCreate :exec

INSERT INTO t_team (team_id, org_id, name, display_name, description, avatar, parent_team_id, path, level, settings, visibility, is_enabled, total_members, total_projects, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type TeamCreateParams struct {
	TeamID        string          `json:"team_id"`
	OrgID         string          `json:"org_id"`
	Name          string          `json:"name"`
	DisplayName   string          `json:"display_name"`
	Description   sql.NullString  `json:"description"`
	Avatar        sql.NullString  `json:"avatar"`
	ParentTeamID  sql.NullString  `json:"parent_team_id"`
	Path          sql.NullString  `json:"path"`
	Level         int32           `json:"level"`
	Settings      json.RawMessage `json:"settings"`
	Visibility    int8            `json:"visibility"`
	IsEnabled     int8            `json:"is_enabled"`
	TotalMembers  int32           `json:"total_members"`
	TotalProjects int32           `json:"total_projects"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// TeamCreate 创建团队
func (q *Queries) TeamCreate(ctx context.Context, arg TeamCreateParams) error {
	_, err := q.db.ExecContext(ctx, teamCreate,
		arg.TeamID,
		arg.OrgID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Avatar,
		arg.ParentTeamID,
		arg.Path,
		arg.Level,
		arg.Settings,
		arg.Visibility,
		arg.IsEnabled,
		arg.TotalMembers,
		arg.TotalProjects,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const teamDeleteByTeamId = `-- name: TeamDeleteByTeamId :exec
DELETE FROM t_team WHERE team_id = ?
`

type TeamDeleteByTeamIdParams struct {
	TeamID string `json:"team_id"`
}

// TeamDeleteByTeamId 按 team_id 删除团队
func (q *Queries) TeamDeleteByTeamId(ctx context.Context, arg TeamDeleteByTeamIdParams) error {
	_, err := q.db.ExecContext(ctx, teamDeleteByTeamId, arg.TeamID)
	return err
}

const teamExistsByTeamId = `-- name: TeamExistsByTeamId :one
SELECT 1 FROM t_team WHERE team_id = ? LIMIT 1
`

type TeamExistsByTeamIdParams struct {
	TeamID string `json:"team_id"`
}

// TeamExistsByTeamId 判断团队是否存在
func (q *Queries) TeamExistsByTeamId(ctx context.Context, arg TeamExistsByTeamIdParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, teamExistsByTeamId, arg.TeamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const teamGetByOrgIdAndName = `-- name: TeamGetByOrgIdAndName :one
SELECT id, team_id, org_id, name, display_name, description, avatar, parent_team_id, path, level, settings, visibility, is_enabled, total_members, total_projects, created_at, updated_at
FROM t_team WHERE org_id = ? AND name = ? LIMIT 1
`

type TeamGetByOrgIdAndNameParams struct {
	OrgID string `json:"org_id"`
	Name  string `json:"name"`
}

// TeamGetByOrgIdAndName 按 org_id 与 name 获取团队
func (q *Queries) TeamGetByOrgIdAndName(ctx context.Context, arg TeamGetByOrgIdAndNameParams) (TTeam, error) {
	row := q.db.QueryRowContext(ctx, teamGetByOrgIdAndName, arg.OrgID, arg.Name)
	var i TTeam
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.ParentTeamID,
		&i.Path,
		&i.Level,
		&i.Settings,
		&i.Visibility,
		&i.IsEnabled,
		&i.TotalMembers,
		&i.TotalProjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const teamGetByTeamId = `-- name: TeamGetByTeamId :one
SELECT id, team_id, org_id, name, display_name, description, avatar, parent_team_id, path, level, settings, visibility, is_enabled, total_members, total_projects, created_at, updated_at
FROM t_team WHERE team_id = ? LIMIT 1
`

type TeamGetByTeamIdParams struct {
	TeamID string `json:"team_id"`
}

// TeamGetByTeamId 按 team_id 获取团队
func (q *Queries) TeamGetByTeamId(ctx context.Context, arg TeamGetByTeamIdParams) (TTeam, error) {
	row := q.db.QueryRowContext(ctx, teamGetByTeamId, arg.TeamID)
	var i TTeam
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Avatar,
		&i.ParentTeamID,
		&i.Path,
		&i.Level,
		&i.Settings,
		&i.Visibility,
		&i.IsEnabled,
		&i.TotalMembers,
		&i.TotalProjects,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const teamIncrementMembers = `-- name: TeamIncrementMembers :exec
UPDATE t_team SET total_members = total_members + ?, updated_at = ? WHERE team_id = ?
`

type TeamIncrementMembersParams struct {
	TotalMembers int32     `json:"total_members"`
	UpdatedAt    time.Time `json:"updated_at"`
	TeamID       string    `json:"team_id"`
}

// TeamIncrementMembers 团队成员数 +delta
func (q *Queries) TeamIncrementMembers(ctx context.Context, arg TeamIncrementMembersParams) error {
	_, err := q.db.ExecContext(ctx, teamIncrementMembers, arg.TotalMembers, arg.UpdatedAt, arg.TeamID)
	return err
}

const teamIncrementProjects = `-- name: TeamIncrementProjects :exec
UPDATE t_team SET total_projects = total_projects + ?, updated_at = ? WHERE team_id = ?
`

type TeamIncrementProjectsParams struct {
	TotalProjects int32     `json:"total_projects"`
	UpdatedAt     time.Time `json:"updated_at"`
	TeamID        string    `json:"team_id"`
}

// TeamIncrementProjects 团队项目数 +delta
func (q *Queries) TeamIncrementProjects(ctx context.Context, arg TeamIncrementProjectsParams) error {
	_, err := q.db.ExecContext(ctx, teamIncrementProjects, arg.TotalProjects, arg.UpdatedAt, arg.TeamID)
	return err
}

const teamList = `-- name: TeamList :many
SELECT team_id, org_id, name, display_name, description, avatar, parent_team_id, path, level, settings, visibility, is_enabled, total_members, total_projects
FROM t_team
WHERE (? = '' OR org_id = ?) AND (? = '' OR name LIKE ?) AND (? = '' OR parent_team_id = ?) AND (? IS NULL OR visibility = ?) AND (? IS NULL OR is_enabled = ?)
ORDER BY team_id DESC LIMIT ? OFFSET ?
`

type TeamListParams struct {
	Column1      interface{}    `json:"column_1"`
	OrgID        string         `json:"org_id"`
	Column3      interface{}    `json:"column_3"`
	Name         string         `json:"name"`
	Column5      interface{}    `json:"column_5"`
	ParentTeamID sql.NullString `json:"parent_team_id"`
	Column7      interface{}    `json:"column_7"`
	Visibility   int8           `json:"visibility"`
	Column9      interface{}    `json:"column_9"`
	IsEnabled    int8           `json:"is_enabled"`
	Limit        int32          `json:"limit"`
	Offset       int32          `json:"offset"`
}

type TeamListRow struct {
	TeamID        string          `json:"team_id"`
	OrgID         string          `json:"org_id"`
	Name          string          `json:"name"`
	DisplayName   string          `json:"display_name"`
	Description   sql.NullString  `json:"description"`
	Avatar        sql.NullString  `json:"avatar"`
	ParentTeamID  sql.NullString  `json:"parent_team_id"`
	Path          sql.NullString  `json:"path"`
	Level         int32           `json:"level"`
	Settings      json.RawMessage `json:"settings"`
	Visibility    int8            `json:"visibility"`
	IsEnabled     int8            `json:"is_enabled"`
	TotalMembers  int32           `json:"total_members"`
	TotalProjects int32           `json:"total_projects"`
}

// TeamList 团队列表分页
func (q *Queries) TeamList(ctx context.Context, arg TeamListParams) ([]TeamListRow, error) {
	rows, err := q.db.QueryContext(ctx, teamList,
		arg.Column1,
		arg.OrgID,
		arg.Column3,
		arg.Name,
		arg.Column5,
		arg.ParentTeamID,
		arg.Column7,
		arg.Visibility,
		arg.Column9,
		arg.IsEnabled,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamListRow{}
	for rows.Next() {
		var i TeamListRow
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.ParentTeamID,
			&i.Path,
			&i.Level,
			&i.Settings,
			&i.Visibility,
			&i.IsEnabled,
			&i.TotalMembers,
			&i.TotalProjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamListByOrg = `-- name: TeamListByOrg :many
SELECT team_id, org_id, name, display_name, description, avatar, parent_team_id, path, level, settings, visibility, is_enabled, total_members, total_projects
FROM t_team WHERE org_id = ? AND is_enabled = 1 ORDER BY level ASC, team_id DESC
`

type TeamListByOrgParams struct {
	OrgID string `json:"org_id"`
}

type TeamListByOrgRow struct {
	TeamID        string          `json:"team_id"`
	OrgID         string          `json:"org_id"`
	Name          string          `json:"name"`
	DisplayName   string          `json:"display_name"`
	Description   sql.NullString  `json:"description"`
	Avatar        sql.NullString  `json:"avatar"`
	ParentTeamID  sql.NullString  `json:"parent_team_id"`
	Path          sql.NullString  `json:"path"`
	Level         int32           `json:"level"`
	Settings      json.RawMessage `json:"settings"`
	Visibility    int8            `json:"visibility"`
	IsEnabled     int8            `json:"is_enabled"`
	TotalMembers  int32           `json:"total_members"`
	TotalProjects int32           `json:"total_projects"`
}

// TeamListByOrg 按组织获取团队列表
func (q *Queries) TeamListByOrg(ctx context.Context, arg TeamListByOrgParams) ([]TeamListByOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, teamListByOrg, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamListByOrgRow{}
	for rows.Next() {
		var i TeamListByOrgRow
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.ParentTeamID,
			&i.Path,
			&i.Level,
			&i.Settings,
			&i.Visibility,
			&i.IsEnabled,
			&i.TotalMembers,
			&i.TotalProjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamListByUser = `-- name: TeamListByUser :many
SELECT t.team_id, t.org_id, t.name, t.display_name, t.description, t.avatar, t.parent_team_id, t.path, t.level, t.settings, t.visibility, t.is_enabled, t.total_members, t.total_projects
FROM t_team t
INNER JOIN t_team_member tm ON t.team_id = tm.team_id
WHERE tm.user_id = ? AND t.is_enabled = 1 ORDER BY t.team_id DESC
`

type TeamListByUserParams struct {
	UserID string `json:"user_id"`
}

type TeamListByUserRow struct {
	TeamID        string          `json:"team_id"`
	OrgID         string          `json:"org_id"`
	Name          string          `json:"name"`
	DisplayName   string          `json:"display_name"`
	Description   sql.NullString  `json:"description"`
	Avatar        sql.NullString  `json:"avatar"`
	ParentTeamID  sql.NullString  `json:"parent_team_id"`
	Path          sql.NullString  `json:"path"`
	Level         int32           `json:"level"`
	Settings      json.RawMessage `json:"settings"`
	Visibility    int8            `json:"visibility"`
	IsEnabled     int8            `json:"is_enabled"`
	TotalMembers  int32           `json:"total_members"`
	TotalProjects int32           `json:"total_projects"`
}

// TeamListByUser 按用户获取其所属团队列表（JOIN t_team_member）
func (q *Queries) TeamListByUser(ctx context.Context, arg TeamListByUserParams) ([]TeamListByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, teamListByUser, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamListByUserRow{}
	for rows.Next() {
		var i TeamListByUserRow
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.ParentTeamID,
			&i.Path,
			&i.Level,
			&i.Settings,
			&i.Visibility,
			&i.IsEnabled,
			&i.TotalMembers,
			&i.TotalProjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamListCount = `-- name: TeamListCount :one
SELECT COUNT(*) FROM t_team
WHERE (? = '' OR org_id = ?)
  AND (? = '' OR name LIKE ?)
  AND (? = '' OR parent_team_id = ?)
  AND (? IS NULL OR visibility = ?)
  AND (? IS NULL OR is_enabled = ?)
`

type TeamListCountParams struct {
	Column1      interface{}    `json:"column_1"`
	OrgID        string         `json:"org_id"`
	Column3      interface{}    `json:"column_3"`
	Name         string         `json:"name"`
	Column5      interface{}    `json:"column_5"`
	ParentTeamID sql.NullString `json:"parent_team_id"`
	Column7      interface{}    `json:"column_7"`
	Visibility   int8           `json:"visibility"`
	Column9      interface{}    `json:"column_9"`
	IsEnabled    int8           `json:"is_enabled"`
}

// TeamListCount 团队列表总数（可选条件：org_id, name LIKE, parent_team_id, visibility, is_enabled）
func (q *Queries) TeamListCount(ctx context.Context, arg TeamListCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, teamListCount,
		arg.Column1,
		arg.OrgID,
		arg.Column3,
		arg.Name,
		arg.Column5,
		arg.ParentTeamID,
		arg.Column7,
		arg.Visibility,
		arg.Column9,
		arg.IsEnabled,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const teamListSubTeams = `-- name: TeamListSubTeams :many
SELECT team_id, org_id, name, display_name, description, avatar, parent_team_id, path, level, settings, visibility, is_enabled, total_members, total_projects
FROM t_team WHERE parent_team_id = ?
`

type TeamListSubTeamsParams struct {
	ParentTeamID sql.NullString `json:"parent_team_id"`
}

type TeamListSubTeamsRow struct {
	TeamID        string          `json:"team_id"`
	OrgID         string          `json:"org_id"`
	Name          string          `json:"name"`
	DisplayName   string          `json:"display_name"`
	Description   sql.NullString  `json:"description"`
	Avatar        sql.NullString  `json:"avatar"`
	ParentTeamID  sql.NullString  `json:"parent_team_id"`
	Path          sql.NullString  `json:"path"`
	Level         int32           `json:"level"`
	Settings      json.RawMessage `json:"settings"`
	Visibility    int8            `json:"visibility"`
	IsEnabled     int8            `json:"is_enabled"`
	TotalMembers  int32           `json:"total_members"`
	TotalProjects int32           `json:"total_projects"`
}

// TeamListSubTeams 获取子团队列表
func (q *Queries) TeamListSubTeams(ctx context.Context, arg TeamListSubTeamsParams) ([]TeamListSubTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, teamListSubTeams, arg.ParentTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamListSubTeamsRow{}
	for rows.Next() {
		var i TeamListSubTeamsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Avatar,
			&i.ParentTeamID,
			&i.Path,
			&i.Level,
			&i.Settings,
			&i.Visibility,
			&i.IsEnabled,
			&i.TotalMembers,
			&i.TotalProjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamNameExists = `-- name: TeamNameExists :one
SELECT COUNT(*) > 0 FROM t_team WHERE org_id = ? AND name = ? AND (? = '' OR team_id != ?)
`

type TeamNameExistsParams struct {
	OrgID   string      `json:"org_id"`
	Name    string      `json:"name"`
	Column3 interface{} `json:"column_3"`
	TeamID  string      `json:"team_id"`
}

// TeamNameExists 判断组织下团队名称是否存在（可排除指定 team_id）
func (q *Queries) TeamNameExists(ctx context.Context, arg TeamNameExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, teamNameExists,
		arg.OrgID,
		arg.Name,
		arg.Column3,
		arg.TeamID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const teamUpdateByTeamId = `-- name: TeamUpdateByTeamId :exec
UPDATE t_team SET display_name = ?, description = ?, avatar = ?, settings = ?, visibility = ?, is_enabled = ?, updated_at = ? WHERE team_id = ?
`

type TeamUpdateByTeamIdParams struct {
	DisplayName string          `json:"display_name"`
	Description sql.NullString  `json:"description"`
	Avatar      sql.NullString  `json:"avatar"`
	Settings    json.RawMessage `json:"settings"`
	Visibility  int8            `json:"visibility"`
	IsEnabled   int8            `json:"is_enabled"`
	UpdatedAt   time.Time       `json:"updated_at"`
	TeamID      string          `json:"team_id"`
}

// TeamUpdateByTeamId 按 team_id 更新团队（动态字段由调用方传入）
func (q *Queries) TeamUpdateByTeamId(ctx context.Context, arg TeamUpdateByTeamIdParams) error {
	_, err := q.db.ExecContext(ctx, teamUpdateByTeamId,
		arg.DisplayName,
		arg.Description,
		arg.Avatar,
		arg.Settings,
		arg.Visibility,
		arg.IsEnabled,
		arg.UpdatedAt,
		arg.TeamID,
	)
	return err
}

const teamUpdatePath = `-- name: TeamUpdatePath :exec
UPDATE t_team SET path = ?, level = ?, updated_at = ? WHERE team_id = ?
`

type TeamUpdatePathParams struct {
	Path      sql.NullString `json:"path"`
	Level     int32          `json:"level"`
	UpdatedAt time.Time      `json:"updated_at"`
	TeamID    string         `json:"team_id"`
}

// TeamUpdatePath 更新团队 path 与 level
func (q *Queries) TeamUpdatePath(ctx context.Context, arg TeamUpdatePathParams) error {
	_, err := q.db.ExecContext(ctx, teamUpdatePath,
		arg.Path,
		arg.Level,
		arg.UpdatedAt,
		arg.TeamID,
	)
	return err
}

const teamUpdateStatistics = `-- name: TeamUpdateStatistics :exec
UPDATE t_team SET total_members = ?, total_projects = ?, updated_at = ? WHERE team_id = ?
`

type TeamUpdateStatisticsParams struct {
	TotalMembers  int32     `json:"total_members"`
	TotalProjects int32     `json:"total_projects"`
	UpdatedAt     time.Time `json:"updated_at"`
	TeamID        string    `json:"team_id"`
}

// TeamUpdateStatistics 更新团队统计（total_members, total_projects）
func (q *Queries) TeamUpdateStatistics(ctx context.Context, arg TeamUpdateStatisticsParams) error {
	_, err := q.db.ExecContext(ctx, teamUpdateStatistics,
		arg.TotalMembers,
		arg.TotalProjects,
		arg.UpdatedAt,
		arg.TeamID,
	)
	return err
}
