// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_member.sql

package dal

import (
	"context"
	"time"
)

const teamMemberAdd = `-- name: TeamMemberAdd :exec
INSERT INTO t_team_member (team_id, user_id, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type TeamMemberAddParams struct {
	TeamID    string    `json:"team_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TeamMemberAdd 添加团队成员
func (q *Queries) TeamMemberAdd(ctx context.Context, arg TeamMemberAddParams) error {
	_, err := q.db.ExecContext(ctx, teamMemberAdd,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const teamMemberGet = `-- name: TeamMemberGet :one

SELECT id, team_id, user_id, role, created_at, updated_at FROM t_team_member WHERE team_id = ? AND user_id = ? LIMIT 1
`

type TeamMemberGetParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

type TeamMemberGetRow struct {
	ID        int32     `json:"id"`
	TeamID    string    `json:"team_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// TeamMemberGet 按 team_id 与 user_id 获取团队成员
func (q *Queries) TeamMemberGet(ctx context.Context, arg TeamMemberGetParams) (TeamMemberGetRow, error) {
	row := q.db.QueryRowContext(ctx, teamMemberGet, arg.TeamID, arg.UserID)
	var i TeamMemberGetRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const teamMemberListByTeamId = `-- name: TeamMemberListByTeamId :many
SELECT id, team_id, user_id, role, created_at, updated_at FROM t_team_member WHERE team_id = ?
`

type TeamMemberListByTeamIdParams struct {
	TeamID string `json:"team_id"`
}

type TeamMemberListByTeamIdRow struct {
	ID        int32     `json:"id"`
	TeamID    string    `json:"team_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TeamMemberListByTeamId 按 team_id 列出成员
func (q *Queries) TeamMemberListByTeamId(ctx context.Context, arg TeamMemberListByTeamIdParams) ([]TeamMemberListByTeamIdRow, error) {
	rows, err := q.db.QueryContext(ctx, teamMemberListByTeamId, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMemberListByTeamIdRow{}
	for rows.Next() {
		var i TeamMemberListByTeamIdRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamMemberListByUserId = `-- name: TeamMemberListByUserId :many
SELECT id, team_id, user_id, role, created_at, updated_at FROM t_team_member WHERE user_id = ?
`

type TeamMemberListByUserIdParams struct {
	UserID string `json:"user_id"`
}

type TeamMemberListByUserIdRow struct {
	ID        int32     `json:"id"`
	TeamID    string    `json:"team_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// TeamMemberListByUserId 按 user_id 列出其团队成员关系
func (q *Queries) TeamMemberListByUserId(ctx context.Context, arg TeamMemberListByUserIdParams) ([]TeamMemberListByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, teamMemberListByUserId, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMemberListByUserIdRow{}
	for rows.Next() {
		var i TeamMemberListByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamMemberRemove = `-- name: TeamMemberRemove :exec
DELETE FROM t_team_member WHERE team_id = ? AND user_id = ?
`

type TeamMemberRemoveParams struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

// TeamMemberRemove 移除团队成员
func (q *Queries) TeamMemberRemove(ctx context.Context, arg TeamMemberRemoveParams) error {
	_, err := q.db.ExecContext(ctx, teamMemberRemove, arg.TeamID, arg.UserID)
	return err
}

const teamMemberUpdateRole = `-- name: TeamMemberUpdateRole :exec
UPDATE t_team_member SET role = ?, updated_at = ? WHERE team_id = ? AND user_id = ?
`

type TeamMemberUpdateRoleParams struct {
	Role      string    `json:"role"`
	UpdatedAt time.Time `json:"updated_at"`
	TeamID    string    `json:"team_id"`
	UserID    string    `json:"user_id"`
}

// TeamMemberUpdateRole 更新团队成员角色
func (q *Queries) TeamMemberUpdateRole(ctx context.Context, arg TeamMemberUpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, teamMemberUpdateRole,
		arg.Role,
		arg.UpdatedAt,
		arg.TeamID,
		arg.UserID,
	)
	return err
}
