// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_ext.sql

package dal

import (
	"context"
	"database/sql"
)

const userExtCreate = `-- name: UserExtCreate :exec

INSERT INTO t_user_ext (user_id, timezone, last_login_at, invitation_status, invited_by, invited_at, accepted_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UserExtCreateParams struct {
	UserID           string         `json:"user_id"`
	Timezone         sql.NullString `json:"timezone"`
	LastLoginAt      sql.NullTime   `json:"last_login_at"`
	InvitationStatus sql.NullString `json:"invitation_status"`
	InvitedBy        sql.NullString `json:"invited_by"`
	InvitedAt        sql.NullTime   `json:"invited_at"`
	AcceptedAt       sql.NullTime   `json:"accepted_at"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// UserExtCreate 创建用户扩展
func (q *Queries) UserExtCreate(ctx context.Context, arg UserExtCreateParams) error {
	_, err := q.db.ExecContext(ctx, userExtCreate,
		arg.UserID,
		arg.Timezone,
		arg.LastLoginAt,
		arg.InvitationStatus,
		arg.InvitedBy,
		arg.InvitedAt,
		arg.AcceptedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const userExtDeleteByUserId = `-- name: UserExtDeleteByUserId :exec
DELETE FROM t_user_ext WHERE user_id = ?
`

type UserExtDeleteByUserIdParams struct {
	UserID string `json:"user_id"`
}

// UserExtDeleteByUserId 按 user_id 删除用户扩展
func (q *Queries) UserExtDeleteByUserId(ctx context.Context, arg UserExtDeleteByUserIdParams) error {
	_, err := q.db.ExecContext(ctx, userExtDeleteByUserId, arg.UserID)
	return err
}

const userExtExistsByUserId = `-- name: UserExtExistsByUserId :one
SELECT COUNT(*) > 0 FROM t_user_ext WHERE user_id = ?
`

type UserExtExistsByUserIdParams struct {
	UserID string `json:"user_id"`
}

// UserExtExistsByUserId 判断用户扩展是否存在
func (q *Queries) UserExtExistsByUserId(ctx context.Context, arg UserExtExistsByUserIdParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExtExistsByUserId, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const userExtGetByUserId = `-- name: UserExtGetByUserId :one
SELECT id, user_id, timezone, last_login_at, invitation_status, invited_by, invited_at, accepted_at, created_at, updated_at FROM t_user_ext WHERE user_id = ? LIMIT 1
`

type UserExtGetByUserIdParams struct {
	UserID string `json:"user_id"`
}

// UserExtGetByUserId 按 user_id 获取用户扩展
func (q *Queries) UserExtGetByUserId(ctx context.Context, arg UserExtGetByUserIdParams) (TUserExt, error) {
	row := q.db.QueryRowContext(ctx, userExtGetByUserId, arg.UserID)
	var i TUserExt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Timezone,
		&i.LastLoginAt,
		&i.InvitationStatus,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExtUpdateByUserId = `-- name: UserExtUpdateByUserId :exec
UPDATE t_user_ext SET timezone = ?, last_login_at = ?, invitation_status = ?, invited_by = ?, invited_at = ?, accepted_at = ?, updated_at = ? WHERE user_id = ?
`

type UserExtUpdateByUserIdParams struct {
	Timezone         sql.NullString `json:"timezone"`
	LastLoginAt      sql.NullTime   `json:"last_login_at"`
	InvitationStatus sql.NullString `json:"invitation_status"`
	InvitedBy        sql.NullString `json:"invited_by"`
	InvitedAt        sql.NullTime   `json:"invited_at"`
	AcceptedAt       sql.NullTime   `json:"accepted_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	UserID           string         `json:"user_id"`
}

// UserExtUpdateByUserId 按 user_id 更新用户扩展
func (q *Queries) UserExtUpdateByUserId(ctx context.Context, arg UserExtUpdateByUserIdParams) error {
	_, err := q.db.ExecContext(ctx, userExtUpdateByUserId,
		arg.Timezone,
		arg.LastLoginAt,
		arg.InvitationStatus,
		arg.InvitedBy,
		arg.InvitedAt,
		arg.AcceptedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const userExtUpdateInvitationStatus = `-- name: UserExtUpdateInvitationStatus :exec
UPDATE t_user_ext SET invitation_status = ?, accepted_at = CASE WHEN ? = 'accepted' THEN ? ELSE accepted_at END, updated_at = ? WHERE user_id = ?
`

type UserExtUpdateInvitationStatusParams struct {
	InvitationStatus sql.NullString `json:"invitation_status"`
	Column2          interface{}    `json:"column_2"`
	AcceptedAt       sql.NullTime   `json:"accepted_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	UserID           string         `json:"user_id"`
}

// UserExtUpdateInvitationStatus 更新邀请状态（accepted 时写 accepted_at）
func (q *Queries) UserExtUpdateInvitationStatus(ctx context.Context, arg UserExtUpdateInvitationStatusParams) error {
	_, err := q.db.ExecContext(ctx, userExtUpdateInvitationStatus,
		arg.InvitationStatus,
		arg.Column2,
		arg.AcceptedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const userExtUpdateLastLogin = `-- name: UserExtUpdateLastLogin :exec
UPDATE t_user_ext SET last_login_at = ?, updated_at = ? WHERE user_id = ?
`

type UserExtUpdateLastLoginParams struct {
	LastLoginAt sql.NullTime `json:"last_login_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	UserID      string       `json:"user_id"`
}

// UserExtUpdateLastLogin 更新最后登录时间
func (q *Queries) UserExtUpdateLastLogin(ctx context.Context, arg UserExtUpdateLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, userExtUpdateLastLogin, arg.LastLoginAt, arg.UpdatedAt, arg.UserID)
	return err
}

const userExtUpdateTimezone = `-- name: UserExtUpdateTimezone :exec
UPDATE t_user_ext SET timezone = ?, updated_at = ? WHERE user_id = ?
`

type UserExtUpdateTimezoneParams struct {
	Timezone  sql.NullString `json:"timezone"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UserID    string         `json:"user_id"`
}

// UserExtUpdateTimezone 更新时区
func (q *Queries) UserExtUpdateTimezone(ctx context.Context, arg UserExtUpdateTimezoneParams) error {
	_, err := q.db.ExecContext(ctx, userExtUpdateTimezone, arg.Timezone, arg.UpdatedAt, arg.UserID)
	return err
}
