// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_role_binding.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const userRoleBindingCreate = `-- name: UserRoleBindingCreate :exec
INSERT INTO t_user_role_binding (binding_id, user_id, role_id, granted_by, create_time, update_time)
VALUES (?, ?, ?, ?, ?, ?)
`

type UserRoleBindingCreateParams struct {
	BindingID  string         `json:"binding_id"`
	UserID     string         `json:"user_id"`
	RoleID     string         `json:"role_id"`
	GrantedBy  sql.NullString `json:"granted_by"`
	CreateTime time.Time      `json:"create_time"`
	UpdateTime time.Time      `json:"update_time"`
}

// UserRoleBindingCreate 创建用户角色绑定
func (q *Queries) UserRoleBindingCreate(ctx context.Context, arg UserRoleBindingCreateParams) error {
	_, err := q.db.ExecContext(ctx, userRoleBindingCreate,
		arg.BindingID,
		arg.UserID,
		arg.RoleID,
		arg.GrantedBy,
		arg.CreateTime,
		arg.UpdateTime,
	)
	return err
}

const userRoleBindingDeleteByBindingId = `-- name: UserRoleBindingDeleteByBindingId :exec
DELETE FROM t_user_role_binding WHERE binding_id = ?
`

type UserRoleBindingDeleteByBindingIdParams struct {
	BindingID string `json:"binding_id"`
}

// UserRoleBindingDeleteByBindingId 按 binding_id 删除
func (q *Queries) UserRoleBindingDeleteByBindingId(ctx context.Context, arg UserRoleBindingDeleteByBindingIdParams) error {
	_, err := q.db.ExecContext(ctx, userRoleBindingDeleteByBindingId, arg.BindingID)
	return err
}

const userRoleBindingDeleteByUserId = `-- name: UserRoleBindingDeleteByUserId :exec
DELETE FROM t_user_role_binding WHERE user_id = ?
`

type UserRoleBindingDeleteByUserIdParams struct {
	UserID string `json:"user_id"`
}

// UserRoleBindingDeleteByUserId 按 user_id 删除该用户全部绑定
func (q *Queries) UserRoleBindingDeleteByUserId(ctx context.Context, arg UserRoleBindingDeleteByUserIdParams) error {
	_, err := q.db.ExecContext(ctx, userRoleBindingDeleteByUserId, arg.UserID)
	return err
}

const userRoleBindingGetByUserIdAndRoleId = `-- name: UserRoleBindingGetByUserIdAndRoleId :one
SELECT binding_id, user_id, role_id, granted_by, create_time, update_time FROM t_user_role_binding WHERE user_id = ? AND role_id = ? LIMIT 1
`

type UserRoleBindingGetByUserIdAndRoleIdParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

type UserRoleBindingGetByUserIdAndRoleIdRow struct {
	BindingID  string         `json:"binding_id"`
	UserID     string         `json:"user_id"`
	RoleID     string         `json:"role_id"`
	GrantedBy  sql.NullString `json:"granted_by"`
	CreateTime time.Time      `json:"create_time"`
	UpdateTime time.Time      `json:"update_time"`
}

// UserRoleBindingGetByUserIdAndRoleId 按 user_id 与 role_id 获取绑定
func (q *Queries) UserRoleBindingGetByUserIdAndRoleId(ctx context.Context, arg UserRoleBindingGetByUserIdAndRoleIdParams) (UserRoleBindingGetByUserIdAndRoleIdRow, error) {
	row := q.db.QueryRowContext(ctx, userRoleBindingGetByUserIdAndRoleId, arg.UserID, arg.RoleID)
	var i UserRoleBindingGetByUserIdAndRoleIdRow
	err := row.Scan(
		&i.BindingID,
		&i.UserID,
		&i.RoleID,
		&i.GrantedBy,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const userRoleBindingListByUserId = `-- name: UserRoleBindingListByUserId :many

SELECT binding_id, user_id, role_id, granted_by, create_time, update_time FROM t_user_role_binding WHERE user_id = ?
`

type UserRoleBindingListByUserIdParams struct {
	UserID string `json:"user_id"`
}

type UserRoleBindingListByUserIdRow struct {
	BindingID  string         `json:"binding_id"`
	UserID     string         `json:"user_id"`
	RoleID     string         `json:"role_id"`
	GrantedBy  sql.NullString `json:"granted_by"`
	CreateTime time.Time      `json:"create_time"`
	UpdateTime time.Time      `json:"update_time"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// UserRoleBindingListByUserId 按 user_id 列出用户角色绑定
func (q *Queries) UserRoleBindingListByUserId(ctx context.Context, arg UserRoleBindingListByUserIdParams) ([]UserRoleBindingListByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, userRoleBindingListByUserId, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoleBindingListByUserIdRow{}
	for rows.Next() {
		var i UserRoleBindingListByUserIdRow
		if err := rows.Scan(
			&i.BindingID,
			&i.UserID,
			&i.RoleID,
			&i.GrantedBy,
			&i.CreateTime,
			&i.UpdateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
