// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package dal

import (
	"context"
	"database/sql"
	"time"
)

const userCount = `-- name: UserCount :one
SELECT COUNT(*) FROM t_user
`

// UserCount 用户总数
func (q *Queries) UserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, userCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userCreate = `-- name: UserCreate :exec

INSERT INTO t_user (user_id, username, full_name, avatar, email, phone, password, is_enabled, is_super_admin, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type UserCreateParams struct {
	UserID       string         `json:"user_id"`
	Username     string         `json:"username"`
	FullName     sql.NullString `json:"full_name"`
	Avatar       sql.NullString `json:"avatar"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	Password     string         `json:"password"`
	IsEnabled    int8           `json:"is_enabled"`
	IsSuperAdmin int8           `json:"is_super_admin"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// Copyright 2026 Arcentra Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// UserCreate 创建用户（AddUserReq -> t_user）
func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) error {
	_, err := q.db.ExecContext(ctx, userCreate,
		arg.UserID,
		arg.Username,
		arg.FullName,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.IsEnabled,
		arg.IsSuperAdmin,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const userDeleteByUserId = `-- name: UserDeleteByUserId :exec
DELETE FROM t_user WHERE user_id = ?
`

type UserDeleteByUserIdParams struct {
	UserID string `json:"user_id"`
}

// UserDeleteByUserId 按 user_id 删除用户
func (q *Queries) UserDeleteByUserId(ctx context.Context, arg UserDeleteByUserIdParams) error {
	_, err := q.db.ExecContext(ctx, userDeleteByUserId, arg.UserID)
	return err
}

const userFetchInfoByUserId = `-- name: UserFetchInfoByUserId :one
SELECT user_id, username, full_name, avatar, email, phone FROM t_user WHERE user_id = ? LIMIT 1
`

type UserFetchInfoByUserIdParams struct {
	UserID string `json:"user_id"`
}

type UserFetchInfoByUserIdRow struct {
	UserID   string         `json:"user_id"`
	Username string         `json:"username"`
	FullName sql.NullString `json:"full_name"`
	Avatar   sql.NullString `json:"avatar"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
}

// UserFetchInfoByUserId 获取用户基本信息（不含 password）
func (q *Queries) UserFetchInfoByUserId(ctx context.Context, arg UserFetchInfoByUserIdParams) (UserFetchInfoByUserIdRow, error) {
	row := q.db.QueryRowContext(ctx, userFetchInfoByUserId, arg.UserID)
	var i UserFetchInfoByUserIdRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Phone,
	)
	return i, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT id, user_id, username, full_name, avatar, email, phone, is_enabled, is_super_admin, created_at, updated_at
FROM t_user WHERE email = ? LIMIT 1
`

type UserGetByEmailParams struct {
	Email sql.NullString `json:"email"`
}

type UserGetByEmailRow struct {
	ID           int32          `json:"id"`
	UserID       string         `json:"user_id"`
	Username     string         `json:"username"`
	FullName     sql.NullString `json:"full_name"`
	Avatar       sql.NullString `json:"avatar"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	IsEnabled    int8           `json:"is_enabled"`
	IsSuperAdmin int8           `json:"is_super_admin"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// UserGetByEmail 按 email 获取用户（不含 password）
func (q *Queries) UserGetByEmail(ctx context.Context, arg UserGetByEmailParams) (UserGetByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, userGetByEmail, arg.Email)
	var i UserGetByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.IsEnabled,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userGetByUserId = `-- name: UserGetByUserId :one
SELECT id, user_id, username, full_name, password, avatar, email, phone, is_enabled, is_super_admin, created_at, updated_at FROM t_user WHERE user_id = ? LIMIT 1
`

type UserGetByUserIdParams struct {
	UserID string `json:"user_id"`
}

// UserGetByUserId 按 user_id 获取用户
func (q *Queries) UserGetByUserId(ctx context.Context, arg UserGetByUserIdParams) (TUser, error) {
	row := q.db.QueryRowContext(ctx, userGetByUserId, arg.UserID)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FullName,
		&i.Password,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.IsEnabled,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userGetByUsername = `-- name: UserGetByUsername :one
SELECT id, user_id, username, full_name, avatar, email, phone, is_enabled, is_super_admin, created_at, updated_at
FROM t_user WHERE username = ? LIMIT 1
`

type UserGetByUsernameParams struct {
	Username string `json:"username"`
}

type UserGetByUsernameRow struct {
	ID           int32          `json:"id"`
	UserID       string         `json:"user_id"`
	Username     string         `json:"username"`
	FullName     sql.NullString `json:"full_name"`
	Avatar       sql.NullString `json:"avatar"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	IsEnabled    int8           `json:"is_enabled"`
	IsSuperAdmin int8           `json:"is_super_admin"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// UserGetByUsername 按 username 获取用户（不含 password）
func (q *Queries) UserGetByUsername(ctx context.Context, arg UserGetByUsernameParams) (UserGetByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, userGetByUsername, arg.Username)
	var i UserGetByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.IsEnabled,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userGetPasswordByUserId = `-- name: UserGetPasswordByUserId :one
SELECT password FROM t_user WHERE user_id = ? LIMIT 1
`

type UserGetPasswordByUserIdParams struct {
	UserID string `json:"user_id"`
}

// UserGetPasswordByUserId 获取用户密码哈希
func (q *Queries) UserGetPasswordByUserId(ctx context.Context, arg UserGetPasswordByUserIdParams) (string, error) {
	row := q.db.QueryRowContext(ctx, userGetPasswordByUserId, arg.UserID)
	var password string
	err := row.Scan(&password)
	return password, err
}

const userGetUserIdByUsername = `-- name: UserGetUserIdByUsername :one
SELECT user_id FROM t_user WHERE username = ? LIMIT 1
`

type UserGetUserIdByUsernameParams struct {
	Username string `json:"username"`
}

// UserGetUserIdByUsername 按 username 获取 user_id
func (q *Queries) UserGetUserIdByUsername(ctx context.Context, arg UserGetUserIdByUsernameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, userGetUserIdByUsername, arg.Username)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const userListSimple = `-- name: UserListSimple :many
SELECT id, user_id, username, full_name, avatar, email, phone, is_enabled, is_super_admin, created_at, updated_at
FROM t_user ORDER BY id DESC LIMIT ? OFFSET ?
`

type UserListSimpleParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type UserListSimpleRow struct {
	ID           int32          `json:"id"`
	UserID       string         `json:"user_id"`
	Username     string         `json:"username"`
	FullName     sql.NullString `json:"full_name"`
	Avatar       sql.NullString `json:"avatar"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	IsEnabled    int8           `json:"is_enabled"`
	IsSuperAdmin int8           `json:"is_super_admin"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

// UserListSimple 简单用户列表（不含 password，按 id DESC 分页）
func (q *Queries) UserListSimple(ctx context.Context, arg UserListSimpleParams) ([]UserListSimpleRow, error) {
	rows, err := q.db.QueryContext(ctx, userListSimple, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserListSimpleRow{}
	for rows.Next() {
		var i UserListSimpleRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.FullName,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.IsEnabled,
			&i.IsSuperAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userListWithExtAndRole = `-- name: UserListWithExtAndRole :many
SELECT u.user_id, u.username, u.full_name, u.avatar, u.email, u.phone, u.is_enabled, u.is_super_admin, ue.last_login_at, COALESCE(ue.invitation_status, 'accepted') AS invitation_status, role.role_name
FROM t_user u
LEFT JOIN t_user_ext ue ON ue.user_id = u.user_id
LEFT JOIN (
  SELECT user_id, name AS role_name FROM (
    SELECT urb.user_id, r.name, ROW_NUMBER() OVER (PARTITION BY urb.user_id ORDER BY urb.create_time ASC) rn
    FROM t_user_role_binding urb JOIN t_role r ON r.role_id = urb.role_id WHERE r.is_enabled = 1
  ) t WHERE rn = 1
) role ON role.user_id = u.user_id
ORDER BY u.created_at DESC LIMIT ? OFFSET ?
`

type UserListWithExtAndRoleParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type UserListWithExtAndRoleRow struct {
	UserID           string         `json:"user_id"`
	Username         string         `json:"username"`
	FullName         sql.NullString `json:"full_name"`
	Avatar           sql.NullString `json:"avatar"`
	Email            sql.NullString `json:"email"`
	Phone            sql.NullString `json:"phone"`
	IsEnabled        int8           `json:"is_enabled"`
	IsSuperAdmin     int8           `json:"is_super_admin"`
	LastLoginAt      sql.NullTime   `json:"last_login_at"`
	InvitationStatus string         `json:"invitation_status"`
	RoleName         string         `json:"role_name"`
}

// UserListWithExtAndRole 用户列表（含扩展表与角色名，分页）
func (q *Queries) UserListWithExtAndRole(ctx context.Context, arg UserListWithExtAndRoleParams) ([]UserListWithExtAndRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, userListWithExtAndRole, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserListWithExtAndRoleRow{}
	for rows.Next() {
		var i UserListWithExtAndRoleRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FullName,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.IsEnabled,
			&i.IsSuperAdmin,
			&i.LastLoginAt,
			&i.InvitationStatus,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userListWithExtAndRoleByRoleId = `-- name: UserListWithExtAndRoleByRoleId :many
SELECT u.user_id, u.username, u.full_name, u.avatar, u.email, u.phone, u.is_enabled, u.is_super_admin, ue.last_login_at, COALESCE(ue.invitation_status, 'accepted') AS invitation_status, role.role_name
FROM t_user u
LEFT JOIN t_user_ext ue ON ue.user_id = u.user_id
INNER JOIN (SELECT DISTINCT urb.user_id, r.name AS role_name FROM t_user_role_binding urb JOIN t_role r ON r.role_id = urb.role_id WHERE r.is_enabled = 1 AND urb.role_id = ?) role ON role.user_id = u.user_id
ORDER BY u.created_at DESC LIMIT ? OFFSET ?
`

type UserListWithExtAndRoleByRoleIdParams struct {
	RoleID string `json:"role_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type UserListWithExtAndRoleByRoleIdRow struct {
	UserID           string         `json:"user_id"`
	Username         string         `json:"username"`
	FullName         sql.NullString `json:"full_name"`
	Avatar           sql.NullString `json:"avatar"`
	Email            sql.NullString `json:"email"`
	Phone            sql.NullString `json:"phone"`
	IsEnabled        int8           `json:"is_enabled"`
	IsSuperAdmin     int8           `json:"is_super_admin"`
	LastLoginAt      sql.NullTime   `json:"last_login_at"`
	InvitationStatus string         `json:"invitation_status"`
	RoleName         string         `json:"role_name"`
}

// UserListWithExtAndRoleByRoleId 按 role_id 过滤的用户列表（含扩展与角色名）
func (q *Queries) UserListWithExtAndRoleByRoleId(ctx context.Context, arg UserListWithExtAndRoleByRoleIdParams) ([]UserListWithExtAndRoleByRoleIdRow, error) {
	rows, err := q.db.QueryContext(ctx, userListWithExtAndRoleByRoleId, arg.RoleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserListWithExtAndRoleByRoleIdRow{}
	for rows.Next() {
		var i UserListWithExtAndRoleByRoleIdRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FullName,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.IsEnabled,
			&i.IsSuperAdmin,
			&i.LastLoginAt,
			&i.InvitationStatus,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userListWithExtAndRoleByRoleIdCount = `-- name: UserListWithExtAndRoleByRoleIdCount :one
SELECT COUNT(*) FROM t_user u
LEFT JOIN t_user_ext ue ON ue.user_id = u.user_id
INNER JOIN (SELECT DISTINCT urb.user_id FROM t_user_role_binding urb JOIN t_role r ON r.role_id = urb.role_id WHERE r.is_enabled = 1 AND urb.role_id = ?) role ON role.user_id = u.user_id
`

type UserListWithExtAndRoleByRoleIdCountParams struct {
	RoleID string `json:"role_id"`
}

// UserListWithExtAndRoleByRoleIdCount 按 role_id 过滤的用户总数
func (q *Queries) UserListWithExtAndRoleByRoleIdCount(ctx context.Context, arg UserListWithExtAndRoleByRoleIdCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userListWithExtAndRoleByRoleIdCount, arg.RoleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userListWithExtAndRoleByRoleName = `-- name: UserListWithExtAndRoleByRoleName :many
SELECT u.user_id, u.username, u.full_name, u.avatar, u.email, u.phone, u.is_enabled, u.is_super_admin, ue.last_login_at, COALESCE(ue.invitation_status, 'accepted') AS invitation_status, role.role_name
FROM t_user u
LEFT JOIN t_user_ext ue ON ue.user_id = u.user_id
INNER JOIN (
  SELECT user_id, name AS role_name FROM (
    SELECT urb.user_id, r.name, ROW_NUMBER() OVER (PARTITION BY urb.user_id ORDER BY urb.create_time ASC) rn
    FROM t_user_role_binding urb JOIN t_role r ON r.role_id = urb.role_id WHERE r.is_enabled = 1 AND r.name = ?
  ) t WHERE rn = 1
) role ON role.user_id = u.user_id
ORDER BY u.created_at DESC LIMIT ? OFFSET ?
`

type UserListWithExtAndRoleByRoleNameParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type UserListWithExtAndRoleByRoleNameRow struct {
	UserID           string         `json:"user_id"`
	Username         string         `json:"username"`
	FullName         sql.NullString `json:"full_name"`
	Avatar           sql.NullString `json:"avatar"`
	Email            sql.NullString `json:"email"`
	Phone            sql.NullString `json:"phone"`
	IsEnabled        int8           `json:"is_enabled"`
	IsSuperAdmin     int8           `json:"is_super_admin"`
	LastLoginAt      sql.NullTime   `json:"last_login_at"`
	InvitationStatus string         `json:"invitation_status"`
	RoleName         string         `json:"role_name"`
}

// UserListWithExtAndRoleByRoleName 按角色名过滤的用户列表（含扩展与角色名）
func (q *Queries) UserListWithExtAndRoleByRoleName(ctx context.Context, arg UserListWithExtAndRoleByRoleNameParams) ([]UserListWithExtAndRoleByRoleNameRow, error) {
	rows, err := q.db.QueryContext(ctx, userListWithExtAndRoleByRoleName, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserListWithExtAndRoleByRoleNameRow{}
	for rows.Next() {
		var i UserListWithExtAndRoleByRoleNameRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.FullName,
			&i.Avatar,
			&i.Email,
			&i.Phone,
			&i.IsEnabled,
			&i.IsSuperAdmin,
			&i.LastLoginAt,
			&i.InvitationStatus,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userListWithExtAndRoleByRoleNameCount = `-- name: UserListWithExtAndRoleByRoleNameCount :one
SELECT COUNT(*) FROM t_user u
LEFT JOIN t_user_ext ue ON ue.user_id = u.user_id
INNER JOIN (SELECT user_id FROM (SELECT urb.user_id, ROW_NUMBER() OVER (PARTITION BY urb.user_id ORDER BY urb.create_time ASC) rn FROM t_user_role_binding urb JOIN t_role r ON r.role_id = urb.role_id WHERE r.is_enabled = 1 AND r.name = ?) t WHERE rn = 1) role ON role.user_id = u.user_id
`

type UserListWithExtAndRoleByRoleNameCountParams struct {
	Name string `json:"name"`
}

// UserListWithExtAndRoleByRoleNameCount 按角色名过滤的用户总数
func (q *Queries) UserListWithExtAndRoleByRoleNameCount(ctx context.Context, arg UserListWithExtAndRoleByRoleNameCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userListWithExtAndRoleByRoleNameCount, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userListWithExtAndRoleCount = `-- name: UserListWithExtAndRoleCount :one
SELECT COUNT(*) FROM t_user u
LEFT JOIN t_user_ext ue ON ue.user_id = u.user_id
LEFT JOIN (
  SELECT user_id FROM (SELECT urb.user_id, ROW_NUMBER() OVER (PARTITION BY urb.user_id ORDER BY urb.create_time ASC) rn FROM t_user_role_binding urb JOIN t_role r ON r.role_id = urb.role_id WHERE r.is_enabled = 1) t WHERE rn = 1
) role ON role.user_id = u.user_id
`

// UserListWithExtAndRoleCount 用户列表总数（无角色过滤，与 UserListWithExtAndRole 对应）
func (q *Queries) UserListWithExtAndRoleCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, userListWithExtAndRoleCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userLogin = `-- name: UserLogin :one
SELECT user_id, username, full_name, avatar, email, phone, password FROM t_user WHERE (username = ? OR email = ?) AND is_enabled = 1 LIMIT 1
`

type UserLoginParams struct {
	Username string         `json:"username"`
	Email    sql.NullString `json:"email"`
}

type UserLoginRow struct {
	UserID   string         `json:"user_id"`
	Username string         `json:"username"`
	FullName sql.NullString `json:"full_name"`
	Avatar   sql.NullString `json:"avatar"`
	Email    sql.NullString `json:"email"`
	Phone    sql.NullString `json:"phone"`
	Password string         `json:"password"`
}

// UserLogin 登录（username 或 email + is_enabled=1）
func (q *Queries) UserLogin(ctx context.Context, arg UserLoginParams) (UserLoginRow, error) {
	row := q.db.QueryRowContext(ctx, userLogin, arg.Username, arg.Email)
	var i UserLoginRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.FullName,
		&i.Avatar,
		&i.Email,
		&i.Phone,
		&i.Password,
	)
	return i, err
}

const userResetPasswordByUserId = `-- name: UserResetPasswordByUserId :exec
UPDATE t_user SET password = ?, updated_at = ? WHERE user_id = ?
`

type UserResetPasswordByUserIdParams struct {
	Password  string    `json:"password"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    string    `json:"user_id"`
}

// UserResetPasswordByUserId 重置密码
func (q *Queries) UserResetPasswordByUserId(ctx context.Context, arg UserResetPasswordByUserIdParams) error {
	_, err := q.db.ExecContext(ctx, userResetPasswordByUserId, arg.Password, arg.UpdatedAt, arg.UserID)
	return err
}

const userUpdateByUserId = `-- name: UserUpdateByUserId :exec
UPDATE t_user SET full_name = ?, avatar = ?, email = ?, phone = ?, is_enabled = ?, is_super_admin = ?, updated_at = ? WHERE user_id = ?
`

type UserUpdateByUserIdParams struct {
	FullName     sql.NullString `json:"full_name"`
	Avatar       sql.NullString `json:"avatar"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	IsEnabled    int8           `json:"is_enabled"`
	IsSuperAdmin int8           `json:"is_super_admin"`
	UpdatedAt    time.Time      `json:"updated_at"`
	UserID       string         `json:"user_id"`
}

// UserUpdateByUserId 按 user_id 更新（动态字段，不含 user_id/username/created_at）
func (q *Queries) UserUpdateByUserId(ctx context.Context, arg UserUpdateByUserIdParams) error {
	_, err := q.db.ExecContext(ctx, userUpdateByUserId,
		arg.FullName,
		arg.Avatar,
		arg.Email,
		arg.Phone,
		arg.IsEnabled,
		arg.IsSuperAdmin,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}
